import { v } from 'convex/values'
import type { Doc, Id } from '../../_generated/dataModel'
import { permissionedMutation, permissionedQuery } from '../../lib/auth'
import { asDomainMutationCtx } from '../../lib/mutationContext'
import { decimalToScaledInt64, scaledInt64ToDecimal } from '../../lib/decimal'
import { synieError } from '../../lib/errors'
import { paginationOptions, requireSearchTerm, resourcePage } from '../../lib/pagination'
import { writeAudit } from '../../platform/audit/write'
import { nextInMutation } from '../../platform/numbering/service'

function categoryPresent(row:Doc<'materialCategories'>){return{id:row._id,code:row.code,name:row.name,isLeaf:row.isLeaf,active:row.active,parentId:row.parentId,insertedAt:row.insertedAt,updatedAt:row.updatedAt}}
async function categoryParent(ctx:{db:any},self:Id<'materialCategories'>|null,parentId:Id<'materialCategories'>|null){let cursor=parentId;for(let depth=0;cursor;depth++){if(depth>=100||cursor===self)throw synieError('validation','物料分类上级形成循环');const parent=await ctx.db.get(cursor) as Doc<'materialCategories'>|null;if(!parent)throw synieError('validation','上级物料分类不存在');cursor=parent.parentId}}
export const getCategory=permissionedQuery('inv.material_category:read')({args:{id:v.id('materialCategories')},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);return row?categoryPresent(row):null}})
export const listCategories=permissionedQuery('inv.material_category:read')({args:{profile:v.union(v.literal('default'),v.literal('treeChildren'),v.literal('search')),numItems:v.number(),cursor:v.optional(v.union(v.string(),v.null())),search:v.optional(v.string()),parentId:v.optional(v.union(v.id('materialCategories'),v.null()))},returns:v.any(),handler:async(ctx,args)=>{const o=paginationOptions(args);const page=args.profile==='search'?await ctx.db.query('materialCategories').withSearchIndex('search_text',q=>q.search('searchText',requireSearchTerm(args.search))).paginate(o):args.profile==='treeChildren'?await ctx.db.query('materialCategories').withIndex('by_parent_code_key',q=>q.eq('parentId',args.parentId??null)).paginate(o):await ctx.db.query('materialCategories').withIndex('by_code_key').paginate(o);return resourcePage({...page,page:page.page.map(categoryPresent)})}})
export const createCategory=permissionedMutation('inv.material_category:create')({args:{code:v.string(),name:v.string(),isLeaf:v.optional(v.boolean()),active:v.optional(v.boolean()),parentId:v.optional(v.union(v.id('materialCategories'),v.null()))},returns:v.any(),handler:async(ctx,args)=>{const code=args.code.trim(),name=args.name.trim(),codeKey=code.toLocaleLowerCase();if(!code||!name)throw synieError('validation','物料分类参数不合法');if(await ctx.db.query('materialCategories').withIndex('by_code_key',q=>q.eq('codeKey',codeKey)).unique())throw synieError('conflict','分类编号已存在');await categoryParent(ctx,null,args.parentId??null);const now=Date.now(),id=await ctx.db.insert('materialCategories',{code,codeKey,name,isLeaf:args.isLeaf??true,active:args.active??true,parentId:args.parentId??null,searchText:`${code} ${name}`.toLocaleLowerCase(),insertedAt:now,updatedAt:now});const row=(await ctx.db.get(id))!;await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource:'invMaterialCategories',recordId:id,recordLabel:name,action:'create',changes:categoryPresent(row)});return categoryPresent(row)}})
export const updateCategory=permissionedMutation('inv.material_category:update')({args:{id:v.id('materialCategories'),code:v.optional(v.string()),name:v.optional(v.string()),isLeaf:v.optional(v.boolean()),active:v.optional(v.boolean()),parentId:v.optional(v.union(v.id('materialCategories'),v.null()))},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row)throw synieError('not_found','物料分类不存在');const code=args.code?.trim()??row.code,name=args.name?.trim()??row.name,codeKey=code.toLocaleLowerCase(),parentId=args.parentId===undefined?row.parentId:args.parentId,isLeaf=args.isLeaf??row.isLeaf;if(codeKey!==row.codeKey&&await ctx.db.query('materialCategories').withIndex('by_code_key',q=>q.eq('codeKey',codeKey)).unique())throw synieError('conflict','分类编号已存在');await categoryParent(ctx,row._id,parentId);if(isLeaf&&!row.isLeaf&&await ctx.db.query('materialCategories').withIndex('by_parent_code_key',q=>q.eq('parentId',row._id)).first())throw synieError('validation','存在下级分类,不能改为叶子分类');if(!isLeaf&&row.isLeaf&&await ctx.db.query('materials').withIndex('by_category',q=>q.eq('categoryId',row._id)).first())throw synieError('validation','分类下存在物料,不能改为非叶子分类');await ctx.db.patch(row._id,{code,codeKey,name,isLeaf,active:args.active??row.active,parentId,searchText:`${code} ${name}`.toLocaleLowerCase(),updatedAt:Date.now()});return categoryPresent((await ctx.db.get(row._id))!)}})
export const removeCategory=permissionedMutation('inv.material_category:delete')({args:{id:v.id('materialCategories')},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row)throw synieError('not_found','物料分类不存在');const [child,material]=await Promise.all([ctx.db.query('materialCategories').withIndex('by_parent_code_key',q=>q.eq('parentId',row._id)).first(),ctx.db.query('materials').withIndex('by_category',q=>q.eq('categoryId',row._id)).first()]);if(child)throw synieError('conflict','存在下级分类,不能删除');if(material)throw synieError('conflict','分类下存在物料,不能删除');await ctx.db.delete(row._id);await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource:'invMaterialCategories',recordId:row._id,recordLabel:row.name,action:'destroy',changes:categoryPresent(row)});return null}})

function materialPresent(row:Doc<'materials'>){return{id:row._id,code:row.code,name:row.name,spec:row.spec,customerPartNo:row.customerPartNo,isCustomerMaterial:row.isCustomerMaterial,active:row.active,categoryId:row.categoryId,defaultUnitId:row.defaultUnitId,customerId:row.customerId,insertedAt:row.insertedAt,updatedAt:row.updatedAt}}
async function materialRelations(ctx:{db:any},args:{categoryId:Id<'materialCategories'>,defaultUnitId:Id<'units'>,customerId:Id<'customers'>|null,isCustomerMaterial:boolean}){const [category,unit,customer]=await Promise.all([ctx.db.get(args.categoryId),ctx.db.get(args.defaultUnitId),args.customerId?ctx.db.get(args.customerId):null]);if(!category?.active||!category.isLeaf)throw synieError('validation','物料分类不存在、停用或不是叶子分类');if(!unit)throw synieError('validation','默认单位不存在');if(args.isCustomerMaterial!==Boolean(customer))throw synieError('validation','客户物料标记与客户必须同时填写')}
export const getMaterial=permissionedQuery('inv.material:read')({args:{id:v.id('materials')},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);return row?materialPresent(row):null}})
export const listMaterials=permissionedQuery('inv.material:read')({args:{profile:v.union(v.literal('default'),v.literal('search')),numItems:v.number(),cursor:v.optional(v.union(v.string(),v.null())),search:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>{const o=paginationOptions(args);const page=args.profile==='search'?await ctx.db.query('materials').withSearchIndex('search_text',q=>q.search('searchText',requireSearchTerm(args.search))).paginate(o):await ctx.db.query('materials').withIndex('by_code_key').paginate(o);return resourcePage({...page,page:page.page.map(materialPresent)})}})
export const createMaterial=permissionedMutation('inv.material:create')({args:{code:v.optional(v.string()),name:v.string(),spec:v.optional(v.union(v.string(),v.null())),customerPartNo:v.optional(v.union(v.string(),v.null())),isCustomerMaterial:v.optional(v.boolean()),active:v.optional(v.boolean()),categoryId:v.id('materialCategories'),defaultUnitId:v.id('units'),customerId:v.optional(v.union(v.id('customers'),v.null()))},returns:v.any(),handler:async(ctx,args)=>{const name=args.name.trim(),isCustomerMaterial=args.isCustomerMaterial??false,customerId=args.customerId??null;await materialRelations(ctx,{categoryId:args.categoryId,defaultUnitId:args.defaultUnitId,customerId,isCustomerMaterial});const code=args.code?.trim()||await nextInMutation(asDomainMutationCtx(ctx),'inv.material',{category_id:args.categoryId,customer_id:customerId}),codeKey=code.toLocaleLowerCase();if(!code||!name)throw synieError('validation','物料参数不合法');if(await ctx.db.query('materials').withIndex('by_code_key',q=>q.eq('codeKey',codeKey)).unique())throw synieError('conflict','物料编号已存在');const now=Date.now(),id=await ctx.db.insert('materials',{code,codeKey,name,spec:args.spec?.trim()||null,customerPartNo:args.customerPartNo?.trim()||null,isCustomerMaterial,active:args.active??true,categoryId:args.categoryId,defaultUnitId:args.defaultUnitId,customerId,searchText:`${code} ${name} ${args.spec??''}`.toLocaleLowerCase(),insertedAt:now,updatedAt:now});const row=(await ctx.db.get(id))!;await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource:'invMaterials',recordId:id,recordLabel:name,action:'create',changes:materialPresent(row)});return materialPresent(row)}})
export const updateMaterial=permissionedMutation('inv.material:update')({args:{id:v.id('materials'),name:v.optional(v.string()),spec:v.optional(v.union(v.string(),v.null())),customerPartNo:v.optional(v.union(v.string(),v.null())),isCustomerMaterial:v.optional(v.boolean()),active:v.optional(v.boolean()),categoryId:v.optional(v.id('materialCategories')),defaultUnitId:v.optional(v.id('units')),customerId:v.optional(v.union(v.id('customers'),v.null()))},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row)throw synieError('not_found','物料不存在');const draft={categoryId:args.categoryId??row.categoryId,defaultUnitId:args.defaultUnitId??row.defaultUnitId,customerId:args.customerId===undefined?row.customerId:args.customerId,isCustomerMaterial:args.isCustomerMaterial??row.isCustomerMaterial};await materialRelations(ctx,draft);if(draft.defaultUnitId!==row.defaultUnitId){const [conversion,fact]=await Promise.all([ctx.db.query('materialUnits').withIndex('by_material_unit',q=>q.eq('materialId',row._id)).first(),ctx.db.query('stockEntries').withIndex('by_material',q=>q.eq('materialId',row._id)).first()]);if(conversion||fact)throw synieError('validation','物料已有转换或库存分录,默认单位不可修改')}const name=args.name?.trim()??row.name;if(!name)throw synieError('validation','物料参数不合法');await ctx.db.patch(row._id,{name,spec:args.spec===undefined?row.spec:args.spec?.trim()||null,customerPartNo:args.customerPartNo===undefined?row.customerPartNo:args.customerPartNo?.trim()||null,...draft,active:args.active??row.active,searchText:`${row.code} ${name} ${args.spec??row.spec??''}`.toLocaleLowerCase(),updatedAt:Date.now()});return materialPresent((await ctx.db.get(row._id))!)}})
export const removeMaterial=permissionedMutation('inv.material:delete')({args:{id:v.id('materials')},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row)throw synieError('not_found','物料不存在');const [unit,fact,ref]=await Promise.all([ctx.db.query('materialUnits').withIndex('by_material_unit',q=>q.eq('materialId',row._id)).first(),ctx.db.query('stockEntries').withIndex('by_material',q=>q.eq('materialId',row._id)).first(),ctx.db.query('domainReferences').withIndex('by_target',q=>q.eq('targetResource','invMaterials').eq('targetRecordId',row._id)).first()]);if(unit||fact||ref)throw synieError('conflict','物料已被业务数据引用,不可删除');await ctx.db.delete(row._id);await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource:'invMaterials',recordId:row._id,recordLabel:row.name,action:'destroy',changes:materialPresent(row)});return null}})

function unitPresent(row:Doc<'materialUnits'>){return{id:row._id,factor:scaledInt64ToDecimal(row.factorScaled,6),materialId:row.materialId,unitId:row.unitId,insertedAt:row.insertedAt,updatedAt:row.updatedAt}}
export const listMaterialUnits=permissionedQuery('inv.material:read')({args:{numItems:v.number(),cursor:v.optional(v.union(v.string(),v.null())),materialId:v.id('materials')},returns:v.any(),handler:async(ctx,args)=>{const page=await ctx.db.query('materialUnits').withIndex('by_material_unit',q=>q.eq('materialId',args.materialId)).paginate(paginationOptions(args));return resourcePage({...page,page:page.page.map(unitPresent)})}})
export const createMaterialUnit=permissionedMutation('inv.material:update')({args:{materialId:v.id('materials'),unitId:v.id('units'),factor:v.string()},returns:v.any(),handler:async(ctx,args)=>{const [material,unit]=await Promise.all([ctx.db.get(args.materialId),ctx.db.get(args.unitId)]);if(!material||!unit||material.defaultUnitId===unit._id)throw synieError('validation','物料单位转换参数不合法');if(await ctx.db.query('materialUnits').withIndex('by_material_unit',q=>q.eq('materialId',args.materialId).eq('unitId',args.unitId)).unique())throw synieError('conflict','同一物料同一单位只能有一行转换');const factorScaled=decimalToScaledInt64(args.factor,6);if(factorScaled<=0n)throw synieError('validation','转换因子必须大于零');const now=Date.now(),id=await ctx.db.insert('materialUnits',{materialId:args.materialId,unitId:args.unitId,factorScaled,insertedAt:now,updatedAt:now});return unitPresent((await ctx.db.get(id))!)}})
export const getMaterialUnit=permissionedQuery('inv.material:read')({args:{id:v.id('materialUnits')},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);return row?unitPresent(row):null}})
export const updateMaterialUnit=permissionedMutation('inv.material:update')({args:{id:v.id('materialUnits'),unitId:v.optional(v.id('units')),factor:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row)throw synieError('not_found','物料单位转换不存在');const unitId=args.unitId??row.unitId,factorScaled=args.factor===undefined?row.factorScaled:decimalToScaledInt64(args.factor,6);const material=await ctx.db.get(row.materialId);if(!material||material.defaultUnitId===unitId||factorScaled<=0n)throw synieError('validation','物料单位转换参数不合法');const duplicate=await ctx.db.query('materialUnits').withIndex('by_material_unit',q=>q.eq('materialId',row.materialId).eq('unitId',unitId)).unique();if(duplicate&&duplicate._id!==row._id)throw synieError('conflict','同一物料同一单位只能有一行转换');await ctx.db.patch(row._id,{unitId,factorScaled,updatedAt:Date.now()});return unitPresent((await ctx.db.get(row._id))!)}})
export const removeMaterialUnit=permissionedMutation('inv.material:delete')({args:{id:v.id('materialUnits')},returns:v.null(),handler:async(ctx,args)=>{if(!(await ctx.db.get(args.id)))throw synieError('not_found','物料单位转换不存在');await ctx.db.delete(args.id);return null}})
