import { v } from 'convex/values'
import type { Doc } from '../../_generated/dataModel'
import { permissionedMutation, permissionedQuery } from '../../lib/auth'
import { asDomainMutationCtx } from '../../lib/mutationContext'
import { synieError, validationError } from '../../lib/errors'
import { decimalToScaledInt64, scaledInt64ToDecimal } from '../../lib/decimal'
import { paginationOptions, requireSearchTerm, resourcePage } from '../../lib/pagination'
import { changedFields } from '../../platform/audit/model'
import { writeAudit } from '../../platform/audit/write'
import { nextInMutation } from '../../platform/numbering/service'

type PartyTable = 'customers' | 'suppliers'
type PartyDoc = Doc<'customers'> | Doc<'suppliers'>
function normalize(input: { code: string; name: string; shortName?: string | null }) {
  const code = input.code.trim(); const name = input.name.trim(); const shortName = input.shortName?.trim() || null
  if (!code || code.length > 32 || !name || name.length > 128 || (shortName?.length ?? 0) > 64) throw synieError('validation', '客商参数不合法')
  return { code, codeKey: code.toLocaleLowerCase(), name, shortName, searchText: `${code} ${name} ${shortName ?? ''}`.toLocaleLowerCase() }
}
function present(row: PartyDoc) { return { id: row._id, code: row.code, name: row.name, shortName: row.shortName, insertedAt: row.insertedAt, updatedAt: row.updatedAt } }
function api(table: PartyTable, prefix: 'sales.customer' | 'purchase.supplier', resource: 'salCustomers' | 'purSuppliers', label: string) {
  const get = permissionedQuery(`${prefix}:read`)({ args:{id:v.string()},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id as never) as PartyDoc|null;return row?present(row):null} })
  const list = permissionedQuery(`${prefix}:read`)({args:{profile:v.union(v.literal('default'),v.literal('search')),numItems:v.number(),cursor:v.optional(v.union(v.string(),v.null())),search:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>{const options=paginationOptions(args);const db=ctx.db as any;const page=args.profile==='search'?await db.query(table).withSearchIndex('search_text',(q:any)=>q.search('searchText',requireSearchTerm(args.search))).paginate(options):await db.query(table).withIndex('by_code_key').paginate(options);return resourcePage({...page,page:page.page.map(present)})}})
  const create = permissionedMutation(`${prefix}:create`)({args:{code:v.string(),name:v.string(),shortName:v.optional(v.union(v.string(),v.null()))},returns:v.any(),handler:async(ctx,args)=>{const n=normalize(args);const db=ctx.db as any;if(await db.query(table).withIndex('by_code_key',(q:any)=>q.eq('codeKey',n.codeKey)).unique())throw synieError('conflict',`${label}编号已存在`);const now=Date.now();const id=await db.insert(table,{...n,insertedAt:now,updatedAt:now});const row=await db.get(id) as PartyDoc;await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource,recordId:id,recordLabel:row.name,action:'create',changes:present(row)});return present(row)}})
  const update = permissionedMutation(`${prefix}:update`)({args:{id:v.string(),code:v.optional(v.string()),name:v.optional(v.string()),shortName:v.optional(v.union(v.string(),v.null()))},returns:v.any(),handler:async(ctx,args)=>{const db=ctx.db as any;const row=await db.get(args.id) as PartyDoc|null;if(!row)throw synieError('not_found',`${label}不存在`);const before=present(row);const n=normalize({code:args.code??row.code,name:args.name??row.name,shortName:args.shortName===undefined?row.shortName:args.shortName});if(n.codeKey!==row.codeKey&&await db.query(table).withIndex('by_code_key',(q:any)=>q.eq('codeKey',n.codeKey)).unique())throw synieError('conflict',`${label}编号已存在`);await db.patch(row._id,{...n,updatedAt:Date.now()});const after=present(await db.get(row._id));const changes=changedFields(before,after);if(Object.keys(changes).length)await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource,recordId:row._id,recordLabel:after.name,action:'update',changes});return after}})
  const remove = permissionedMutation(`${prefix}:delete`)({args:{id:v.string()},returns:v.null(),handler:async(ctx,args)=>{const db=ctx.db as any;const row=await db.get(args.id) as PartyDoc|null;if(!row)throw synieError('not_found',`${label}不存在`);if(table==='customers'&&await ctx.db.query('materials').withIndex('by_customer',(q)=>q.eq('customerId',row._id as never)).first())throw synieError('conflict','存在关联物料,不能删除');const reference=await ctx.db.query('domainReferences').withIndex('by_target',(q)=>q.eq('targetResource',resource).eq('targetRecordId',row._id)).first();if(reference)throw synieError('conflict',`${label}已被业务数据引用,不可删除`);await db.delete(row._id);await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource,recordId:row._id,recordLabel:row.name,action:'destroy',changes:present(row)});return null}})
  return {get,list,create,update,remove}
}
const customer = api('customers','sales.customer','salCustomers','客户')
const supplier = api('suppliers','purchase.supplier','purSuppliers','供应商')
export const getCustomer=customer.get;export const listCustomers=customer.list;export const createCustomer=customer.create;export const updateCustomer=customer.update;export const removeCustomer=customer.remove
export const getSupplier=supplier.get;export const listSuppliers=supplier.list;export const createSupplier=supplier.create;export const updateSupplier=supplier.update;export const removeSupplier=supplier.remove

function employeePresent(row: Doc<'employees'>) { return { id:row._id,code:row.code,name:row.name,attendanceNo:row.attendanceNo,idNumber:row.idNumber,householdRegistration:row.householdRegistration,phone:row.phone,currentAddress:row.currentAddress,dailyWage:row.dailyWage===null?null:scaledInt64ToDecimal(row.dailyWage,2),monthlyAllowance:row.monthlyAllowance===null?null:scaledInt64ToDecimal(row.monthlyAllowance,2),insuranceTypes:row.insuranceTypes,insertedAt:row.insertedAt,updatedAt:row.updatedAt } }
function optionalText(value:string|null|undefined,max:number){const text=value?.trim()||null;if(text&&text.length>max)throw synieError('validation','员工参数不合法');return text}
function money(value:string|null|undefined){if(value==null||value==='')return null;let scaled:bigint;try{scaled=decimalToScaledInt64(value,2)}catch{throw validationError('员工参数不合法',{amount:['必须是非负十进制字符串']})}if(scaled<0n)throw synieError('validation','员工参数不合法');return scaled}
export const getEmployee=permissionedQuery('hr.employee:read')({args:{id:v.id('employees')},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);return row?employeePresent(row):null}})
export const listEmployees=permissionedQuery('hr.employee:read')({args:{profile:v.union(v.literal('default'),v.literal('search')),numItems:v.number(),cursor:v.optional(v.union(v.string(),v.null())),search:v.optional(v.string())},returns:v.any(),handler:async(ctx,args)=>{const o=paginationOptions(args);const page=args.profile==='search'?await ctx.db.query('employees').withSearchIndex('search_text',q=>q.search('searchText',requireSearchTerm(args.search))).paginate(o):await ctx.db.query('employees').withIndex('by_code_key').paginate(o);return resourcePage({...page,page:page.page.map(employeePresent)})}})
export const createEmployee=permissionedMutation('hr.employee:create')({args:{code:v.optional(v.string()),name:v.string(),attendanceNo:v.optional(v.union(v.string(),v.null())),idNumber:v.optional(v.union(v.string(),v.null())),householdRegistration:v.optional(v.union(v.string(),v.null())),phone:v.optional(v.union(v.string(),v.null())),currentAddress:v.optional(v.union(v.string(),v.null())),dailyWage:v.optional(v.union(v.string(),v.null())),monthlyAllowance:v.optional(v.union(v.string(),v.null())),insuranceTypes:v.optional(v.array(v.string()))},returns:v.any(),handler:async(ctx,args)=>{const code=args.code?.trim()||await nextInMutation(asDomainMutationCtx(ctx),'hr.employee',{}),name=args.name.trim();if(!code||!name)throw synieError('validation','员工参数不合法');const codeKey=code.toLocaleLowerCase();if(await ctx.db.query('employees').withIndex('by_code_key',q=>q.eq('codeKey',codeKey)).unique())throw synieError('conflict','员工编号已存在');const attendanceNo=optionalText(args.attendanceNo,64);if(attendanceNo&&await ctx.db.query('employees').withIndex('by_attendance_no',q=>q.eq('attendanceNo',attendanceNo)).unique())throw synieError('conflict','考勤编号已存在');const now=Date.now();const id=await ctx.db.insert('employees',{code,codeKey,name,attendanceNo,idNumber:optionalText(args.idNumber,64),householdRegistration:optionalText(args.householdRegistration,128),phone:optionalText(args.phone,32),currentAddress:optionalText(args.currentAddress,256),dailyWage:money(args.dailyWage),monthlyAllowance:money(args.monthlyAllowance),insuranceTypes:[...new Set(args.insuranceTypes??[])],searchText:`${code} ${name} ${attendanceNo??''}`.toLocaleLowerCase(),insertedAt:now,updatedAt:now});const row=(await ctx.db.get(id))!;await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource:'hrEmployees',recordId:id,recordLabel:name,action:'create',changes:employeePresent(row)});return employeePresent(row)}})
export const updateEmployee=permissionedMutation('hr.employee:update')({args:{id:v.id('employees'),name:v.optional(v.string()),attendanceNo:v.optional(v.union(v.string(),v.null())),idNumber:v.optional(v.union(v.string(),v.null())),householdRegistration:v.optional(v.union(v.string(),v.null())),phone:v.optional(v.union(v.string(),v.null())),currentAddress:v.optional(v.union(v.string(),v.null())),dailyWage:v.optional(v.union(v.string(),v.null())),monthlyAllowance:v.optional(v.union(v.string(),v.null())),insuranceTypes:v.optional(v.array(v.string()))},returns:v.any(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row)throw synieError('not_found','员工不存在');const attendanceNo=args.attendanceNo===undefined?row.attendanceNo:optionalText(args.attendanceNo,64);if(attendanceNo!==row.attendanceNo&&attendanceNo&&await ctx.db.query('employees').withIndex('by_attendance_no',q=>q.eq('attendanceNo',attendanceNo)).unique())throw synieError('conflict','考勤编号已存在');const name=args.name?.trim()??row.name;if(!name)throw synieError('validation','员工参数不合法');await ctx.db.patch(row._id,{name,attendanceNo,idNumber:args.idNumber===undefined?row.idNumber:optionalText(args.idNumber,64),householdRegistration:args.householdRegistration===undefined?row.householdRegistration:optionalText(args.householdRegistration,128),phone:args.phone===undefined?row.phone:optionalText(args.phone,32),currentAddress:args.currentAddress===undefined?row.currentAddress:optionalText(args.currentAddress,256),dailyWage:args.dailyWage===undefined?row.dailyWage:money(args.dailyWage),monthlyAllowance:args.monthlyAllowance===undefined?row.monthlyAllowance:money(args.monthlyAllowance),insuranceTypes:args.insuranceTypes===undefined?row.insuranceTypes:[...new Set(args.insuranceTypes)],searchText:`${row.code} ${name} ${attendanceNo??''}`.toLocaleLowerCase(),updatedAt:Date.now()});return employeePresent((await ctx.db.get(row._id))!)}})
export const removeEmployee=permissionedMutation('hr.employee:delete')({args:{id:v.id('employees')},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row)throw synieError('not_found','员工不存在');const ref=await ctx.db.query('domainReferences').withIndex('by_target',q=>q.eq('targetResource','hrEmployees').eq('targetRecordId',row._id)).first();if(ref)throw synieError('conflict','员工已被业务数据引用,不可删除');await ctx.db.delete(row._id);await writeAudit(asDomainMutationCtx(ctx),ctx.actor,{resource:'hrEmployees',recordId:row._id,recordLabel:row.name,action:'destroy',changes:employeePresent(row)});return null}})
