import type { ResourceMeta } from '../meta/types.ts'

export const RULE_RESOURCE_NAME = 'sysNumberingRules'
export const COUNTER_RESOURCE_NAME = 'sysNumberingCounters'

export function ruleResourceMeta(): ResourceMeta {
  return {
    name: RULE_RESOURCE_NAME,
    permissionPrefix: 'sys.numbering_rule',
    permissionLabel: '编号规则',
    table: 'sys_numbering_rule',
    print: true,
    printHead: true,
    audit: { enabled: true },
    fields: [
      { name: 'id', apiName: 'id', dbColumn: 'id', type: 'uuid', label: 'id', readonly: true, sortable: true },
      {
        name: 'resource',
        apiName: 'resource',
        dbColumn: 'resource',
        type: 'string',
        label: '绑定资源',
        required: true,
        createOnly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'name',
        apiName: 'name',
        dbColumn: 'name',
        type: 'string',
        label: '规则名称',
        required: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'segments',
        apiName: 'segments',
        dbColumn: 'segments',
        type: 'string',
        label: '编号段',
        required: true,
      },
      {
        name: 'per_company',
        apiName: 'perCompany',
        dbColumn: 'per_company',
        type: 'boolean',
        label: '按公司计数',
        required: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'enabled',
        apiName: 'enabled',
        dbColumn: 'enabled',
        type: 'boolean',
        label: '启用',
        required: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'inserted_at',
        apiName: 'insertedAt',
        dbColumn: 'inserted_at',
        type: 'datetime',
        label: '创建时间',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'updated_at',
        apiName: 'updatedAt',
        dbColumn: 'updated_at',
        type: 'datetime',
        label: '更新时间',
        readonly: true,
        filterable: true,
        sortable: true,
      },
    ],
    actions: [
      { key: 'read', label: '查看', scope: 'both' },
      { key: 'create', label: '新增', scope: 'both' },
      { key: 'update', label: '编辑', scope: 'row' },
      { key: 'delete', label: '删除', scope: 'row', isDanger: true },
    ],
    form: {
      exclude: ['id', 'insertedAt', 'updatedAt'],
      fields: {
        name: { placeholder: '如 记账凭证编号' },
        perCompany: { initial: true, span: 6 },
        enabled: { initial: true },
      },
    },

  }
}

export function counterResourceMeta(): ResourceMeta {
  return {
    name: COUNTER_RESOURCE_NAME,
    permissionPrefix: 'sys.numbering_rule',
    permissionLabel: '编号规则',
    table: 'sys_numbering_counter',
    audit: { enabled: true },
    fields: [
      { name: 'id', apiName: 'id', dbColumn: 'id', type: 'uuid', label: 'id', readonly: true, sortable: true },
      {
        name: 'scope_key',
        apiName: 'scopeKey',
        dbColumn: 'scope_key',
        type: 'string',
        label: '计数范围',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'value',
        apiName: 'value',
        dbColumn: 'value',
        type: 'integer',
        label: '当前序号',
        required: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'inserted_at',
        apiName: 'insertedAt',
        dbColumn: 'inserted_at',
        type: 'datetime',
        label: '创建时间',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'updated_at',
        apiName: 'updatedAt',
        dbColumn: 'updated_at',
        type: 'datetime',
        label: '更新时间',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'rule_id',
        apiName: 'ruleId',
        dbColumn: 'rule_id',
        type: 'uuid',
        label: '编号规则',
        required: true,
        readonly: true,
        filterable: true,
        ref: { resource: RULE_RESOURCE_NAME, relation: 'rule', labelField: 'name' },
      },
    ],
    actions: [],
    form: { exclude: ['id', 'ruleId', 'scopeKey', 'insertedAt', 'updatedAt'] },
  }
}
