import type { ResourceMeta } from '../meta/types.ts'

export const AUDIT_LOG_RESOURCE_NAME = 'sysAuditLogs'

export function auditLogResourceMeta(): ResourceMeta {
  return {
    name: AUDIT_LOG_RESOURCE_NAME,
    classification: { presentation: 'none', interactive: false, note: '只读审计' },
    permissionPrefix: 'sys.audit_log',
    permissionLabel: '审计日志',
    table: 'sys_audit_log',
    audit: { enabled: false },
    fields: [
      { name: 'id', apiName: 'id', dbColumn: 'id', type: 'uuid', label: 'id', readonly: true, sortable: true },
      {
        name: 'resource',
        apiName: 'resource',
        dbColumn: 'resource',
        type: 'string',
        label: '资源',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'record_id',
        apiName: 'recordId',
        dbColumn: 'record_id',
        type: 'uuid',
        label: '记录',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'record_label',
        apiName: 'recordLabel',
        dbColumn: 'record_label',
        type: 'string',
        label: '记录摘要',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'action_type',
        apiName: 'actionType',
        dbColumn: 'action_type',
        type: 'string',
        label: '动作类型',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'action_name',
        apiName: 'actionName',
        dbColumn: 'action_name',
        type: 'string',
        label: '动作名',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'actor_id',
        apiName: 'actorId',
        dbColumn: 'actor_id',
        type: 'uuid',
        label: '操作人',
        readonly: true,
        filterable: true,
      },
      {
        name: 'actor_name',
        apiName: 'actorName',
        dbColumn: 'actor_name',
        type: 'string',
        label: '操作人用户名',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'company_id',
        apiName: 'companyId',
        dbColumn: 'company_id',
        type: 'uuid',
        label: '公司',
        readonly: true,
        filterable: true,
      },
      {
        name: 'changes',
        apiName: 'changes',
        dbColumn: 'changes',
        type: 'json',
        label: '变更',
        readonly: true,
      },
      {
        name: 'inserted_at',
        apiName: 'insertedAt',
        dbColumn: 'inserted_at',
        type: 'datetime',
        label: '时间',
        readonly: true,
        filterable: true,
        sortable: true,
      },
    ],
    actions: [{ key: 'read', label: '查看', scope: 'both' }],
  }
}
