// 权限矩阵中文标签;漏码原样显示英文(同 logs.tsx 模式),新域/新资源/新动作接入时在此补
export const DOMAIN_LABELS: Record<string, string> = {
  sys: '系统',
  base: '基础资料',
  sales: '销售',
  purchase: '采购',
  acc: '财务',
  hr: '人事',
  inv: '库存',
}

export const RESOURCE_LABELS: Record<string, string> = {
  'sys.user': '用户',
  'sys.role': '角色',
  'sys.role_permission': '角色权限',
  'sys.audit_log': '操作日志',
  'sys.numbering_rule': '编号规则',
  'sys.setting': '系统设置',
  'base.company': '公司',
  'base.unit': '计量单位',
  'base.currency': '币种',
  'base.account': '会计科目',
  'base.market_instrument': '行情品种',
  'base.market_price': '行情价点',
  'sales.customer': '客户',
  'sales.order': '销售订单',
  'sales.quotation': '销售报价单',
  'sales.setting': '销售设置',
  'purchase.supplier': '供应商',
  'hr.employee': '员工',
  'hr.attendance_punch': '打卡记录',
  'hr.attendance_day': '日考勤',
  'hr.attendance_correction': '补卡单',
  'hr.payroll': '工资单',
  'hr.payroll_payment': '工资发放',
  'hr.employee_loan': '员工借款',
  'inv.material_category': '物料分类',
  'inv.material': '物料',
  'inv.warehouse': '仓库',
  'sys.file': '附件',
  'sys.storage': '存储接入',
  'acc.gl_entry': '总账分录',
  'acc.gl_journal': '会计凭证',
  'acc.bank_account': '银行账户',
  'acc.bank_transaction': '银行流水',
  'acc.bank_import_template': '流水导入模板',
  'acc.vat_invoice': '增值税发票',
  'acc.bill': '承兑票据',
  'acc.bill_transaction': '承兑交易',
  'acc.bill_holding': '持有承兑',
  'acc.setting': '财务设置',
}

export const ACTION_LABELS: Record<string, string> = {
  create: '新增',
  read: '查看',
  update: '编辑',
  delete: '删除',
  print: '打印',
  import: '导入',
  export: '导出',
  batch_delete: '批量删除',
  batch_update: '批量更新',
  batch_print: '批量打印',
  audit: '审核',
  cancel: '取消',
  void: '作废',
  close: '关闭',
  reverse: '红冲',
  reconcile: '对账',
  recalc: '重算',
}

export const domainLabel = (d: string) => DOMAIN_LABELS[d] ?? d
export const resourceLabel = (p: string) => RESOURCE_LABELS[p] ?? p
export const actionLabel = (a: string) => ACTION_LABELS[a] ?? a
