/* Generated by scripts/generate-convex-web-manifest.ts; do not edit. */
export const CONVEX_DOMAIN_MANIFEST = {
  "basMarketInstruments": {
    "gateway": "market",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "basMarketPricePoints": {
    "gateway": "market",
    "capabilities": [
      "create",
      "void"
    ],
    "commands": [
      "void"
    ],
    "commandTargets": {
      "void": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "hrAttendancePunches": {
    "gateway": "hr",
    "capabilities": [
      "import"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [
      "punchedAt"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "hrAttendanceImports": {
    "gateway": "hr",
    "capabilities": [
      "import"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [
      "insertedAt"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "hrAttendanceDays": {
    "gateway": "hr",
    "capabilities": [
      "recalc"
    ],
    "commands": [
      "recalc"
    ],
    "commandTargets": {
      "recalc": "collection"
    },
    "parentField": null,
    "sortFields": [
      "date"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "hrAttendanceCorrections": {
    "gateway": "hr",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [
      "insertedAt"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "hrPayrolls": {
    "gateway": "hr",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [
      "month"
    ],
    "aggregate": false,
    "draftGateway": null
  },
  "hrPayrollPayments": {
    "gateway": "hr",
    "capabilities": [
      "create",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": "payrollId",
    "sortFields": [
      "paidOn"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "hrEmployeeLoans": {
    "gateway": "hr",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [
      "occurredOn"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "invStockEntries": {
    "gateway": "inventory",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [
      "postingDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "invStockDocs": {
    "gateway": "inventory",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "docDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "inventory"
  },
  "invStockDocItems": {
    "gateway": "inventory",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "stockDocId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "invStockTransfers": {
    "gateway": "inventory",
    "capabilities": [
      "create",
      "update",
      "delete",
      "ship",
      "receive"
    ],
    "commands": [
      "ship",
      "receive"
    ],
    "commandTargets": {
      "ship": "row",
      "receive": "row"
    },
    "parentField": null,
    "sortFields": [
      "docDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "inventory"
  },
  "invStockTransferItems": {
    "gateway": "inventory",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "stockTransferId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "invStockCounts": {
    "gateway": "inventory",
    "capabilities": [
      "create",
      "update",
      "delete",
      "approve",
      "cancel"
    ],
    "commands": [
      "approve",
      "cancel"
    ],
    "commandTargets": {
      "approve": "row",
      "cancel": "row"
    },
    "parentField": null,
    "sortFields": [
      "postingDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "inventory"
  },
  "invStockCountItems": {
    "gateway": "inventory",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "countId",
    "sortFields": [
      "insertedAt"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accGlJournals": {
    "gateway": "accounting",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "cancel"
    ],
    "commands": [
      "audit",
      "cancel"
    ],
    "commandTargets": {
      "audit": "row",
      "cancel": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "accounting"
  },
  "accGlJournalLines": {
    "gateway": "accounting",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "journalId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accGlEntries": {
    "gateway": "accounting",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [
      "postingDate",
      "seq"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "salQuotations": {
    "gateway": "quotations",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "trading"
  },
  "salQuotationItems": {
    "gateway": "quotations",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "quotationId",
    "sortFields": [
      "idx",
      "quotationDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "salQuotationTiers": {
    "gateway": "quotations",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "itemId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "salOrders": {
    "gateway": "orders",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "close",
      "void",
      "print",
      "export",
      "batch_print"
    ],
    "commands": [
      "audit",
      "close",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "close": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "trading"
  },
  "salOrderItems": {
    "gateway": "orders",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "orderId",
    "sortFields": [
      "idx",
      "orderDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "salDeliveries": {
    "gateway": "fulfillment",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void",
      "print",
      "export",
      "batch_print"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "deliveryDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "trading"
  },
  "salDeliveryItems": {
    "gateway": "fulfillment",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "deliveryId",
    "sortFields": [
      "idx",
      "deliveryDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "salReconciliations": {
    "gateway": "reconciliation",
    "capabilities": [
      "create",
      "update",
      "delete",
      "confirm",
      "unconfirm",
      "audit",
      "void"
    ],
    "commands": [
      "confirm",
      "unconfirm",
      "audit",
      "void"
    ],
    "commandTargets": {
      "confirm": "row",
      "unconfirm": "row",
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "reconciliationNo"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "reconciliation"
  },
  "salReconciliationItems": {
    "gateway": "reconciliation",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "reconciliationId",
    "sortFields": [
      "idx",
      "deliveryDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purQuotations": {
    "gateway": "quotations",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "trading"
  },
  "purQuotationItems": {
    "gateway": "quotations",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "quotationId",
    "sortFields": [
      "idx",
      "quotationDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purQuotationTiers": {
    "gateway": "quotations",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "itemId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purOrders": {
    "gateway": "orders",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "close",
      "void"
    ],
    "commands": [
      "audit",
      "close",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "close": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "trading"
  },
  "purOrderItems": {
    "gateway": "orders",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "orderId",
    "sortFields": [
      "idx",
      "orderDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purReceipts": {
    "gateway": "fulfillment",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "receiptDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "trading"
  },
  "purReceiptItems": {
    "gateway": "fulfillment",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "receiptId",
    "sortFields": [
      "idx",
      "receiptDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purReconciliations": {
    "gateway": "reconciliation",
    "capabilities": [
      "create",
      "update",
      "delete",
      "confirm",
      "unconfirm",
      "audit",
      "void"
    ],
    "commands": [
      "confirm",
      "unconfirm",
      "audit",
      "void"
    ],
    "commandTargets": {
      "confirm": "row",
      "unconfirm": "row",
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "reconciliationNo"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "reconciliation"
  },
  "purReconciliationItems": {
    "gateway": "reconciliation",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "reconciliationId",
    "sortFields": [
      "idx",
      "receiptDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "salDeliveryPackBoxes": {
    "gateway": "fulfillment",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "deliveryId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "salDeliveryPackLines": {
    "gateway": "fulfillment",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "packBoxId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purOrderItemMaterials": {
    "gateway": "orders",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "orderItemId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purOrderItemByproducts": {
    "gateway": "orders",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "orderItemId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purOutsourcedIssues": {
    "gateway": "fulfillment",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "issueDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "fulfillment"
  },
  "purOutsourcedIssueItems": {
    "gateway": "fulfillment",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "issueId",
    "sortFields": [
      "idx",
      "issueDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purOutsourcedReceipts": {
    "gateway": "fulfillment",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "receiptDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "fulfillment"
  },
  "purOutsourcedReceiptItems": {
    "gateway": "fulfillment",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "receiptId",
    "sortFields": [
      "idx",
      "receiptDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purOutsourcedReceiptItemMaterials": {
    "gateway": "fulfillment",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "receiptItemId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "purOutsourcedReceiptItemByproducts": {
    "gateway": "fulfillment",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "receiptItemId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accVatInvoices": {
    "gateway": "finance",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void",
      "reverse"
    ],
    "commands": [
      "audit",
      "void",
      "reverse"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row",
      "reverse": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accBankAccounts": {
    "gateway": "finance",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accBankTransactions": {
    "gateway": "finance",
    "capabilities": [
      "create",
      "update",
      "delete",
      "import",
      "reconcile"
    ],
    "commands": [
      "reconcile"
    ],
    "commandTargets": {
      "reconcile": "row"
    },
    "parentField": null,
    "sortFields": [
      "occurredAt"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accBankImportTemplates": {
    "gateway": "finance",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accBankImports": {
    "gateway": "finance",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accBankImportItems": {
    "gateway": "finance",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "importId",
    "sortFields": [
      "rowNo"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accBankReconciliations": {
    "gateway": "finance",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "bankTransactionId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accExpenseReports": {
    "gateway": "finance",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "finance"
  },
  "accExpenseReportItems": {
    "gateway": "finance",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "reportId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accBills": {
    "gateway": "finance",
    "capabilities": [
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [
      "billNo"
    ],
    "aggregate": false,
    "draftGateway": null
  },
  "accBillTransactions": {
    "gateway": "finance",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": "billId",
    "sortFields": [
      "occurredOn"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "accBillHoldings": {
    "gateway": "finance",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "billId",
    "sortFields": [
      "dueDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "scmOrderFlowItems": {
    "gateway": "reconciliation",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgOperations": {
    "gateway": "manufacturing",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgProcessTemplates": {
    "gateway": "manufacturing",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [],
    "commandTargets": {},
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "manufacturing"
  },
  "mfgProcessTemplateItems": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "templateId",
    "sortFields": [
      "seq"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgBoms": {
    "gateway": "manufacturing",
    "capabilities": [
      "create",
      "update",
      "delete"
    ],
    "commands": [
      "activate",
      "deactivate"
    ],
    "commandTargets": {
      "activate": "row",
      "deactivate": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [
      "materialId"
    ],
    "aggregate": true,
    "draftGateway": "manufacturing"
  },
  "mfgBomComponents": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "bomId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgBomRoutes": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "bomId",
    "sortFields": [
      "seq"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgBomByproducts": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "bomId",
    "sortFields": [],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgDemands": {
    "gateway": "manufacturing",
    "capabilities": [
      "create",
      "update",
      "delete",
      "confirm",
      "close",
      "void"
    ],
    "commands": [
      "audit",
      "close",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "close": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "manufacturing"
  },
  "mfgDemandItems": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "demandId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgWorkOrders": {
    "gateway": "manufacturing",
    "capabilities": [
      "create",
      "update",
      "delete",
      "void",
      "print",
      "export",
      "batch_print"
    ],
    "commands": [
      "void"
    ],
    "commandTargets": {
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "needDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "manufacturing"
  },
  "mfgWorkOrderComponents": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "workOrderId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgWorkOrderRoutes": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "workOrderId",
    "sortFields": [
      "seq"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgWorkOrderByproducts": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "workOrderId",
    "sortFields": [
      "idx"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  },
  "mfgOutputs": {
    "gateway": "manufacturing",
    "capabilities": [
      "create",
      "update",
      "delete",
      "audit",
      "void"
    ],
    "commands": [
      "audit",
      "void"
    ],
    "commandTargets": {
      "audit": "row",
      "void": "row"
    },
    "parentField": null,
    "sortFields": [
      "outputDate"
    ],
    "equalityFields": [],
    "aggregate": true,
    "draftGateway": "manufacturing"
  },
  "mfgOutputItems": {
    "gateway": "manufacturing",
    "capabilities": [],
    "commands": [],
    "commandTargets": {},
    "parentField": "outputId",
    "sortFields": [
      "idx",
      "outputDate"
    ],
    "equalityFields": [],
    "aggregate": false,
    "draftGateway": null
  }
} as const
export type ConvexDomainResource = keyof typeof CONVEX_DOMAIN_MANIFEST
