defmodule SynieCore.Repo.Migrations.RenameSysCompanyToBasCompany do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:sys_company), to: table(:bas_company))

    drop(constraint(:sys_user_company, "sys_user_company_company_id_fkey"))

    alter table(:sys_user_company) do
      modify(
        :company_id,
        references(:bas_company,
          column: :id,
          name: "sys_user_company_company_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:bas_company, "sys_company_parent_id_fkey"))

    alter table(:bas_company) do
      modify(
        :parent_id,
        references(:bas_company,
          column: :id,
          name: "bas_company_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    execute("ALTER INDEX sys_company_unique_code_index RENAME TO bas_company_unique_code_index")
  end

  def down do
    execute("ALTER INDEX bas_company_unique_code_index RENAME TO sys_company_unique_code_index")

    # 手动调整:先把表改回 sys_company,再重建指向它的外键,否则外键引用的表还不存在
    rename(table(:bas_company), to: table(:sys_company))

    drop(constraint(:sys_company, "bas_company_parent_id_fkey"))

    alter table(:sys_company) do
      modify(
        :parent_id,
        references(:sys_company,
          column: :id,
          name: "sys_company_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:sys_user_company, "sys_user_company_company_id_fkey"))

    alter table(:sys_user_company) do
      modify(
        :company_id,
        references(:sys_company,
          column: :id,
          name: "sys_user_company_company_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end
end
