defmodule SynieCore.Repo.Migrations.AddInvMaterialCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inv_material_category, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :name, :text, null: false
      add :is_leaf, :boolean, null: false, default: true
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_id,
          references(:inv_material_category,
            column: :id,
            name: "inv_material_category_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:inv_material_category, [:code],
             name: "inv_material_category_unique_code_index"
           )
  end

  def down do
    drop_if_exists unique_index(:inv_material_category, [:code],
                     name: "inv_material_category_unique_code_index"
                   )

    drop constraint(:inv_material_category, "inv_material_category_parent_id_fkey")

    drop table(:inv_material_category)
  end
end
