defmodule SynieCore.Repo.Migrations.AddSysAuditLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sys_audit_log, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource, :text, null: false
      add :record_id, :uuid, null: false
      add :record_label, :text
      add :action_type, :text, null: false
      add :action_name, :text, null: false
      add :actor_id, :uuid
      add :actor_name, :text
      add :company_id, :uuid
      add :changes, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:sys_audit_log, [:inserted_at])

    create index(:sys_audit_log, [:resource, :record_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:sys_audit_log, [:resource, :record_id, :inserted_at])

    drop_if_exists index(:sys_audit_log, [:inserted_at])

    drop table(:sys_audit_log)
  end
end
