defmodule SynieCore.Repo.Migrations.CompanyAccountDefaultAndRequiredAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sal_company_account_default, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "sal_company_account_default_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :delivery_debit_account_id,
          references(:bas_account,
            column: :id,
            name: "sal_company_account_default_delivery_debit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :delivery_credit_account_id,
          references(:bas_account,
            column: :id,
            name: "sal_company_account_default_delivery_credit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :receipt_debit_account_id,
          references(:bas_account,
            column: :id,
            name: "sal_company_account_default_receipt_debit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :receipt_credit_account_id,
          references(:bas_account,
            column: :id,
            name: "sal_company_account_default_receipt_credit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:sal_company_account_default, [:company_id],
             name: "sal_company_account_default_unique_company_index"
           )

    # 科目改为草稿必填:清掉尚未选科目的历史草稿(无线上生产数据;零金额单原先可空)
    execute """
    DELETE FROM sal_delivery_item
    WHERE delivery_id IN (
      SELECT id FROM sal_delivery
      WHERE debit_account_id IS NULL OR credit_account_id IS NULL
    )
    """

    execute """
    DELETE FROM sal_delivery
    WHERE debit_account_id IS NULL OR credit_account_id IS NULL
    """

    execute """
    DELETE FROM pur_receipt_item
    WHERE receipt_id IN (
      SELECT id FROM pur_receipt
      WHERE debit_account_id IS NULL OR credit_account_id IS NULL
    )
    """

    execute """
    DELETE FROM pur_receipt
    WHERE debit_account_id IS NULL OR credit_account_id IS NULL
    """

    alter table(:sal_delivery) do
      modify :credit_account_id, :uuid, null: false
      modify :debit_account_id, :uuid, null: false
    end

    alter table(:pur_receipt) do
      modify :credit_account_id, :uuid, null: false
      modify :debit_account_id, :uuid, null: false
    end
  end

  def down do
    alter table(:pur_receipt) do
      modify :debit_account_id, :uuid, null: true
      modify :credit_account_id, :uuid, null: true
    end

    alter table(:sal_delivery) do
      modify :debit_account_id, :uuid, null: true
      modify :credit_account_id, :uuid, null: true
    end

    drop constraint(:sal_company_account_default, "sal_company_account_default_company_id_fkey")

    drop constraint(
           :sal_company_account_default,
           "sal_company_account_default_delivery_debit_account_id_fkey"
         )

    drop constraint(
           :sal_company_account_default,
           "sal_company_account_default_delivery_credit_account_id_fkey"
         )

    drop constraint(
           :sal_company_account_default,
           "sal_company_account_default_receipt_debit_account_id_fkey"
         )

    drop constraint(
           :sal_company_account_default,
           "sal_company_account_default_receipt_credit_account_id_fkey"
         )

    drop_if_exists unique_index(:sal_company_account_default, [:company_id],
                     name: "sal_company_account_default_unique_company_index"
                   )

    drop table(:sal_company_account_default)
  end
end
