defmodule SynieCore.Repo.Migrations.BankReconciliationJournalIdx do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:acc_bank_reconciliation, [:journal_id])
  end

  def down do
    drop_if_exists index(:acc_bank_reconciliation, [:journal_id])
  end
end
