defmodule SynieCore.Repo.Migrations.AddMfgFulfillment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mfg_demand_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :base_qty, :decimal, null: false, default: "0"
      add :need_date, :date
      add :fulfillment_method, :text, null: false, default: "make"
      add :status, :text, null: false, default: "pending"
      add :material_code, :text, null: false, default: ""
      add :material_name, :text, null: false, default: ""
      add :material_spec, :text
      add :unit_name, :text, null: false, default: ""
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :demand_id, :uuid, null: false
      add :company_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :unit_id, :uuid, null: false
      add :sales_order_item_id, :uuid
    end

    create table(:mfg_output_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :base_qty, :decimal, null: false, default: "0"
      add :material_code, :text, null: false, default: ""
      add :material_name, :text, null: false, default: ""
      add :material_spec, :text
      add :unit_name, :text, null: false, default: ""
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :output_id, :uuid, null: false
      add :company_id, :uuid, null: false
      add :work_order_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :unit_id, :uuid, null: false
      add :warehouse_id, :uuid, null: false
    end

    create table(:mfg_output, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:mfg_output_item) do
      modify :output_id,
             references(:mfg_output,
               column: :id,
               name: "mfg_output_item_output_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :company_id,
             references(:bas_company,
               column: :id,
               name: "mfg_output_item_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:mfg_output) do
      add :output_no, :text, null: false
      add :output_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :remarks, :text
      add :status, :text, null: false, default: "draft"
      add :audited_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "mfg_output_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "mfg_output_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "mfg_output_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :audited_by_id,
          references(:sys_user,
            column: :id,
            name: "mfg_output_audited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:mfg_output, [:output_no], name: "mfg_output_unique_output_no_index")

    create table(:mfg_demand, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:mfg_demand_item) do
      modify :demand_id,
             references(:mfg_demand,
               column: :id,
               name: "mfg_demand_item_demand_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :company_id,
             references(:bas_company,
               column: :id,
               name: "mfg_demand_item_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :material_id,
             references(:inv_material,
               column: :id,
               name: "mfg_demand_item_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :unit_id,
             references(:bas_unit,
               column: :id,
               name: "mfg_demand_item_unit_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :sales_order_item_id,
             references(:sal_order_item,
               column: :id,
               name: "mfg_demand_item_sales_order_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:mfg_demand) do
      add :demand_no, :text, null: false
      add :demand_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :remarks, :text
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "mfg_demand_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "mfg_demand_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:mfg_demand, [:demand_no], name: "mfg_demand_unique_demand_no_index")

    create table(:mfg_setting, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :output_overreceive_ratio, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    # 单行表:恒存在一行,不开放 create
    execute(
      "INSERT INTO mfg_setting (id, output_overreceive_ratio, inserted_at, updated_at) VALUES (gen_random_uuid(), 0, now(), now())",
      "DELETE FROM mfg_setting"
    )

    create table(:mfg_work_order, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:mfg_output_item) do
      modify :work_order_id,
             references(:mfg_work_order,
               column: :id,
               name: "mfg_output_item_work_order_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :material_id,
             references(:inv_material,
               column: :id,
               name: "mfg_output_item_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :unit_id,
             references(:bas_unit,
               column: :id,
               name: "mfg_output_item_unit_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :warehouse_id,
             references(:inv_warehouse,
               column: :id,
               name: "mfg_output_item_warehouse_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:mfg_work_order) do
      add :work_order_no, :text, null: false
      add :qty, :decimal, null: false, default: "0"
      add :base_qty, :decimal, null: false, default: "0"
      add :received_base_qty, :decimal, null: false, default: "0"
      add :need_date, :date
      add :material_code, :text, null: false, default: ""
      add :material_name, :text, null: false, default: ""
      add :material_spec, :text
      add :unit_name, :text, null: false, default: ""
      add :status, :text, null: false, default: "in_progress"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "mfg_work_order_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :demand_id,
          references(:mfg_demand,
            column: :id,
            name: "mfg_work_order_demand_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false

      add :demand_item_id,
          references(:mfg_demand_item,
            column: :id,
            name: "mfg_work_order_demand_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false

      add :material_id,
          references(:inv_material,
            column: :id,
            name: "mfg_work_order_material_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false

      add :unit_id,
          references(:bas_unit,
            column: :id,
            name: "mfg_work_order_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "mfg_work_order_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:mfg_work_order, [:demand_item_id],
             name: "mfg_work_order_active_demand_item_index",
             unique: true,
             where: "status <> 'voided'"
           )

    create unique_index(:mfg_work_order, [:work_order_no],
             name: "mfg_work_order_unique_work_order_no_index"
           )

    create constraint(:mfg_setting, :output_overreceive_ratio_range,
             check: """
               output_overreceive_ratio >= 0 AND output_overreceive_ratio <= 1
             """
           )

    create constraint(:mfg_output_item, :qty_positive,
             check: """
               qty > 0
             """
           )

    create constraint(:mfg_demand_item, :qty_positive,
             check: """
               qty > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:mfg_demand_item, :qty_positive)

    drop_if_exists constraint(:mfg_output_item, :qty_positive)

    drop_if_exists constraint(:mfg_setting, :output_overreceive_ratio_range)

    drop constraint(:mfg_work_order, "mfg_work_order_company_id_fkey")

    drop constraint(:mfg_work_order, "mfg_work_order_demand_id_fkey")

    drop constraint(:mfg_work_order, "mfg_work_order_demand_item_id_fkey")

    drop constraint(:mfg_work_order, "mfg_work_order_material_id_fkey")

    drop constraint(:mfg_work_order, "mfg_work_order_unit_id_fkey")

    drop constraint(:mfg_work_order, "mfg_work_order_created_by_id_fkey")

    drop_if_exists unique_index(:mfg_work_order, [:work_order_no],
                     name: "mfg_work_order_unique_work_order_no_index"
                   )

    drop_if_exists index(:mfg_work_order, [:demand_item_id],
                     name: "mfg_work_order_active_demand_item_index"
                   )

    alter table(:mfg_work_order) do
      remove :created_by_id
      remove :unit_id
      remove :material_id
      remove :demand_item_id
      remove :demand_id
      remove :company_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :unit_name
      remove :material_spec
      remove :material_name
      remove :material_code
      remove :need_date
      remove :received_base_qty
      remove :base_qty
      remove :qty
      remove :work_order_no
    end

    drop constraint(:mfg_output_item, "mfg_output_item_work_order_id_fkey")

    drop constraint(:mfg_output_item, "mfg_output_item_material_id_fkey")

    drop constraint(:mfg_output_item, "mfg_output_item_unit_id_fkey")

    drop constraint(:mfg_output_item, "mfg_output_item_warehouse_id_fkey")

    alter table(:mfg_output_item) do
      modify :warehouse_id, :uuid
      modify :unit_id, :uuid
      modify :material_id, :uuid
      modify :work_order_id, :uuid
    end

    drop table(:mfg_work_order)

    drop table(:mfg_setting)

    drop constraint(:mfg_demand, "mfg_demand_company_id_fkey")

    drop constraint(:mfg_demand, "mfg_demand_created_by_id_fkey")

    drop_if_exists unique_index(:mfg_demand, [:demand_no],
                     name: "mfg_demand_unique_demand_no_index"
                   )

    alter table(:mfg_demand) do
      remove :created_by_id
      remove :company_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :remarks
      remove :demand_date
      remove :demand_no
    end

    drop constraint(:mfg_demand_item, "mfg_demand_item_demand_id_fkey")

    drop constraint(:mfg_demand_item, "mfg_demand_item_company_id_fkey")

    drop constraint(:mfg_demand_item, "mfg_demand_item_material_id_fkey")

    drop constraint(:mfg_demand_item, "mfg_demand_item_unit_id_fkey")

    drop constraint(:mfg_demand_item, "mfg_demand_item_sales_order_item_id_fkey")

    alter table(:mfg_demand_item) do
      modify :sales_order_item_id, :uuid
      modify :unit_id, :uuid
      modify :material_id, :uuid
      modify :company_id, :uuid
      modify :demand_id, :uuid
    end

    drop table(:mfg_demand)

    drop constraint(:mfg_output, "mfg_output_company_id_fkey")

    drop constraint(:mfg_output, "mfg_output_warehouse_id_fkey")

    drop constraint(:mfg_output, "mfg_output_created_by_id_fkey")

    drop constraint(:mfg_output, "mfg_output_audited_by_id_fkey")

    drop_if_exists unique_index(:mfg_output, [:output_no],
                     name: "mfg_output_unique_output_no_index"
                   )

    alter table(:mfg_output) do
      remove :audited_by_id
      remove :created_by_id
      remove :warehouse_id
      remove :company_id
      remove :updated_at
      remove :inserted_at
      remove :audited_at
      remove :status
      remove :remarks
      remove :output_date
      remove :output_no
    end

    drop constraint(:mfg_output_item, "mfg_output_item_output_id_fkey")

    drop constraint(:mfg_output_item, "mfg_output_item_company_id_fkey")

    alter table(:mfg_output_item) do
      modify :company_id, :uuid
      modify :output_id, :uuid
    end

    drop table(:mfg_output)

    drop table(:mfg_output_item)

    drop table(:mfg_demand_item)
  end
end
