defmodule SynieCore.Repo.Migrations.AddFilesAttachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sys_file, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :storage, :text, null: false
      add :key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :size, :bigint
      add :sha256, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :uploaded_by_id,
          references(:sys_user,
            column: :id,
            name: "sys_file_uploaded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:sys_attachment, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :category, :text, null: false, default: "default"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :file_id,
          references(:sys_file,
            column: :id,
            name: "sys_attachment_file_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:sys_attachment, [:owner_type, :owner_id])
  end

  def down do
    drop constraint(:sys_attachment, "sys_attachment_file_id_fkey")

    drop_if_exists index(:sys_attachment, [:owner_type, :owner_id])

    drop table(:sys_attachment)

    drop constraint(:sys_file, "sys_file_uploaded_by_id_fkey")

    drop table(:sys_file)
  end
end
