defmodule SynieCore.Repo.Migrations.SalOrderItemSnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  手工理顺(存量表加 allow_nil? false 列):
  1. 五个快照列先按可空加入;
  2. 存量行按当前物料/单位主数据回填(口径为迁移时点);
  3. 存量行的物料 drawing 挂接整份复制到行(owner_type sal_order_item、
     category drawing,company_id 取行的 company_id);
  4. 必填快照列(material_code/material_name/unit_name)回填后再 SET NOT NULL。
  """

  use Ecto.Migration

  def up do
    alter table(:sal_order_item) do
      add(:material_code, :text)
      add(:material_name, :text)
      add(:material_spec, :text)
      add(:customer_part_no, :text)
      add(:unit_name, :text)
    end

    # 存量行快照回填:按当前 inv_material/bas_unit 取值
    execute("""
    UPDATE sal_order_item i
    SET material_code = m.code,
        material_name = m.name,
        material_spec = m.spec,
        customer_part_no = m.customer_part_no,
        unit_name = u.name
    FROM inv_material m, bas_unit u
    WHERE m.id = i.material_id AND u.id = i.unit_id
    """)

    # 存量行图纸挂接复制:物料 drawing 槽位整份挂到行
    # (id/inserted_at 走表默认值,category 显式给 drawing)
    execute("""
    INSERT INTO sys_attachment (owner_type, owner_id, category, file_id, company_id)
    SELECT 'sal_order_item', i.id, 'drawing', a.file_id, i.company_id
    FROM sal_order_item i
    JOIN sys_attachment a
      ON a.owner_type = 'inv_material' AND a.owner_id = i.material_id AND a.category = 'drawing'
    """)

    alter table(:sal_order_item) do
      modify(:material_code, :text, null: false)
      modify(:material_name, :text, null: false)
      modify(:unit_name, :text, null: false)
    end
  end

  def down do
    execute("DELETE FROM sys_attachment WHERE owner_type = 'sal_order_item'")

    alter table(:sal_order_item) do
      remove(:unit_name)
      remove(:customer_part_no)
      remove(:material_spec)
      remove(:material_name)
      remove(:material_code)
    end
  end
end
