defmodule SynieCore.Repo.Migrations.BillFaceAmountOptional do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acc_bill) do
      modify :face_amount, :decimal, null: true
    end
  end

  def down do
    alter table(:acc_bill) do
      modify :face_amount, :decimal, null: false
    end
  end
end
