defmodule SynieCore.Repo.Migrations.AddOrderOutsourcedConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pur_order) do
      add :is_outsourced, :boolean, null: false, default: false
    end

    create table(:pur_order_item_byproduct, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_item_id,
          references(:pur_order_item,
            column: :id,
            name: "pur_order_item_byproduct_order_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "pur_order_item_byproduct_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :material_id,
          references(:inv_material,
            column: :id,
            name: "pur_order_item_byproduct_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :unit_id,
          references(:bas_unit,
            column: :id,
            name: "pur_order_item_byproduct_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:pur_order_item_material, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :issued_qty, :decimal, null: false, default: "0"
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_item_id,
          references(:pur_order_item,
            column: :id,
            name: "pur_order_item_material_order_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "pur_order_item_material_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :material_id,
          references(:inv_material,
            column: :id,
            name: "pur_order_item_material_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :unit_id,
          references(:bas_unit,
            column: :id,
            name: "pur_order_item_material_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    alter table(:pur_order_item) do
      add :bom_id,
          references(:mfg_bom,
            column: :id,
            name: "pur_order_item_bom_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create constraint(:pur_order_item_material, :quantity_positive,
             check: """
               quantity > 0
             """
           )

    create constraint(:pur_order_item_material, :issued_qty_nonnegative,
             check: """
               issued_qty >= 0
             """
           )

    create constraint(:pur_order_item_byproduct, :quantity_positive,
             check: """
               quantity > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:pur_order_item_byproduct, :quantity_positive)

    drop_if_exists constraint(:pur_order_item_material, :issued_qty_nonnegative)

    drop_if_exists constraint(:pur_order_item_material, :quantity_positive)

    drop constraint(:pur_order_item, "pur_order_item_bom_id_fkey")

    alter table(:pur_order_item) do
      remove :bom_id
    end

    drop constraint(:pur_order_item_material, "pur_order_item_material_order_item_id_fkey")

    drop constraint(:pur_order_item_material, "pur_order_item_material_company_id_fkey")

    drop constraint(:pur_order_item_material, "pur_order_item_material_material_id_fkey")

    drop constraint(:pur_order_item_material, "pur_order_item_material_unit_id_fkey")

    drop table(:pur_order_item_material)

    drop constraint(:pur_order_item_byproduct, "pur_order_item_byproduct_order_item_id_fkey")

    drop constraint(:pur_order_item_byproduct, "pur_order_item_byproduct_company_id_fkey")

    drop constraint(:pur_order_item_byproduct, "pur_order_item_byproduct_material_id_fkey")

    drop constraint(:pur_order_item_byproduct, "pur_order_item_byproduct_unit_id_fkey")

    drop table(:pur_order_item_byproduct)

    alter table(:pur_order) do
      remove :is_outsourced
    end
  end
end
