defmodule SynieCore.Repo.Migrations.OutsourcedIssue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  委外发料单(ADR 2026-07-24):新建头/行两表(无金额不过总账,审核写
  「调出仓负＋外协仓正」库存分录并累加发料清单行已发料量);随迁移种子
  `purchase.outsourced_issue` 启用编号规则(见
  `SynieCore.Purchase.OutsourcedIssueNumberingSeed`)。
  """

  use Ecto.Migration

  def up do
    create table(:pur_outsourced_issue, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :issue_no, :text, null: false
      add :issue_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :party_type, :text, null: false
      add :party_id, :uuid, null: false
      add :remarks, :text
      add :status, :text, null: false, default: "draft"
      add :audited_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "pur_outsourced_issue_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :from_warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "pur_outsourced_issue_from_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :outsourced_warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "pur_outsourced_issue_outsourced_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "pur_outsourced_issue_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :audited_by_id,
          references(:sys_user,
            column: :id,
            name: "pur_outsourced_issue_audited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:pur_outsourced_issue, [:issue_no],
             name: "pur_outsourced_issue_unique_issue_no_index"
           )

    create table(:pur_outsourced_issue_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :base_qty, :decimal, null: false, default: "0"
      add :material_code, :text, null: false
      add :material_name, :text, null: false
      add :material_spec, :text
      add :unit_name, :text, null: false
      add :order_no, :text, null: false
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :issue_id,
          references(:pur_outsourced_issue,
            column: :id,
            name: "pur_outsourced_issue_item_issue_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "pur_outsourced_issue_item_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :order_item_material_id,
          references(:pur_order_item_material,
            column: :id,
            name: "pur_outsourced_issue_item_order_item_material_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          ), null: false

      add :material_id,
          references(:inv_material,
            column: :id,
            name: "pur_outsourced_issue_item_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :unit_id,
          references(:bas_unit,
            column: :id,
            name: "pur_outsourced_issue_item_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :from_warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "pur_outsourced_issue_item_from_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :outsourced_warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "pur_outsourced_issue_item_outsourced_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create constraint(:pur_outsourced_issue_item, :qty_positive,
             check: """
               qty > 0
             """
           )

    # 落冲排队的 DDL(新表就位),编号规则种子走应用 Repo 直查
    flush()

    # 种子 purchase.outsourced_issue 启用编号规则(幂等;老环境免手工配置)
    SynieCore.Purchase.OutsourcedIssueNumberingSeed.run!()
  end

  def down do
    drop_if_exists constraint(:pur_outsourced_issue_item, :qty_positive)

    drop constraint(:pur_outsourced_issue_item, "pur_outsourced_issue_item_issue_id_fkey")

    drop constraint(:pur_outsourced_issue_item, "pur_outsourced_issue_item_company_id_fkey")

    drop constraint(
           :pur_outsourced_issue_item,
           "pur_outsourced_issue_item_order_item_material_id_fkey"
         )

    drop constraint(:pur_outsourced_issue_item, "pur_outsourced_issue_item_material_id_fkey")

    drop constraint(:pur_outsourced_issue_item, "pur_outsourced_issue_item_unit_id_fkey")

    drop constraint(
           :pur_outsourced_issue_item,
           "pur_outsourced_issue_item_from_warehouse_id_fkey"
         )

    drop constraint(
           :pur_outsourced_issue_item,
           "pur_outsourced_issue_item_outsourced_warehouse_id_fkey"
         )

    drop table(:pur_outsourced_issue_item)

    drop constraint(:pur_outsourced_issue, "pur_outsourced_issue_company_id_fkey")

    drop constraint(:pur_outsourced_issue, "pur_outsourced_issue_from_warehouse_id_fkey")

    drop constraint(:pur_outsourced_issue, "pur_outsourced_issue_outsourced_warehouse_id_fkey")

    drop constraint(:pur_outsourced_issue, "pur_outsourced_issue_created_by_id_fkey")

    drop constraint(:pur_outsourced_issue, "pur_outsourced_issue_audited_by_id_fkey")

    drop_if_exists unique_index(:pur_outsourced_issue, [:issue_no],
                     name: "pur_outsourced_issue_unique_issue_no_index"
                   )

    drop table(:pur_outsourced_issue)

    # 回滚即撤销本功能:连带删掉随迁移种子的委外发料编号规则(计数器外键级联随删)
    execute("DELETE FROM sys_numbering_rule WHERE resource = 'purchase.outsourced_issue'", "")
  end
end
