defmodule SynieCore.Repo.Migrations.AddAccGlEntry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acc_gl_entry, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :seq, :bigserial, null: false
      add :posting_date, :date, null: false
      add :debit, :decimal, null: false, default: "0"
      add :credit, :decimal, null: false, default: "0"
      add :party_type, :text
      add :party_id, :uuid
      add :voucher_type, :text, null: false
      add :voucher_id, :uuid, null: false
      add :voucher_no, :text, null: false
      add :is_cancelled, :boolean, null: false, default: false
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "acc_gl_entry_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :account_id,
          references(:bas_account,
            column: :id,
            name: "acc_gl_entry_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :currency_id,
          references(:bas_currency,
            column: :id,
            name: "acc_gl_entry_currency_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:acc_gl_entry, [:voucher_type, :voucher_id])

    create index(:acc_gl_entry, [:company_id, :account_id, :posting_date])

    create constraint(:acc_gl_entry, :single_sided_amount,
             check: """
               debit >= 0 AND credit >= 0 AND (debit = 0) <> (credit = 0)
             """
           )

    create constraint(:acc_gl_entry, :party_pair,
             check: """
               (party_type IS NULL) = (party_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:acc_gl_entry, :party_pair)

    drop_if_exists constraint(:acc_gl_entry, :single_sided_amount)

    drop constraint(:acc_gl_entry, "acc_gl_entry_company_id_fkey")

    drop constraint(:acc_gl_entry, "acc_gl_entry_account_id_fkey")

    drop constraint(:acc_gl_entry, "acc_gl_entry_currency_id_fkey")

    drop_if_exists index(:acc_gl_entry, [:company_id, :account_id, :posting_date])

    drop_if_exists index(:acc_gl_entry, [:voucher_type, :voucher_id])

    drop table(:acc_gl_entry)
  end
end
