defmodule SynieCore.Repo.Migrations.AddEmployeeInsuranceTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:hr_employees) do
      add :insurance_types, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:hr_employees) do
      remove :insurance_types
    end
  end
end
