defmodule SynieCore.Repo.Migrations.OrderItemBaseQty do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sal_order_item) do
      add :base_qty, :decimal, null: false, default: "0"
    end

    # 回填:默认单位时 base_qty = qty;否则 qty ÷ 转换系数(1 默认单位 = factor 行单位)
    # 子查询回填,避免 UPDATE...FROM 的 JOIN ON 引用目标表触发 PG 限制
    execute("""
    UPDATE sal_order_item AS i
    SET base_qty = sub.new_base
    FROM (
      SELECT
        i2.id,
        CASE
          WHEN i2.unit_id = m.default_unit_id THEN i2.qty
          WHEN mu.factor IS NOT NULL AND mu.factor > 0 THEN ROUND(i2.qty / mu.factor, 6)
          ELSE i2.qty
        END AS new_base
      FROM sal_order_item AS i2
      INNER JOIN inv_material AS m ON m.id = i2.material_id
      LEFT JOIN inv_material_unit AS mu
        ON mu.material_id = i2.material_id AND mu.unit_id = i2.unit_id
    ) AS sub
    WHERE i.id = sub.id
    """)
  end

  def down do
    alter table(:sal_order_item) do
      remove :base_qty
    end
  end
end
