defmodule SynieCore.Repo.Migrations.AddOrgCompany do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sys_user_company, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:sys_user,
          column: :id,
          name: "sys_user_company_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:company_id, :uuid, null: false)
    end

    create(
      unique_index(:sys_user_company, [:user_id, :company_id],
        name: "sys_user_company_unique_user_company_index"
      )
    )

    create table(:sys_company, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:sys_user_company) do
      modify(
        :company_id,
        references(:sys_company,
          column: :id,
          name: "sys_user_company_company_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:sys_company) do
      add(:code, :text, null: false)
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :parent_id,
        references(:sys_company,
          column: :id,
          name: "sys_company_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(unique_index(:sys_company, [:code], name: "sys_company_unique_code_index"))
  end

  def down do
    drop_if_exists(unique_index(:sys_company, [:code], name: "sys_company_unique_code_index"))

    drop(constraint(:sys_company, "sys_company_parent_id_fkey"))

    alter table(:sys_company) do
      remove(:parent_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:name)
      remove(:code)
    end

    drop(constraint(:sys_user_company, "sys_user_company_company_id_fkey"))

    alter table(:sys_user_company) do
      modify(:company_id, :uuid)
    end

    drop(table(:sys_company))

    drop(constraint(:sys_user_company, "sys_user_company_user_id_fkey"))

    drop_if_exists(
      unique_index(:sys_user_company, [:user_id, :company_id],
        name: "sys_user_company_unique_user_company_index"
      )
    )

    drop(table(:sys_user_company))
  end
end
