defmodule SynieCore.Repo.Migrations.SetupWizard do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  手工补种(照 acc_setting/sales_order_currency 先例):
  1. sys_setting 单行:库中已有用户即视为已初始化(存量环境回填完成时刻,永不进向导),
     全新库留空(首启进初始化向导);
  2. 内置 admin 角色 + 全域通配 `*` 授权:迁移统一种子,新老环境一致;幂等,
     种子走 SQL 直插,不触发 Ash 层的内置角色守卫。
  """

  use Ecto.Migration

  def up do
    alter table(:sys_role) do
      add :builtin, :boolean, null: false, default: false
    end

    create table(:sys_setting, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :setup_completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:sys_user) do
      add :preferred_language, :text
    end

    # sys_setting 单行(资源不开放 create):存量库已有用户 → 回填已完成;全新库 → 留空进向导
    execute("""
    INSERT INTO sys_setting (id, setup_completed_at, inserted_at, updated_at)
    SELECT gen_random_uuid(),
           CASE WHEN EXISTS (SELECT 1 FROM sys_user) THEN now() ELSE NULL END,
           now(), now()
    """)

    # 内置 admin 角色(幂等):全域通配 `*` 授权,新老环境一致
    execute("""
    INSERT INTO sys_role (id, code, name, enabled, builtin, inserted_at, updated_at)
    SELECT gen_random_uuid(), 'admin', '管理员', true, true, now(), now()
    WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE code = 'admin')
    """)

    execute("""
    INSERT INTO sys_role_permission (id, role_id, permission, inserted_at)
    SELECT gen_random_uuid(), r.id, '*', now()
    FROM sys_role r
    WHERE r.code = 'admin' AND r.builtin
      AND NOT EXISTS (
        SELECT 1 FROM sys_role_permission rp WHERE rp.role_id = r.id AND rp.permission = '*'
      )
    """)
  end

  def down do
    alter table(:sys_user) do
      remove :preferred_language
    end

    drop table(:sys_setting)

    alter table(:sys_role) do
      remove :builtin
    end
  end
end
