defmodule SynieCore.Repo.Migrations.RenameSysUnitToBasUnit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:sys_unit), to: table(:bas_unit))

    execute(
      "ALTER INDEX sys_unit_unique_base_per_type_index RENAME TO bas_unit_unique_base_per_type_index"
    )

    execute("ALTER INDEX sys_unit_unique_symbol_index RENAME TO bas_unit_unique_symbol_index")
  end

  def down do
    execute("ALTER INDEX bas_unit_unique_symbol_index RENAME TO sys_unit_unique_symbol_index")

    execute(
      "ALTER INDEX bas_unit_unique_base_per_type_index RENAME TO sys_unit_unique_base_per_type_index"
    )

    rename(table(:bas_unit), to: table(:sys_unit))
  end
end
