defmodule SynieCore.Repo.Migrations.BankReconciliation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acc_bank_reconciliation, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "acc_bank_reconciliation_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :bank_transaction_id,
          references(:acc_bank_transaction,
            column: :id,
            name: "acc_bank_reconciliation_bank_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false

      add :journal_id,
          references(:acc_gl_journal,
            column: :id,
            name: "acc_bank_reconciliation_journal_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false
    end

    create unique_index(:acc_bank_reconciliation, [:bank_transaction_id, :journal_id],
             name: "acc_bank_reconciliation_unique_txn_journal_index"
           )

    create constraint(:acc_bank_reconciliation, :positive_amount,
             check: """
               amount > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:acc_bank_reconciliation, :positive_amount)

    drop constraint(:acc_bank_reconciliation, "acc_bank_reconciliation_company_id_fkey")

    drop constraint(:acc_bank_reconciliation, "acc_bank_reconciliation_bank_transaction_id_fkey")

    drop constraint(:acc_bank_reconciliation, "acc_bank_reconciliation_journal_id_fkey")

    drop_if_exists unique_index(:acc_bank_reconciliation, [:bank_transaction_id, :journal_id],
                     name: "acc_bank_reconciliation_unique_txn_journal_index"
                   )

    drop table(:acc_bank_reconciliation)
  end
end
