defmodule SynieCore.Repo.Migrations.AddBaseUnitCurrencyAndCompanyShortName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sys_unit, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:unit_type, :text, null: false)
      add(:is_base, :boolean, null: false, default: false)
      add(:name, :text, null: false)
      add(:symbol, :text, null: false)
      add(:ratio, :decimal, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:sys_unit, [:unit_type],
        name: "sys_unit_unique_base_per_type_index",
        where: "(is_base = true)"
      )
    )

    create(unique_index(:sys_unit, [:symbol], name: "sys_unit_unique_symbol_index"))

    create table(:sys_currency, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:iso_code, :text, null: false)
      add(:symbol, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:sys_currency, [:iso_code], name: "sys_currency_unique_iso_code_index"))

    alter table(:sys_company) do
      add(:short_name, :text, null: false)
    end
  end

  def down do
    alter table(:sys_company) do
      remove(:short_name)
    end

    drop_if_exists(
      unique_index(:sys_currency, [:iso_code], name: "sys_currency_unique_iso_code_index")
    )

    drop(table(:sys_currency))

    drop_if_exists(unique_index(:sys_unit, [:symbol], name: "sys_unit_unique_symbol_index"))

    drop_if_exists(
      unique_index(:sys_unit, [:unit_type], name: "sys_unit_unique_base_per_type_index")
    )

    drop(table(:sys_unit))
  end
end
