defmodule SynieCore.Repo.Migrations.AddAccBankTransaction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acc_bank_transaction, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :occurred_at, :utc_datetime, null: false
      add :income, :decimal
      add :expense, :decimal
      add :balance, :decimal
      add :counterparty_name, :text
      add :counterparty_account, :text
      add :summary, :text
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "acc_bank_transaction_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :bank_account_id,
          references(:acc_bank_account,
            column: :id,
            name: "acc_bank_transaction_bank_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:acc_bank_transaction, [:company_id, :bank_account_id, :occurred_at])

    create constraint(:acc_bank_transaction, :single_sided_amount,
             check: """
               (income IS NULL) <> (expense IS NULL) AND COALESCE(income, expense) > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:acc_bank_transaction, :single_sided_amount)

    drop constraint(:acc_bank_transaction, "acc_bank_transaction_company_id_fkey")

    drop constraint(:acc_bank_transaction, "acc_bank_transaction_bank_account_id_fkey")

    drop_if_exists index(:acc_bank_transaction, [:company_id, :bank_account_id, :occurred_at])

    drop table(:acc_bank_transaction)
  end
end
