defmodule SynieCore.Repo.Migrations.SalesQuotation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sal_quotation_tier, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :min_qty, :decimal, null: false
      add :price, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id, :uuid, null: false
      add :company_id, :uuid, null: false
    end

    create unique_index(:sal_quotation_tier, [:item_id, :min_qty],
             name: "sal_quotation_tier_unique_item_min_qty_index"
           )

    create table(:sal_quotation, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quotation_no, :text, null: false
      add :quotation_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :valid_until, :date, null: false
      add :party_type, :text, null: false
      add :party_id, :uuid, null: false
      add :terms, :text
      add :remarks, :text
      add :status, :text, null: false, default: "draft"
      add :audited_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "sal_quotation_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :currency_id,
          references(:bas_currency,
            column: :id,
            name: "sal_quotation_currency_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "sal_quotation_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :audited_by_id,
          references(:sys_user,
            column: :id,
            name: "sal_quotation_audited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:sal_quotation, [:quotation_no],
             name: "sal_quotation_unique_quotation_no_index"
           )

    create table(:sal_quotation_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sal_quotation_tier) do
      modify :item_id,
             references(:sal_quotation_item,
               column: :id,
               name: "sal_quotation_tier_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :company_id,
             references(:bas_company,
               column: :id,
               name: "sal_quotation_tier_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sal_quotation_item) do
      add :idx, :bigint, null: false
      add :pricing_mode, :text, null: false, default: "fixed"
      add :price, :decimal
      add :tax_rate, :decimal, null: false, default: "0.13"
      add :material_code, :text, null: false
      add :material_name, :text, null: false
      add :material_spec, :text
      add :customer_part_no, :text
      add :unit_name, :text, null: false
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :quotation_id,
          references(:sal_quotation,
            column: :id,
            name: "sal_quotation_item_quotation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "sal_quotation_item_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :material_id,
          references(:inv_material,
            column: :id,
            name: "sal_quotation_item_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :unit_id,
          references(:bas_unit,
            column: :id,
            name: "sal_quotation_item_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:sal_quotation_item, [:quotation_id, :material_id, :unit_id],
             name: "sal_quotation_item_unique_material_unit_index"
           )

    create constraint(:sal_quotation_item, :pricing_price_consistency,
             check: """
               (pricing_mode = 'fixed' AND price IS NOT NULL) OR (pricing_mode <> 'fixed' AND price IS NULL)
             """
           )

    create constraint(:sal_quotation_item, :price_nonnegative,
             check: """
               price IS NULL OR price >= 0
             """
           )

    create constraint(:sal_quotation_item, :tax_rate_range,
             check: """
               tax_rate >= 0 AND tax_rate < 1
             """
           )

    create constraint(:sal_quotation, :party_pair,
             check: """
               (party_type IS NULL) = (party_id IS NULL)
             """
           )

    create constraint(:sal_quotation_tier, :min_qty_positive,
             check: """
               min_qty > 0
             """
           )

    create constraint(:sal_quotation_tier, :price_nonnegative,
             check: """
               price >= 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:sal_quotation_tier, :price_nonnegative)

    drop_if_exists constraint(:sal_quotation_tier, :min_qty_positive)

    drop_if_exists constraint(:sal_quotation, :party_pair)

    drop_if_exists constraint(:sal_quotation_item, :tax_rate_range)

    drop_if_exists constraint(:sal_quotation_item, :price_nonnegative)

    drop_if_exists constraint(:sal_quotation_item, :pricing_price_consistency)

    drop constraint(:sal_quotation_item, "sal_quotation_item_quotation_id_fkey")

    drop constraint(:sal_quotation_item, "sal_quotation_item_company_id_fkey")

    drop constraint(:sal_quotation_item, "sal_quotation_item_material_id_fkey")

    drop constraint(:sal_quotation_item, "sal_quotation_item_unit_id_fkey")

    drop_if_exists unique_index(:sal_quotation_item, [:quotation_id, :material_id, :unit_id],
                     name: "sal_quotation_item_unique_material_unit_index"
                   )

    alter table(:sal_quotation_item) do
      remove :unit_id
      remove :material_id
      remove :company_id
      remove :quotation_id
      remove :updated_at
      remove :inserted_at
      remove :remarks
      remove :unit_name
      remove :customer_part_no
      remove :material_spec
      remove :material_name
      remove :material_code
      remove :tax_rate
      remove :price
      remove :pricing_mode
      remove :idx
    end

    drop constraint(:sal_quotation_tier, "sal_quotation_tier_item_id_fkey")

    drop constraint(:sal_quotation_tier, "sal_quotation_tier_company_id_fkey")

    alter table(:sal_quotation_tier) do
      modify :company_id, :uuid
      modify :item_id, :uuid
    end

    drop table(:sal_quotation_item)

    drop constraint(:sal_quotation, "sal_quotation_company_id_fkey")

    drop constraint(:sal_quotation, "sal_quotation_currency_id_fkey")

    drop constraint(:sal_quotation, "sal_quotation_created_by_id_fkey")

    drop constraint(:sal_quotation, "sal_quotation_audited_by_id_fkey")

    drop_if_exists unique_index(:sal_quotation, [:quotation_no],
                     name: "sal_quotation_unique_quotation_no_index"
                   )

    drop table(:sal_quotation)

    drop_if_exists unique_index(:sal_quotation_tier, [:item_id, :min_qty],
                     name: "sal_quotation_tier_unique_item_min_qty_index"
                   )

    drop table(:sal_quotation_tier)
  end
end
