defmodule SynieCore.Repo.Migrations.AddAuthzTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sys_user_role, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:sys_user,
          column: :id,
          name: "sys_user_role_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:role_id, :uuid, null: false)
    end

    create(
      unique_index(:sys_user_role, [:user_id, :role_id],
        name: "sys_user_role_unique_user_role_index"
      )
    )

    alter table(:sys_user) do
      add(:super_admin, :boolean, null: false, default: false)
      add(:all_companies, :boolean, null: false, default: false)
    end

    create table(:sys_role_permission, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:permission, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:role_id, :uuid, null: false)
    end

    create(
      unique_index(:sys_role_permission, [:role_id, :permission],
        name: "sys_role_permission_unique_role_permission_index"
      )
    )

    create table(:sys_role, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:sys_user_role) do
      modify(
        :role_id,
        references(:sys_role,
          column: :id,
          name: "sys_user_role_role_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:sys_role_permission) do
      modify(
        :role_id,
        references(:sys_role,
          column: :id,
          name: "sys_role_permission_role_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:sys_role) do
      add(:code, :text, null: false)
      add(:name, :text, null: false)
      add(:enabled, :boolean, null: false, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:sys_role, [:code], name: "sys_role_unique_code_index"))
  end

  def down do
    drop_if_exists(unique_index(:sys_role, [:code], name: "sys_role_unique_code_index"))

    alter table(:sys_role) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:enabled)
      remove(:name)
      remove(:code)
    end

    drop(constraint(:sys_role_permission, "sys_role_permission_role_id_fkey"))

    alter table(:sys_role_permission) do
      modify(:role_id, :uuid)
    end

    drop(constraint(:sys_user_role, "sys_user_role_role_id_fkey"))

    alter table(:sys_user_role) do
      modify(:role_id, :uuid)
    end

    drop(table(:sys_role))

    drop_if_exists(
      unique_index(:sys_role_permission, [:role_id, :permission],
        name: "sys_role_permission_unique_role_permission_index"
      )
    )

    drop(table(:sys_role_permission))

    alter table(:sys_user) do
      remove(:all_companies)
      remove(:super_admin)
    end

    drop(constraint(:sys_user_role, "sys_user_role_user_id_fkey"))

    drop_if_exists(
      unique_index(:sys_user_role, [:user_id, :role_id],
        name: "sys_user_role_unique_user_role_index"
      )
    )

    drop(table(:sys_user_role))
  end
end
