defmodule SynieCore.Repo.Migrations.PurchaseReceipt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pur_receipt_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :base_qty, :decimal, null: false, default: "0"
      add :material_code, :text, null: false
      add :material_name, :text, null: false
      add :material_spec, :text
      add :customer_part_no, :text
      add :unit_name, :text, null: false
      add :order_no, :text, null: false
      add :order_qty, :decimal, null: false, default: "0"
      add :order_base_qty, :decimal, null: false, default: "0"
      add :order_unit_name, :text, null: false
      add :order_price, :decimal, null: false, default: "0"
      add :order_amount, :decimal, null: false, default: "0"
      add :order_base_price, :decimal, null: false, default: "0"
      add :order_base_amount, :decimal, null: false, default: "0"
      add :order_tax_rate, :decimal, null: false, default: "0"
      add :order_currency_code, :text, null: false
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :receipt_id, :uuid, null: false
      add :company_id, :uuid, null: false
      add :order_item_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :unit_id, :uuid, null: false
      add :warehouse_id, :uuid, null: false
    end

    create table(:pur_receipt, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:pur_receipt_item) do
      modify :receipt_id,
             references(:pur_receipt,
               column: :id,
               name: "pur_receipt_item_receipt_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :company_id,
             references(:bas_company,
               column: :id,
               name: "pur_receipt_item_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :order_item_id,
             references(:pur_order_item,
               column: :id,
               name: "pur_receipt_item_order_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )

      modify :material_id,
             references(:inv_material,
               column: :id,
               name: "pur_receipt_item_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :unit_id,
             references(:bas_unit,
               column: :id,
               name: "pur_receipt_item_unit_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :warehouse_id,
             references(:inv_warehouse,
               column: :id,
               name: "pur_receipt_item_warehouse_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pur_receipt) do
      add :receipt_no, :text, null: false
      add :receipt_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :posting_date, :date
      add :party_type, :text, null: false
      add :party_id, :uuid, null: false
      add :remarks, :text
      add :status, :text, null: false, default: "draft"
      add :audited_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "pur_receipt_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "pur_receipt_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :debit_account_id,
          references(:bas_account,
            column: :id,
            name: "pur_receipt_debit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :credit_account_id,
          references(:bas_account,
            column: :id,
            name: "pur_receipt_credit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "pur_receipt_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :audited_by_id,
          references(:sys_user,
            column: :id,
            name: "pur_receipt_audited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:pur_receipt, [:receipt_no], name: "pur_receipt_unique_receipt_no_index")

    create constraint(:pur_receipt, :party_pair,
             check: """
               (party_type IS NULL) = (party_id IS NULL)
             """
           )

    create constraint(:pur_receipt_item, :qty_positive,
             check: """
               qty > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:pur_receipt_item, :qty_positive)

    drop_if_exists constraint(:pur_receipt, :party_pair)

    drop constraint(:pur_receipt, "pur_receipt_company_id_fkey")

    drop constraint(:pur_receipt, "pur_receipt_warehouse_id_fkey")

    drop constraint(:pur_receipt, "pur_receipt_debit_account_id_fkey")

    drop constraint(:pur_receipt, "pur_receipt_credit_account_id_fkey")

    drop constraint(:pur_receipt, "pur_receipt_created_by_id_fkey")

    drop constraint(:pur_receipt, "pur_receipt_audited_by_id_fkey")

    drop_if_exists unique_index(:pur_receipt, [:receipt_no],
                     name: "pur_receipt_unique_receipt_no_index"
                   )

    alter table(:pur_receipt) do
      remove :audited_by_id
      remove :created_by_id
      remove :credit_account_id
      remove :debit_account_id
      remove :warehouse_id
      remove :company_id
      remove :updated_at
      remove :inserted_at
      remove :audited_at
      remove :status
      remove :remarks
      remove :party_id
      remove :party_type
      remove :posting_date
      remove :receipt_date
      remove :receipt_no
    end

    drop constraint(:pur_receipt_item, "pur_receipt_item_receipt_id_fkey")

    drop constraint(:pur_receipt_item, "pur_receipt_item_company_id_fkey")

    drop constraint(:pur_receipt_item, "pur_receipt_item_order_item_id_fkey")

    drop constraint(:pur_receipt_item, "pur_receipt_item_material_id_fkey")

    drop constraint(:pur_receipt_item, "pur_receipt_item_unit_id_fkey")

    drop constraint(:pur_receipt_item, "pur_receipt_item_warehouse_id_fkey")

    alter table(:pur_receipt_item) do
      modify :warehouse_id, :uuid
      modify :unit_id, :uuid
      modify :material_id, :uuid
      modify :order_item_id, :uuid
      modify :company_id, :uuid
      modify :receipt_id, :uuid
    end

    drop table(:pur_receipt)

    drop table(:pur_receipt_item)
  end
end
