defmodule SynieCore.Repo.Migrations.AddHrPayroll do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:hr_payroll, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :month, :text, null: false
      add :workdays, :decimal, null: false, default: "0"
      add :attendance_days, :bigint, null: false, default: 0
      add :missing_days, :bigint, null: false, default: 0
      add :overtime_hours, :decimal, null: false, default: "0"
      add :daily_wage, :decimal, null: false, default: "0"
      add :base_amount, :decimal, null: false, default: "0"
      add :allowance, :decimal, null: false, default: "0"
      add :bonus, :decimal, null: false, default: "0"
      add :fine, :decimal, null: false, default: "0"
      add :loan_deduction, :decimal, null: false, default: "0"
      add :payable, :decimal, null: false, default: "0"
      add :status, :text, null: false, default: "pending"
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :employee_id,
          references(:hr_employees,
            column: :id,
            name: "hr_payroll_employee_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:hr_payroll, [:month])

    create unique_index(:hr_payroll, [:employee_id, :month],
             name: "hr_payroll_unique_employee_month_index"
           )

    create table(:hr_employee_loan, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :occurred_on, :date, null: false
      add :amount, :decimal, null: false
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :employee_id,
          references(:hr_employees,
            column: :id,
            name: "hr_employee_loan_employee_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :payroll_id,
          references(:hr_payroll,
            column: :id,
            name: "hr_employee_loan_payroll_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "hr_employee_loan_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:hr_employee_loan, [:payroll_id], where: "payroll_id IS NOT NULL")

    create index(:hr_employee_loan, [:employee_id])

    create table(:hr_payroll_payment, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :month, :text
      add :paid_on, :date, null: false
      add :amount, :decimal, null: false
      add :kind, :text, null: false, default: "normal"
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :payroll_id,
          references(:hr_payroll,
            column: :id,
            name: "hr_payroll_payment_payroll_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :employee_id,
          references(:hr_employees,
            column: :id,
            name: "hr_payroll_payment_employee_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "hr_payroll_payment_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:hr_payroll_payment, [:month])

    create index(:hr_payroll_payment, [:employee_id, :month])

    create index(:hr_payroll_payment, [:payroll_id])
  end

  def down do
    drop constraint(:hr_payroll_payment, "hr_payroll_payment_payroll_id_fkey")

    drop constraint(:hr_payroll_payment, "hr_payroll_payment_employee_id_fkey")

    drop constraint(:hr_payroll_payment, "hr_payroll_payment_created_by_id_fkey")

    drop_if_exists index(:hr_payroll_payment, [:payroll_id])

    drop_if_exists index(:hr_payroll_payment, [:employee_id, :month])

    drop_if_exists index(:hr_payroll_payment, [:month])

    drop table(:hr_payroll_payment)

    drop constraint(:hr_employee_loan, "hr_employee_loan_employee_id_fkey")

    drop constraint(:hr_employee_loan, "hr_employee_loan_payroll_id_fkey")

    drop constraint(:hr_employee_loan, "hr_employee_loan_created_by_id_fkey")

    drop_if_exists index(:hr_employee_loan, [:employee_id])

    drop_if_exists index(:hr_employee_loan, [:payroll_id])

    drop table(:hr_employee_loan)

    drop constraint(:hr_payroll, "hr_payroll_employee_id_fkey")

    drop_if_exists unique_index(:hr_payroll, [:employee_id, :month],
                     name: "hr_payroll_unique_employee_month_index"
                   )

    drop_if_exists index(:hr_payroll, [:month])

    drop table(:hr_payroll)
  end
end
