defmodule SynieCore.Repo.Migrations.AddInvStockCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inv_stock_count, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :doc_no, :text, null: false
      add :posting_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :summary, :text
      add :remarks, :text
      add :status, :text, null: false, default: "draft"
      add :audited_at, :utc_datetime_usec
      add :snapshot_taken_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "inv_stock_count_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "inv_stock_count_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "inv_stock_count_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :audited_by_id,
          references(:sys_user,
            column: :id,
            name: "inv_stock_count_audited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:inv_stock_count, [:doc_no], name: "inv_stock_count_unique_doc_no_index")

    alter table(:inv_stock_entry) do
      add :cancelled_at, :utc_datetime_usec
    end

    create table(:inv_stock_count_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :counted_quantity, :decimal
      add :converted_counted, :decimal
      add :book_quantity, :decimal, null: false, default: "0"
      add :material_code, :text, null: false
      add :material_name, :text, null: false
      add :material_spec, :text
      add :unit_name, :text, null: false
      add :remark, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :count_id,
          references(:inv_stock_count,
            column: :id,
            name: "inv_stock_count_item_count_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "inv_stock_count_item_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :material_id,
          references(:inv_material,
            column: :id,
            name: "inv_stock_count_item_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :unit_id,
          references(:bas_unit,
            column: :id,
            name: "inv_stock_count_item_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create constraint(:inv_stock_count_item, :counted_quantity_nonnegative,
             check: """
               counted_quantity >= 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:inv_stock_count_item, :counted_quantity_nonnegative)

    drop constraint(:inv_stock_count_item, "inv_stock_count_item_count_id_fkey")

    drop constraint(:inv_stock_count_item, "inv_stock_count_item_company_id_fkey")

    drop constraint(:inv_stock_count_item, "inv_stock_count_item_material_id_fkey")

    drop constraint(:inv_stock_count_item, "inv_stock_count_item_unit_id_fkey")

    drop table(:inv_stock_count_item)

    alter table(:inv_stock_entry) do
      remove :cancelled_at
    end

    drop constraint(:inv_stock_count, "inv_stock_count_company_id_fkey")

    drop constraint(:inv_stock_count, "inv_stock_count_warehouse_id_fkey")

    drop constraint(:inv_stock_count, "inv_stock_count_created_by_id_fkey")

    drop constraint(:inv_stock_count, "inv_stock_count_audited_by_id_fkey")

    drop_if_exists unique_index(:inv_stock_count, [:doc_no],
                     name: "inv_stock_count_unique_doc_no_index"
                   )

    drop table(:inv_stock_count)
  end
end
