defmodule SynieCore.Repo.Migrations.SalesOrderTyping do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sal_setting, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sample_item_max_qty, :bigint, null: false, default: 100

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    # 单行 seed:资源不开放 create,行在此一次性创建(同 acc_setting 先例)
    execute(
      "INSERT INTO sal_setting (id, sample_item_max_qty, inserted_at, updated_at) VALUES (gen_random_uuid(), 100, now(), now())",
      "DELETE FROM sal_setting"
    )

    alter table(:sal_order) do
      add :order_type, :text, null: false, default: "regular"
    end

    alter table(:sal_order_item) do
      add :quotation_item_id,
          references(:sal_quotation_item,
            column: :id,
            name: "sal_order_item_quotation_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          )
    end

    create constraint(:sal_setting, :sample_item_max_qty_positive,
             check: """
               sample_item_max_qty > 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:sal_setting, :sample_item_max_qty_positive)

    drop constraint(:sal_order_item, "sal_order_item_quotation_item_id_fkey")

    alter table(:sal_order_item) do
      remove :quotation_item_id
    end

    alter table(:sal_order) do
      remove :order_type
    end

    drop table(:sal_setting)
  end
end
