defmodule SynieCore.Repo.Migrations.GlEntryRedReversal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acc_gl_entry) do
      add(:is_reversed, :boolean, null: false, default: false)
      add(:is_reversal, :boolean, null: false, default: false)
    end

    drop_if_exists(constraint(:acc_gl_entry, :single_sided_amount))

    create(
      constraint(:acc_gl_entry, :single_sided_amount,
        check: """
          (debit = 0) <> (credit = 0)
        """
      )
    )
  end

  def down do
    drop_if_exists(constraint(:acc_gl_entry, :single_sided_amount))

    create(
      constraint(:acc_gl_entry, :single_sided_amount,
        check: """
          debit >= 0 AND credit >= 0 AND (debit = 0) <> (credit = 0)
        """
      )
    )

    alter table(:acc_gl_entry) do
      remove(:is_reversal)
      remove(:is_reversed)
    end
  end
end
