defmodule SynieCore.Repo.Migrations.AddSalReconciliation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sal_delivery_item) do
      add :reconciled_qty, :decimal, null: false, default: "0"
    end

    alter table(:acc_vat_invoice) do
      add :sal_reconciliation_id, :uuid
    end

    create table(:sal_reconciliation, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:acc_vat_invoice) do
      modify :sal_reconciliation_id,
             references(:sal_reconciliation,
               column: :id,
               name: "acc_vat_invoice_sal_reconciliation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )
    end

    alter table(:sal_reconciliation) do
      add :reconciliation_no, :text, null: false
      add :reconciliation_type, :text, null: false
      add :party_type, :text, null: false
      add :party_id, :uuid, null: false
      add :posting_date, :date
      add :remarks, :text
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "sal_reconciliation_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :debit_account_id,
          references(:bas_account,
            column: :id,
            name: "sal_reconciliation_debit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :credit_account_id,
          references(:bas_account,
            column: :id,
            name: "sal_reconciliation_credit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "sal_reconciliation_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:sal_reconciliation, [:reconciliation_no],
             name: "sal_reconciliation_unique_reconciliation_no_index"
           )

    create table(:sal_reconciliation_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :base_qty, :decimal, null: false, default: "0"
      add :amount, :decimal, null: false, default: "0"
      add :base_amount, :decimal, null: false, default: "0"
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :reconciliation_id,
          references(:sal_reconciliation,
            column: :id,
            name: "sal_reconciliation_item_reconciliation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "sal_reconciliation_item_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :delivery_item_id,
          references(:sal_delivery_item,
            column: :id,
            name: "sal_reconciliation_item_delivery_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          ), null: false
    end

    create constraint(:sal_reconciliation_item, :qty_positive,
             check: """
               qty > 0
             """
           )

    create constraint(:sal_reconciliation, :party_pair,
             check: """
               (party_type IS NULL) = (party_id IS NULL)
             """
           )

    create constraint(:sal_delivery_item, :reconciled_qty_nonnegative,
             check: """
               reconciled_qty >= 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:sal_delivery_item, :reconciled_qty_nonnegative)

    drop_if_exists constraint(:sal_reconciliation, :party_pair)

    drop_if_exists constraint(:sal_reconciliation_item, :qty_positive)

    drop constraint(:sal_reconciliation_item, "sal_reconciliation_item_reconciliation_id_fkey")

    drop constraint(:sal_reconciliation_item, "sal_reconciliation_item_company_id_fkey")

    drop constraint(:sal_reconciliation_item, "sal_reconciliation_item_delivery_item_id_fkey")

    drop table(:sal_reconciliation_item)

    drop constraint(:sal_reconciliation, "sal_reconciliation_company_id_fkey")

    drop constraint(:sal_reconciliation, "sal_reconciliation_debit_account_id_fkey")

    drop constraint(:sal_reconciliation, "sal_reconciliation_credit_account_id_fkey")

    drop constraint(:sal_reconciliation, "sal_reconciliation_created_by_id_fkey")

    drop_if_exists unique_index(:sal_reconciliation, [:reconciliation_no],
                     name: "sal_reconciliation_unique_reconciliation_no_index"
                   )

    alter table(:sal_reconciliation) do
      remove :created_by_id
      remove :credit_account_id
      remove :debit_account_id
      remove :company_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :remarks
      remove :posting_date
      remove :party_id
      remove :party_type
      remove :reconciliation_type
      remove :reconciliation_no
    end

    drop constraint(:acc_vat_invoice, "acc_vat_invoice_sal_reconciliation_id_fkey")

    alter table(:acc_vat_invoice) do
      modify :sal_reconciliation_id, :uuid
    end

    drop table(:sal_reconciliation)

    alter table(:acc_vat_invoice) do
      remove :sal_reconciliation_id
    end

    alter table(:sal_delivery_item) do
      remove :reconciled_qty
    end
  end
end
