defmodule SynieCore.Repo.Migrations.AddInvMaterial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inv_material_unit, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :factor, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id, :uuid, null: false
      add :unit_id, :uuid, null: false
    end

    create unique_index(:inv_material_unit, [:material_id, :unit_id],
             name: "inv_material_unit_unique_material_unit_index"
           )

    create table(:inv_material, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inv_material_unit) do
      modify :material_id,
             references(:inv_material,
               column: :id,
               name: "inv_material_unit_material_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :unit_id,
             references(:bas_unit,
               column: :id,
               name: "inv_material_unit_unit_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inv_material) do
      add :code, :text, null: false
      add :name, :text, null: false
      add :spec, :text
      add :customer_part_no, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id,
          references(:inv_material_category,
            column: :id,
            name: "inv_material_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :default_unit_id,
          references(:bas_unit,
            column: :id,
            name: "inv_material_default_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:inv_material, [:code], name: "inv_material_unique_code_index")
  end

  def down do
    drop constraint(:inv_material, "inv_material_category_id_fkey")

    drop constraint(:inv_material, "inv_material_default_unit_id_fkey")

    drop_if_exists unique_index(:inv_material, [:code], name: "inv_material_unique_code_index")

    alter table(:inv_material) do
      remove :default_unit_id
      remove :category_id
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :customer_part_no
      remove :spec
      remove :name
      remove :code
    end

    drop constraint(:inv_material_unit, "inv_material_unit_material_id_fkey")

    drop constraint(:inv_material_unit, "inv_material_unit_unit_id_fkey")

    alter table(:inv_material_unit) do
      modify :unit_id, :uuid
      modify :material_id, :uuid
    end

    drop table(:inv_material)

    drop_if_exists unique_index(:inv_material_unit, [:material_id, :unit_id],
                     name: "inv_material_unit_unique_material_unit_index"
                   )

    drop table(:inv_material_unit)
  end
end
