defmodule SynieCore.Repo.Migrations.OutsourcedReceipt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  委外入库单(ADR 2026-07-24,工单05):新建头/成品行/材料扣减行/副产物行四表
  (财务镜像采购入库;审核同事务三副作用——成品入仓＋外协仓材料扣减＋副产物入仓);
  `pur_reconciliation_item` 入库条目改双来源恰一(新增委外入库条目引用,
  采购对账条目池纳入委外加工费);随迁移种子 `purchase.outsourced_receipt`
  启用编号规则(见 `SynieCore.Purchase.OutsourcedReceiptNumberingSeed`)。
  """

  use Ecto.Migration

  def up do
    create table(:pur_outsourced_receipt_item_byproduct, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :base_qty, :decimal, null: false, default: "0"
      add :material_code, :text, null: false
      add :material_name, :text, null: false
      add :material_spec, :text
      add :unit_name, :text, null: false
      add :order_no, :text, null: false
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :receipt_item_id, :uuid, null: false
      add :company_id, :uuid, null: false
      add :order_item_byproduct_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :unit_id, :uuid, null: false
      add :warehouse_id, :uuid
    end

    alter table(:pur_reconciliation_item) do
      modify :receipt_item_id, :uuid, null: true
      add :outsourced_receipt_item_id, :uuid
    end

    create table(:pur_outsourced_receipt_item_material, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :base_qty, :decimal, null: false, default: "0"
      add :material_code, :text, null: false
      add :material_name, :text, null: false
      add :material_spec, :text
      add :unit_name, :text, null: false
      add :order_no, :text, null: false
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :receipt_item_id, :uuid, null: false
      add :company_id, :uuid, null: false
      add :order_item_material_id, :uuid, null: false
      add :material_id, :uuid, null: false
      add :unit_id, :uuid, null: false
      add :outsourced_warehouse_id, :uuid
    end

    create table(:pur_outsourced_receipt, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :receipt_no, :text, null: false
      add :receipt_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :posting_date, :date
      add :party_type, :text, null: false
      add :party_id, :uuid, null: false
      add :remarks, :text
      add :status, :text, null: false, default: "draft"
      add :audited_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "pur_outsourced_receipt_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "pur_outsourced_receipt_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :outsourced_warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "pur_outsourced_receipt_outsourced_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :debit_account_id,
          references(:bas_account,
            column: :id,
            name: "pur_outsourced_receipt_debit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :credit_account_id,
          references(:bas_account,
            column: :id,
            name: "pur_outsourced_receipt_credit_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "pur_outsourced_receipt_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :audited_by_id,
          references(:sys_user,
            column: :id,
            name: "pur_outsourced_receipt_audited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:pur_outsourced_receipt, [:receipt_no],
             name: "pur_outsourced_receipt_unique_receipt_no_index"
           )

    create table(:pur_outsourced_receipt_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:pur_outsourced_receipt_item_byproduct) do
      modify :receipt_item_id,
             references(:pur_outsourced_receipt_item,
               column: :id,
               name: "pur_outsourced_receipt_item_byproduct_receipt_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :company_id,
             references(:bas_company,
               column: :id,
               name: "pur_outsourced_receipt_item_byproduct_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :order_item_byproduct_id,
             references(:pur_order_item_byproduct,
               column: :id,
               name: "pur_outsourced_receipt_item_byproduct_order_item_byproduct_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )

      modify :material_id,
             references(:inv_material,
               column: :id,
               name: "pur_outsourced_receipt_item_byproduct_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :unit_id,
             references(:bas_unit,
               column: :id,
               name: "pur_outsourced_receipt_item_byproduct_unit_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :warehouse_id,
             references(:inv_warehouse,
               column: :id,
               name: "pur_outsourced_receipt_item_byproduct_warehouse_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pur_reconciliation_item) do
      modify :outsourced_receipt_item_id,
             references(:pur_outsourced_receipt_item,
               column: :id,
               name: "pur_reconciliation_item_outsourced_receipt_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )
    end

    alter table(:pur_outsourced_receipt_item_material) do
      modify :receipt_item_id,
             references(:pur_outsourced_receipt_item,
               column: :id,
               name: "pur_outsourced_receipt_item_material_receipt_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :company_id,
             references(:bas_company,
               column: :id,
               name: "pur_outsourced_receipt_item_material_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :order_item_material_id,
             references(:pur_order_item_material,
               column: :id,
               name: "pur_outsourced_receipt_item_material_order_item_material_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )

      modify :material_id,
             references(:inv_material,
               column: :id,
               name: "pur_outsourced_receipt_item_material_material_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :unit_id,
             references(:bas_unit,
               column: :id,
               name: "pur_outsourced_receipt_item_material_unit_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :outsourced_warehouse_id,
             references(:inv_warehouse,
               column: :id,
               name: "pur_outsourced_receipt_item_material_outsourced_warehouse_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pur_outsourced_receipt_item) do
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :base_qty, :decimal, null: false, default: "0"
      add :material_code, :text, null: false
      add :material_name, :text, null: false
      add :material_spec, :text
      add :customer_part_no, :text
      add :unit_name, :text, null: false
      add :order_no, :text, null: false
      add :order_qty, :decimal, null: false, default: "0"
      add :order_base_qty, :decimal, null: false, default: "0"
      add :order_unit_name, :text, null: false
      add :order_price, :decimal, null: false, default: "0"
      add :order_amount, :decimal, null: false, default: "0"
      add :order_base_price, :decimal, null: false, default: "0"
      add :order_base_amount, :decimal, null: false, default: "0"
      add :order_tax_rate, :decimal, null: false, default: "0"
      add :order_currency_code, :text, null: false
      add :reconciled_qty, :decimal, null: false, default: "0"
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :receipt_id,
          references(:pur_outsourced_receipt,
            column: :id,
            name: "pur_outsourced_receipt_item_receipt_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "pur_outsourced_receipt_item_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :order_item_id,
          references(:pur_order_item,
            column: :id,
            name: "pur_outsourced_receipt_item_order_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          ), null: false

      add :material_id,
          references(:inv_material,
            column: :id,
            name: "pur_outsourced_receipt_item_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :unit_id,
          references(:bas_unit,
            column: :id,
            name: "pur_outsourced_receipt_item_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :warehouse_id,
          references(:inv_warehouse,
            column: :id,
            name: "pur_outsourced_receipt_item_warehouse_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create constraint(:pur_outsourced_receipt_item, :qty_positive,
             check: """
               qty > 0
             """
           )

    create constraint(:pur_outsourced_receipt_item, :reconciled_qty_nonnegative,
             check: """
               reconciled_qty >= 0
             """
           )

    create constraint(:pur_outsourced_receipt, :party_pair,
             check: """
               (party_type IS NULL) = (party_id IS NULL)
             """
           )

    create constraint(:pur_outsourced_receipt_item_material, :qty_positive,
             check: """
               qty > 0
             """
           )

    create constraint(:pur_reconciliation_item, :receipt_item_exactly_one,
             check: """
               num_nonnulls(receipt_item_id, outsourced_receipt_item_id) = 1
             """
           )

    create constraint(:pur_outsourced_receipt_item_byproduct, :qty_positive,
             check: """
               qty > 0
             """
           )

    SynieCore.Purchase.OutsourcedReceiptNumberingSeed.run!()
  end

  def down do
    drop_if_exists constraint(:pur_outsourced_receipt_item_byproduct, :qty_positive)

    drop_if_exists constraint(:pur_reconciliation_item, :receipt_item_exactly_one)

    drop_if_exists constraint(:pur_outsourced_receipt_item_material, :qty_positive)

    drop_if_exists constraint(:pur_outsourced_receipt, :party_pair)

    drop_if_exists constraint(:pur_outsourced_receipt_item, :reconciled_qty_nonnegative)

    drop_if_exists constraint(:pur_outsourced_receipt_item, :qty_positive)

    drop constraint(:pur_outsourced_receipt_item, "pur_outsourced_receipt_item_receipt_id_fkey")

    drop constraint(:pur_outsourced_receipt_item, "pur_outsourced_receipt_item_company_id_fkey")

    drop constraint(
           :pur_outsourced_receipt_item,
           "pur_outsourced_receipt_item_order_item_id_fkey"
         )

    drop constraint(:pur_outsourced_receipt_item, "pur_outsourced_receipt_item_material_id_fkey")

    drop constraint(:pur_outsourced_receipt_item, "pur_outsourced_receipt_item_unit_id_fkey")

    drop constraint(:pur_outsourced_receipt_item, "pur_outsourced_receipt_item_warehouse_id_fkey")

    alter table(:pur_outsourced_receipt_item) do
      remove :warehouse_id
      remove :unit_id
      remove :material_id
      remove :order_item_id
      remove :company_id
      remove :receipt_id
      remove :updated_at
      remove :inserted_at
      remove :remarks
      remove :reconciled_qty
      remove :order_currency_code
      remove :order_tax_rate
      remove :order_base_amount
      remove :order_base_price
      remove :order_amount
      remove :order_price
      remove :order_unit_name
      remove :order_base_qty
      remove :order_qty
      remove :order_no
      remove :unit_name
      remove :customer_part_no
      remove :material_spec
      remove :material_name
      remove :material_code
      remove :base_qty
      remove :qty
      remove :idx
    end

    drop constraint(
           :pur_outsourced_receipt_item_material,
           "pur_outsourced_receipt_item_material_receipt_item_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_material,
           "pur_outsourced_receipt_item_material_company_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_material,
           "pur_outsourced_receipt_item_material_order_item_material_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_material,
           "pur_outsourced_receipt_item_material_material_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_material,
           "pur_outsourced_receipt_item_material_unit_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_material,
           "pur_outsourced_receipt_item_material_outsourced_warehouse_id_fkey"
         )

    alter table(:pur_outsourced_receipt_item_material) do
      modify :outsourced_warehouse_id, :uuid
      modify :unit_id, :uuid
      modify :material_id, :uuid
      modify :order_item_material_id, :uuid
      modify :company_id, :uuid
      modify :receipt_item_id, :uuid
    end

    drop constraint(
           :pur_reconciliation_item,
           "pur_reconciliation_item_outsourced_receipt_item_id_fkey"
         )

    alter table(:pur_reconciliation_item) do
      modify :outsourced_receipt_item_id, :uuid
    end

    drop constraint(
           :pur_outsourced_receipt_item_byproduct,
           "pur_outsourced_receipt_item_byproduct_receipt_item_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_byproduct,
           "pur_outsourced_receipt_item_byproduct_company_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_byproduct,
           "pur_outsourced_receipt_item_byproduct_order_item_byproduct_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_byproduct,
           "pur_outsourced_receipt_item_byproduct_material_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_byproduct,
           "pur_outsourced_receipt_item_byproduct_unit_id_fkey"
         )

    drop constraint(
           :pur_outsourced_receipt_item_byproduct,
           "pur_outsourced_receipt_item_byproduct_warehouse_id_fkey"
         )

    alter table(:pur_outsourced_receipt_item_byproduct) do
      modify :warehouse_id, :uuid
      modify :unit_id, :uuid
      modify :material_id, :uuid
      modify :order_item_byproduct_id, :uuid
      modify :company_id, :uuid
      modify :receipt_item_id, :uuid
    end

    drop table(:pur_outsourced_receipt_item)

    drop constraint(:pur_outsourced_receipt, "pur_outsourced_receipt_company_id_fkey")

    drop constraint(:pur_outsourced_receipt, "pur_outsourced_receipt_warehouse_id_fkey")

    drop constraint(
           :pur_outsourced_receipt,
           "pur_outsourced_receipt_outsourced_warehouse_id_fkey"
         )

    drop constraint(:pur_outsourced_receipt, "pur_outsourced_receipt_debit_account_id_fkey")

    drop constraint(:pur_outsourced_receipt, "pur_outsourced_receipt_credit_account_id_fkey")

    drop constraint(:pur_outsourced_receipt, "pur_outsourced_receipt_created_by_id_fkey")

    drop constraint(:pur_outsourced_receipt, "pur_outsourced_receipt_audited_by_id_fkey")

    drop_if_exists unique_index(:pur_outsourced_receipt, [:receipt_no],
                     name: "pur_outsourced_receipt_unique_receipt_no_index"
                   )

    drop table(:pur_outsourced_receipt)

    drop table(:pur_outsourced_receipt_item_material)

    alter table(:pur_reconciliation_item) do
      remove :outsourced_receipt_item_id
      modify :receipt_item_id, :uuid, null: false
    end

    drop table(:pur_outsourced_receipt_item_byproduct)
  end
end
