defmodule SynieCore.Repo.Migrations.AddAccBankAccount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acc_bank_account, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :alias, :text, null: false
      add :bank_name, :text, null: false
      add :branch_name, :text
      add :holder_name, :text, null: false
      add :account_no, :text, null: false
      add :active, :boolean, null: false, default: true
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "acc_bank_account_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :currency_id,
          references(:bas_currency,
            column: :id,
            name: "acc_bank_account_currency_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :account_id,
          references(:bas_account,
            column: :id,
            name: "acc_bank_account_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:acc_bank_account, [:company_id, :account_no],
             name: "acc_bank_account_unique_account_no_per_company_index"
           )

    create unique_index(:acc_bank_account, [:company_id, :alias],
             name: "acc_bank_account_unique_alias_per_company_index"
           )
  end

  def down do
    drop constraint(:acc_bank_account, "acc_bank_account_company_id_fkey")

    drop constraint(:acc_bank_account, "acc_bank_account_currency_id_fkey")

    drop constraint(:acc_bank_account, "acc_bank_account_account_id_fkey")

    drop_if_exists unique_index(:acc_bank_account, [:company_id, :alias],
                     name: "acc_bank_account_unique_alias_per_company_index"
                   )

    drop_if_exists unique_index(:acc_bank_account, [:company_id, :account_no],
                     name: "acc_bank_account_unique_account_no_per_company_index"
                   )

    drop table(:acc_bank_account)
  end
end
