defmodule SynieCore.Repo.Migrations.BankTxnReconcileColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acc_bank_transaction) do
      add :reconciled_amount, :decimal, null: false, default: "0"
      add :unreconciled_amount, :decimal, null: false, default: "0"
      add :reconcile_status, :text, null: false, default: "unreconciled"
    end

    execute("UPDATE acc_bank_transaction SET unreconciled_amount = COALESCE(income, expense)")
  end

  def down do
    alter table(:acc_bank_transaction) do
      remove :reconcile_status
      remove :unreconciled_amount
      remove :reconciled_amount
    end
  end
end
