defmodule SynieCore.Repo.Migrations.AddAccBillHolding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acc_bill_holding, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bill_no, :text, null: false
      add :sub_start, :bigint, null: false
      add :sub_end, :bigint, null: false
      add :amount, :decimal, null: false
      add :due_date, :date, null: false
      add :acquired_on, :date, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "acc_bill_holding_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :bank_account_id,
          references(:acc_bank_account,
            column: :id,
            name: "acc_bill_holding_bank_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :bill_id,
          references(:acc_bill,
            column: :id,
            name: "acc_bill_holding_bill_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_transaction_id,
          references(:acc_bill_transaction,
            column: :id,
            name: "acc_bill_holding_source_transaction_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:acc_bill_holding, [:company_id, :due_date])

    create index(:acc_bill_holding, [:company_id, :bank_account_id])

    create index(:acc_bill_holding, [:bill_id])
  end

  def down do
    drop constraint(:acc_bill_holding, "acc_bill_holding_company_id_fkey")

    drop constraint(:acc_bill_holding, "acc_bill_holding_bank_account_id_fkey")

    drop constraint(:acc_bill_holding, "acc_bill_holding_bill_id_fkey")

    drop constraint(:acc_bill_holding, "acc_bill_holding_source_transaction_id_fkey")

    drop_if_exists index(:acc_bill_holding, [:bill_id])

    drop_if_exists index(:acc_bill_holding, [:company_id, :bank_account_id])

    drop_if_exists index(:acc_bill_holding, [:company_id, :due_date])

    drop table(:acc_bill_holding)
  end
end
