defmodule SynieCore.Repo.Migrations.BomMultiPerMaterial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  放开 BOM 一物料多张(ADR 2026-07-24):去掉「以物料为唯一键」的唯一索引,
  新增独立编号(全局唯一)与可空方案名称;既有 BOM 数据由
  `SynieCore.Mfg.BomNumberingBackfill` 兜底补编号,并随迁移种子 BOM 编号规则
  (规则/计数器一并就位,老环境免手工配置)。
  """

  use Ecto.Migration

  def up do
    alter table(:mfg_bom) do
      # 先可空:存量行补编号后再 SET NOT NULL
      add :code, :text
      add :plan_name, :text
    end

    drop_if_exists unique_index(:mfg_bom, [:material_id], name: "mfg_bom_unique_material_index")

    # 落冲排队的 DDL(新列就位),补编号走应用 Repo 直查,不经迁移执行器队列
    flush()

    # 种子 mfg.bom 编号规则 + 存量补编号 + 计数器垫到已用最大序号(幂等)
    SynieCore.Mfg.BomNumberingBackfill.run!()

    execute(
      "ALTER TABLE mfg_bom ALTER COLUMN code SET NOT NULL",
      "ALTER TABLE mfg_bom ALTER COLUMN code DROP NOT NULL"
    )

    create unique_index(:mfg_bom, [:code], name: "mfg_bom_unique_code_index")
  end

  def down do
    drop_if_exists unique_index(:mfg_bom, [:code], name: "mfg_bom_unique_code_index")

    create unique_index(:mfg_bom, [:material_id], name: "mfg_bom_unique_material_index")

    alter table(:mfg_bom) do
      remove :plan_name
      remove :code
    end

    # 回滚即撤销本功能:连带删掉随迁移种子的 BOM 编号规则(计数器外键级联随删)
    execute("DELETE FROM sys_numbering_rule WHERE resource = 'mfg.bom'", "")
  end
end
