defmodule SynieCore.Repo.Migrations.WarehouseOutsourcedParty do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inv_warehouse) do
      add :party_type, :text
      add :party_id, :uuid
    end

    create constraint(:inv_warehouse, :party_pair,
             check: """
               (party_type IS NULL) = (party_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:inv_warehouse, :party_pair)

    alter table(:inv_warehouse) do
      remove :party_id
      remove :party_type
    end
  end
end
