defmodule SynieCore.Repo.Migrations.AddAccGlJournal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acc_gl_journal, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :voucher_no, :text, null: false
      add :date, :date, null: false
      add :posting_date, :date, null: false
      add :remarks, :text
      add :status, :text, null: false, default: "draft"
      add :submitted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "acc_gl_journal_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "acc_gl_journal_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :submitted_by_id,
          references(:sys_user,
            column: :id,
            name: "acc_gl_journal_submitted_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:acc_gl_journal, [:company_id, :voucher_no],
             name: "acc_gl_journal_unique_voucher_no_per_company_index"
           )
  end

  def down do
    drop constraint(:acc_gl_journal, "acc_gl_journal_company_id_fkey")

    drop constraint(:acc_gl_journal, "acc_gl_journal_created_by_id_fkey")

    drop constraint(:acc_gl_journal, "acc_gl_journal_submitted_by_id_fkey")

    drop_if_exists unique_index(:acc_gl_journal, [:company_id, :voucher_no],
                     name: "acc_gl_journal_unique_voucher_no_per_company_index"
                   )

    drop table(:acc_gl_journal)
  end
end
