defmodule SynieCore.Repo.Migrations.AddSalOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sal_order, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :order_no, :text, null: false
      add :order_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :party_type, :text, null: false
      add :party_id, :uuid, null: false
      add :terms, :text
      add :remarks, :text
      add :status, :text, null: false, default: "draft"
      add :audited_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "sal_order_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:sys_user,
            column: :id,
            name: "sal_order_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :audited_by_id,
          references(:sys_user,
            column: :id,
            name: "sal_order_audited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:sal_order, [:order_no], name: "sal_order_unique_order_no_index")

    create table(:sal_order_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idx, :bigint, null: false
      add :qty, :decimal, null: false
      add :price, :decimal, null: false
      add :amount, :decimal, null: false, default: "0"
      add :tax_rate, :decimal, null: false, default: "0.13"
      add :remarks, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:sal_order,
            column: :id,
            name: "sal_order_item_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "sal_order_item_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :material_id,
          references(:inv_material,
            column: :id,
            name: "sal_order_item_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :unit_id,
          references(:bas_unit,
            column: :id,
            name: "sal_order_item_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create constraint(:sal_order_item, :qty_positive,
             check: """
               qty > 0
             """
           )

    create constraint(:sal_order_item, :price_nonnegative,
             check: """
               price >= 0
             """
           )

    create constraint(:sal_order_item, :tax_rate_range,
             check: """
               tax_rate >= 0 AND tax_rate < 1
             """
           )

    create constraint(:sal_order, :party_pair,
             check: """
               (party_type IS NULL) = (party_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:sal_order, :party_pair)

    drop_if_exists constraint(:sal_order_item, :tax_rate_range)

    drop_if_exists constraint(:sal_order_item, :price_nonnegative)

    drop_if_exists constraint(:sal_order_item, :qty_positive)

    drop constraint(:sal_order_item, "sal_order_item_order_id_fkey")

    drop constraint(:sal_order_item, "sal_order_item_company_id_fkey")

    drop constraint(:sal_order_item, "sal_order_item_material_id_fkey")

    drop constraint(:sal_order_item, "sal_order_item_unit_id_fkey")

    drop table(:sal_order_item)

    drop constraint(:sal_order, "sal_order_company_id_fkey")

    drop constraint(:sal_order, "sal_order_created_by_id_fkey")

    drop constraint(:sal_order, "sal_order_audited_by_id_fkey")

    drop_if_exists unique_index(:sal_order, [:order_no], name: "sal_order_unique_order_no_index")

    drop table(:sal_order)
  end
end
