defmodule SynieCore.Repo.Migrations.AddCustomersSuppliers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sal_customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :name, :text, null: false
      add :short_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:sal_customers, [:code], name: "sal_customers_unique_code_index")

    create table(:pur_supplier, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :name, :text, null: false
      add :short_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:pur_supplier, [:code], name: "pur_supplier_unique_code_index")
  end

  def down do
    drop_if_exists unique_index(:pur_supplier, [:code], name: "pur_supplier_unique_code_index")

    drop table(:pur_supplier)

    drop_if_exists unique_index(:sal_customers, [:code], name: "sal_customers_unique_code_index")

    drop table(:sal_customers)
  end
end
