defmodule SynieCore.Repo.Migrations.AddAccBankImportTemplate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acc_bank_import_template, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :start_row, :bigint, null: false, default: 2
      add :datetime_col, :text
      add :datetime_format, :text
      add :date_col, :text
      add :date_format, :text
      add :time_col, :text
      add :time_format, :text
      add :income_col, :text
      add :expense_col, :text
      add :amount_col, :text
      add :balance_col, :text
      add :counterparty_name_col, :text
      add :counterparty_account_col, :text
      add :summary_col, :text
      add :note_col, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:bas_company,
            column: :id,
            name: "acc_bank_import_template_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :bank_account_id,
          references(:acc_bank_account,
            column: :id,
            name: "acc_bank_import_template_bank_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:acc_bank_import_template, [:company_id, :name],
             name: "acc_bank_import_template_unique_name_per_company_index"
           )
  end

  def down do
    drop constraint(:acc_bank_import_template, "acc_bank_import_template_company_id_fkey")

    drop constraint(:acc_bank_import_template, "acc_bank_import_template_bank_account_id_fkey")

    drop_if_exists unique_index(:acc_bank_import_template, [:company_id, :name],
                     name: "acc_bank_import_template_unique_name_per_company_index"
                   )

    drop table(:acc_bank_import_template)
  end
end
