import documents from '../convex/catalog/generatedDocuments.json'
import { AGGREGATE_HEADS, PARENT_FIELDS, storeForResource } from '../convex/domains/shared/policies'
import { domainEqualityFields, domainSortFields } from '../convex/domains/shared/queryProfiles'

type Document = { capabilities: string[]; commands: Array<{ key: string; target: 'row' | 'collection' }> }

function gateway(resource: string): string | null {
  if (!storeForResource(resource)) return null
  if (resource.startsWith('accGl')) return 'accounting'
  if (resource.startsWith('invStock')) return 'inventory'
  if (resource.startsWith('salQuotation') || resource.startsWith('purQuotation')) return 'quotations'
  if (resource.startsWith('salOrder') || resource.startsWith('purOrder')) return 'orders'
  if (resource.startsWith('salDeliver') || resource.startsWith('purReceipt') || resource.startsWith('purOutsourced')) return 'fulfillment'
  if (resource.startsWith('salReconciliation') || resource.startsWith('purReconciliation') || resource.startsWith('scmOrderFlow')) return 'reconciliation'
  if (resource.startsWith('acc')) return 'finance'
  if (resource.startsWith('mfg')) return 'manufacturing'
  if (resource.startsWith('hr')) return 'hr'
  if (resource.startsWith('basMarket')) return 'market'
  return null
}

function draftGateway(resource: string): string | null {
  if (!AGGREGATE_HEADS.has(resource)) return null
  if (resource === 'accGlJournals') return 'accounting'
  if (resource.startsWith('invStock')) return 'inventory'
  if (['purOrders', 'purQuotations', 'purReceipts', 'salDeliveries', 'salOrders', 'salQuotations'].includes(resource)) return 'trading'
  if (resource.startsWith('purOutsourced')) return 'fulfillment'
  if (resource.endsWith('Reconciliations')) return 'reconciliation'
  if (resource === 'accExpenseReports') return 'finance'
  if (resource.startsWith('mfg')) return 'manufacturing'
  throw new Error(`聚合 ${resource} 缺少 draft gateway`)
}

const manifest = Object.fromEntries(
  Object.entries(documents as Record<string, Document>)
    .map(([resource, document]) => [resource, {
      gateway: gateway(resource),
      capabilities: document.capabilities,
      commands: document.commands.map((command) => command.key),
      commandTargets: Object.fromEntries(document.commands.map((command) => [command.key, command.target])),
      parentField: PARENT_FIELDS[resource] ?? null,
      sortFields: domainSortFields(resource),
      equalityFields: domainEqualityFields(resource),
      aggregate: AGGREGATE_HEADS.has(resource),
      draftGateway: draftGateway(resource),
    }])
    .filter(([, value]) => value.gateway !== null),
)

const output = `/* Generated by scripts/generate-convex-web-manifest.ts; do not edit. */\n` +
  `export const CONVEX_DOMAIN_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const\n` +
  `export type ConvexDomainResource = keyof typeof CONVEX_DOMAIN_MANIFEST\n`

await Bun.write(new URL('../web/app/lib/resources/convex-domain-manifest.ts', import.meta.url), output)
