// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountCountByCompany = `-- name: AccountCountByCompany :one
SELECT count(*) FROM bas_account WHERE company_id = $1
`

func (q *Queries) AccountCountByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, accountCountByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const accountCurrencyISOCode = `-- name: AccountCurrencyISOCode :one
SELECT iso_code FROM bas_currency WHERE id = $1
`

func (q *Queries) AccountCurrencyISOCode(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, accountCurrencyISOCode, id)
	var iso_code string
	err := row.Scan(&iso_code)
	return iso_code, err
}

const accountHasChildren = `-- name: AccountHasChildren :one
SELECT EXISTS(SELECT 1 FROM bas_account WHERE parent_id = $1)
`

func (q *Queries) AccountHasChildren(ctx context.Context, parentID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, accountHasChildren, parentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountParentCompany = `-- name: AccountParentCompany :one
SELECT company_id FROM bas_account WHERE id = $1
`

func (q *Queries) AccountParentCompany(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, accountParentCompany, id)
	var company_id uuid.UUID
	err := row.Scan(&company_id)
	return company_id, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO bas_account (
  code, name, direction, is_group, active, role, parent_id, company_id, currency_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, name, direction, is_group, active, role,
          parent_id, company_id, currency_id, inserted_at, updated_at
`

type CreateAccountParams struct {
	Code       string      `db:"code" json:"code"`
	Name       string      `db:"name" json:"name"`
	Direction  string      `db:"direction" json:"direction"`
	IsGroup    bool        `db:"is_group" json:"is_group"`
	Active     bool        `db:"active" json:"active"`
	Role       pgtype.Text `db:"role" json:"role"`
	ParentID   *uuid.UUID  `db:"parent_id" json:"parent_id"`
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	CurrencyID *uuid.UUID  `db:"currency_id" json:"currency_id"`
}

type CreateAccountRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Code       string           `db:"code" json:"code"`
	Name       string           `db:"name" json:"name"`
	Direction  string           `db:"direction" json:"direction"`
	IsGroup    bool             `db:"is_group" json:"is_group"`
	Active     bool             `db:"active" json:"active"`
	Role       pgtype.Text      `db:"role" json:"role"`
	ParentID   *uuid.UUID       `db:"parent_id" json:"parent_id"`
	CompanyID  uuid.UUID        `db:"company_id" json:"company_id"`
	CurrencyID *uuid.UUID       `db:"currency_id" json:"currency_id"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Code,
		arg.Name,
		arg.Direction,
		arg.IsGroup,
		arg.Active,
		arg.Role,
		arg.ParentID,
		arg.CompanyID,
		arg.CurrencyID,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.IsGroup,
		&i.Active,
		&i.Role,
		&i.ParentID,
		&i.CompanyID,
		&i.CurrencyID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM bas_account WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT a.id, a.code, a.name, a.direction, a.is_group, a.active, a.role,
       a.parent_id, a.company_id, a.currency_id, a.inserted_at, a.updated_at,
       p.name AS parent_name, company.name AS company_name, currency.name AS currency_name,
       EXISTS(SELECT 1 FROM bas_account child WHERE child.parent_id = a.id) AS has_children
FROM bas_account AS a
LEFT JOIN bas_account AS p ON p.id = a.parent_id
JOIN bas_company AS company ON company.id = a.company_id
LEFT JOIN bas_currency AS currency ON currency.id = a.currency_id
WHERE a.id = $1
`

type GetAccountRow struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	Code         string           `db:"code" json:"code"`
	Name         string           `db:"name" json:"name"`
	Direction    string           `db:"direction" json:"direction"`
	IsGroup      bool             `db:"is_group" json:"is_group"`
	Active       bool             `db:"active" json:"active"`
	Role         pgtype.Text      `db:"role" json:"role"`
	ParentID     *uuid.UUID       `db:"parent_id" json:"parent_id"`
	CompanyID    uuid.UUID        `db:"company_id" json:"company_id"`
	CurrencyID   *uuid.UUID       `db:"currency_id" json:"currency_id"`
	InsertedAt   pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ParentName   pgtype.Text      `db:"parent_name" json:"parent_name"`
	CompanyName  string           `db:"company_name" json:"company_name"`
	CurrencyName pgtype.Text      `db:"currency_name" json:"currency_name"`
	HasChildren  bool             `db:"has_children" json:"has_children"`
}

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.IsGroup,
		&i.Active,
		&i.Role,
		&i.ParentID,
		&i.CompanyID,
		&i.CurrencyID,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ParentName,
		&i.CompanyName,
		&i.CurrencyName,
		&i.HasChildren,
	)
	return i, err
}

const lockAccount = `-- name: LockAccount :one
SELECT id, code, name, direction, is_group, active, role,
       parent_id, company_id, currency_id, inserted_at, updated_at
FROM bas_account
WHERE id = $1
FOR UPDATE
`

type LockAccountRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Code       string           `db:"code" json:"code"`
	Name       string           `db:"name" json:"name"`
	Direction  string           `db:"direction" json:"direction"`
	IsGroup    bool             `db:"is_group" json:"is_group"`
	Active     bool             `db:"active" json:"active"`
	Role       pgtype.Text      `db:"role" json:"role"`
	ParentID   *uuid.UUID       `db:"parent_id" json:"parent_id"`
	CompanyID  uuid.UUID        `db:"company_id" json:"company_id"`
	CurrencyID *uuid.UUID       `db:"currency_id" json:"currency_id"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockAccount(ctx context.Context, id uuid.UUID) (LockAccountRow, error) {
	row := q.db.QueryRow(ctx, lockAccount, id)
	var i LockAccountRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.IsGroup,
		&i.Active,
		&i.Role,
		&i.ParentID,
		&i.CompanyID,
		&i.CurrencyID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE bas_account
SET name = $2, direction = $3, is_group = $4, active = $5, role = $6,
    parent_id = $7, currency_id = $8, updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, code, name, direction, is_group, active, role,
          parent_id, company_id, currency_id, inserted_at, updated_at
`

type UpdateAccountParams struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	Name       string      `db:"name" json:"name"`
	Direction  string      `db:"direction" json:"direction"`
	IsGroup    bool        `db:"is_group" json:"is_group"`
	Active     bool        `db:"active" json:"active"`
	Role       pgtype.Text `db:"role" json:"role"`
	ParentID   *uuid.UUID  `db:"parent_id" json:"parent_id"`
	CurrencyID *uuid.UUID  `db:"currency_id" json:"currency_id"`
}

type UpdateAccountRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Code       string           `db:"code" json:"code"`
	Name       string           `db:"name" json:"name"`
	Direction  string           `db:"direction" json:"direction"`
	IsGroup    bool             `db:"is_group" json:"is_group"`
	Active     bool             `db:"active" json:"active"`
	Role       pgtype.Text      `db:"role" json:"role"`
	ParentID   *uuid.UUID       `db:"parent_id" json:"parent_id"`
	CompanyID  uuid.UUID        `db:"company_id" json:"company_id"`
	CurrencyID *uuid.UUID       `db:"currency_id" json:"currency_id"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Direction,
		arg.IsGroup,
		arg.Active,
		arg.Role,
		arg.ParentID,
		arg.CurrencyID,
	)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.IsGroup,
		&i.Active,
		&i.Role,
		&i.ParentID,
		&i.CompanyID,
		&i.CurrencyID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
