// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO sys_attachment
  (file_id, owner_type, owner_id, category, company_id)
VALUES
  ($1, $2, $3, $4, $5)
RETURNING id, file_id, owner_type, owner_id, category, company_id, inserted_at
`

type CreateAttachmentParams struct {
	FileID    uuid.UUID  `db:"file_id" json:"file_id"`
	OwnerType string     `db:"owner_type" json:"owner_type"`
	OwnerID   uuid.UUID  `db:"owner_id" json:"owner_id"`
	Category  string     `db:"category" json:"category"`
	CompanyID *uuid.UUID `db:"company_id" json:"company_id"`
}

type CreateAttachmentRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	FileID     uuid.UUID        `db:"file_id" json:"file_id"`
	OwnerType  string           `db:"owner_type" json:"owner_type"`
	OwnerID    uuid.UUID        `db:"owner_id" json:"owner_id"`
	Category   string           `db:"category" json:"category"`
	CompanyID  *uuid.UUID       `db:"company_id" json:"company_id"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.FileID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Category,
		arg.CompanyID,
	)
	var i CreateAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Category,
		&i.CompanyID,
		&i.InsertedAt,
	)
	return i, err
}

const createStorageEndpoint = `-- name: CreateStorageEndpoint :one
INSERT INTO sys_storage
  (name, label, kind, root, endpoint, region, bucket, prefix, access_key_id, secret_access_key)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, label, kind, root, endpoint, region, bucket, prefix,
          access_key_id, secret_access_key, builtin, is_default, inserted_at, updated_at
`

type CreateStorageEndpointParams struct {
	Name            string      `db:"name" json:"name"`
	Label           string      `db:"label" json:"label"`
	Kind            string      `db:"kind" json:"kind"`
	Root            pgtype.Text `db:"root" json:"root"`
	Endpoint        pgtype.Text `db:"endpoint" json:"endpoint"`
	Region          pgtype.Text `db:"region" json:"region"`
	Bucket          pgtype.Text `db:"bucket" json:"bucket"`
	Prefix          pgtype.Text `db:"prefix" json:"prefix"`
	AccessKeyID     pgtype.Text `db:"access_key_id" json:"access_key_id"`
	SecretAccessKey pgtype.Text `db:"secret_access_key" json:"secret_access_key"`
}

func (q *Queries) CreateStorageEndpoint(ctx context.Context, arg CreateStorageEndpointParams) (SysStorage, error) {
	row := q.db.QueryRow(ctx, createStorageEndpoint,
		arg.Name,
		arg.Label,
		arg.Kind,
		arg.Root,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.Prefix,
		arg.AccessKeyID,
		arg.SecretAccessKey,
	)
	var i SysStorage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Kind,
		&i.Root,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.Builtin,
		&i.IsDefault,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStoredFile = `-- name: CreateStoredFile :one
INSERT INTO sys_file
  (storage, key, filename, content_type, size, sha256, uploaded_by_id)
VALUES
  ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, storage, key, filename, content_type, size, sha256, inserted_at, uploaded_by_id
`

type CreateStoredFileParams struct {
	Storage      string      `db:"storage" json:"storage"`
	Key          string      `db:"key" json:"key"`
	Filename     string      `db:"filename" json:"filename"`
	ContentType  pgtype.Text `db:"content_type" json:"content_type"`
	Size         pgtype.Int8 `db:"size" json:"size"`
	Sha256       pgtype.Text `db:"sha256" json:"sha256"`
	UploadedByID *uuid.UUID  `db:"uploaded_by_id" json:"uploaded_by_id"`
}

func (q *Queries) CreateStoredFile(ctx context.Context, arg CreateStoredFileParams) (SysFile, error) {
	row := q.db.QueryRow(ctx, createStoredFile,
		arg.Storage,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.Sha256,
		arg.UploadedByID,
	)
	var i SysFile
	err := row.Scan(
		&i.ID,
		&i.Storage,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.InsertedAt,
		&i.UploadedByID,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM sys_attachment WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStorageEndpoint = `-- name: DeleteStorageEndpoint :execrows
DELETE FROM sys_storage WHERE id = $1
`

func (q *Queries) DeleteStorageEndpoint(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStorageEndpoint, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStoredFile = `-- name: DeleteStoredFile :execrows
DELETE FROM sys_file WHERE id = $1
`

func (q *Queries) DeleteStoredFile(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStoredFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, file_id, owner_type, owner_id, category, company_id, inserted_at
FROM sys_attachment
WHERE id = $1
`

type GetAttachmentRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	FileID     uuid.UUID        `db:"file_id" json:"file_id"`
	OwnerType  string           `db:"owner_type" json:"owner_type"`
	OwnerID    uuid.UUID        `db:"owner_id" json:"owner_id"`
	Category   string           `db:"category" json:"category"`
	CompanyID  *uuid.UUID       `db:"company_id" json:"company_id"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
}

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Category,
		&i.CompanyID,
		&i.InsertedAt,
	)
	return i, err
}

const getStorageEndpoint = `-- name: GetStorageEndpoint :one
SELECT id, name, label, kind, root, endpoint, region, bucket, prefix,
       access_key_id, secret_access_key, builtin, is_default, inserted_at, updated_at
FROM sys_storage
WHERE id = $1
`

func (q *Queries) GetStorageEndpoint(ctx context.Context, id uuid.UUID) (SysStorage, error) {
	row := q.db.QueryRow(ctx, getStorageEndpoint, id)
	var i SysStorage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Kind,
		&i.Root,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.Builtin,
		&i.IsDefault,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoredFile = `-- name: GetStoredFile :one
SELECT id, storage, key, filename, content_type, size, sha256, inserted_at, uploaded_by_id
FROM sys_file
WHERE id = $1
`

func (q *Queries) GetStoredFile(ctx context.Context, id uuid.UUID) (SysFile, error) {
	row := q.db.QueryRow(ctx, getStoredFile, id)
	var i SysFile
	err := row.Scan(
		&i.ID,
		&i.Storage,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.InsertedAt,
		&i.UploadedByID,
	)
	return i, err
}

const lockStorageEndpoint = `-- name: LockStorageEndpoint :one
SELECT id, name, label, kind, root, endpoint, region, bucket, prefix,
       access_key_id, secret_access_key, builtin, is_default, inserted_at, updated_at
FROM sys_storage
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockStorageEndpoint(ctx context.Context, id uuid.UUID) (SysStorage, error) {
	row := q.db.QueryRow(ctx, lockStorageEndpoint, id)
	var i SysStorage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Kind,
		&i.Root,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.Builtin,
		&i.IsDefault,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockStoredFile = `-- name: LockStoredFile :one
SELECT id, storage, key, filename, content_type, size, sha256, inserted_at, uploaded_by_id
FROM sys_file
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockStoredFile(ctx context.Context, id uuid.UUID) (SysFile, error) {
	row := q.db.QueryRow(ctx, lockStoredFile, id)
	var i SysFile
	err := row.Scan(
		&i.ID,
		&i.Storage,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.InsertedAt,
		&i.UploadedByID,
	)
	return i, err
}

const updateStorageEndpoint = `-- name: UpdateStorageEndpoint :one
UPDATE sys_storage
SET label = $2,
    root = $3,
    endpoint = $4,
    region = $5,
    bucket = $6,
    prefix = $7,
    access_key_id = $8,
    secret_access_key = $9,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, name, label, kind, root, endpoint, region, bucket, prefix,
          access_key_id, secret_access_key, builtin, is_default, inserted_at, updated_at
`

type UpdateStorageEndpointParams struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	Label           string      `db:"label" json:"label"`
	Root            pgtype.Text `db:"root" json:"root"`
	Endpoint        pgtype.Text `db:"endpoint" json:"endpoint"`
	Region          pgtype.Text `db:"region" json:"region"`
	Bucket          pgtype.Text `db:"bucket" json:"bucket"`
	Prefix          pgtype.Text `db:"prefix" json:"prefix"`
	AccessKeyID     pgtype.Text `db:"access_key_id" json:"access_key_id"`
	SecretAccessKey pgtype.Text `db:"secret_access_key" json:"secret_access_key"`
}

func (q *Queries) UpdateStorageEndpoint(ctx context.Context, arg UpdateStorageEndpointParams) (SysStorage, error) {
	row := q.db.QueryRow(ctx, updateStorageEndpoint,
		arg.ID,
		arg.Label,
		arg.Root,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.Prefix,
		arg.AccessKeyID,
		arg.SecretAccessKey,
	)
	var i SysStorage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Kind,
		&i.Root,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Prefix,
		&i.AccessKeyID,
		&i.SecretAccessKey,
		&i.Builtin,
		&i.IsDefault,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
