// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_banking.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const financeBankingCreateReconciliation = `-- name: FinanceBankingCreateReconciliation :one
INSERT INTO acc_bank_reconciliation (
  id, amount, company_id, bank_transaction_id, journal_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, amount, inserted_at, updated_at, company_id,
          bank_transaction_id, journal_id
`

type FinanceBankingCreateReconciliationParams struct {
	ID                uuid.UUID       `db:"id" json:"id"`
	Amount            decimal.Decimal `db:"amount" json:"amount"`
	CompanyID         uuid.UUID       `db:"company_id" json:"company_id"`
	BankTransactionID uuid.UUID       `db:"bank_transaction_id" json:"bank_transaction_id"`
	JournalID         uuid.UUID       `db:"journal_id" json:"journal_id"`
}

func (q *Queries) FinanceBankingCreateReconciliation(ctx context.Context, arg FinanceBankingCreateReconciliationParams) (AccBankReconciliation, error) {
	row := q.db.QueryRow(ctx, financeBankingCreateReconciliation,
		arg.ID,
		arg.Amount,
		arg.CompanyID,
		arg.BankTransactionID,
		arg.JournalID,
	)
	var i AccBankReconciliation
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.BankTransactionID,
		&i.JournalID,
	)
	return i, err
}

const financeBankingDeleteReconciliation = `-- name: FinanceBankingDeleteReconciliation :execrows
DELETE FROM acc_bank_reconciliation WHERE id=$1
`

func (q *Queries) FinanceBankingDeleteReconciliation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, financeBankingDeleteReconciliation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const financeBankingDuplicateImportSHA = `-- name: FinanceBankingDuplicateImportSHA :one
SELECT EXISTS(
  SELECT 1
  FROM acc_bank_import i
  JOIN sys_file f ON f.id=i.file_id
  WHERE i.bank_account_id=$1 AND i.status<>'failed' AND f.sha256=$2
)::boolean
`

type FinanceBankingDuplicateImportSHAParams struct {
	BankAccountID uuid.UUID   `db:"bank_account_id" json:"bank_account_id"`
	Sha256        pgtype.Text `db:"sha256" json:"sha256"`
}

func (q *Queries) FinanceBankingDuplicateImportSHA(ctx context.Context, arg FinanceBankingDuplicateImportSHAParams) (bool, error) {
	row := q.db.QueryRow(ctx, financeBankingDuplicateImportSHA, arg.BankAccountID, arg.Sha256)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const financeBankingJournalCreditTotal = `-- name: FinanceBankingJournalCreditTotal :one
SELECT COALESCE(sum(credit), 0)::numeric
FROM acc_gl_journal_line
WHERE journal_id=$1 AND account_id=$2
`

type FinanceBankingJournalCreditTotalParams struct {
	JournalID uuid.UUID `db:"journal_id" json:"journal_id"`
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
}

func (q *Queries) FinanceBankingJournalCreditTotal(ctx context.Context, arg FinanceBankingJournalCreditTotalParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, financeBankingJournalCreditTotal, arg.JournalID, arg.AccountID)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const financeBankingJournalCreditUsed = `-- name: FinanceBankingJournalCreditUsed :one
SELECT COALESCE(sum(r.amount), 0)::numeric
FROM acc_bank_reconciliation r
JOIN acc_bank_transaction t ON t.id=r.bank_transaction_id
JOIN acc_bank_account b ON b.id=t.bank_account_id
WHERE r.journal_id=$1 AND b.account_id=$2 AND t.expense IS NOT NULL
`

type FinanceBankingJournalCreditUsedParams struct {
	JournalID uuid.UUID  `db:"journal_id" json:"journal_id"`
	AccountID *uuid.UUID `db:"account_id" json:"account_id"`
}

func (q *Queries) FinanceBankingJournalCreditUsed(ctx context.Context, arg FinanceBankingJournalCreditUsedParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, financeBankingJournalCreditUsed, arg.JournalID, arg.AccountID)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const financeBankingJournalDebitTotal = `-- name: FinanceBankingJournalDebitTotal :one
SELECT COALESCE(sum(debit), 0)::numeric
FROM acc_gl_journal_line
WHERE journal_id=$1 AND account_id=$2
`

type FinanceBankingJournalDebitTotalParams struct {
	JournalID uuid.UUID `db:"journal_id" json:"journal_id"`
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
}

func (q *Queries) FinanceBankingJournalDebitTotal(ctx context.Context, arg FinanceBankingJournalDebitTotalParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, financeBankingJournalDebitTotal, arg.JournalID, arg.AccountID)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const financeBankingJournalDebitUsed = `-- name: FinanceBankingJournalDebitUsed :one
SELECT COALESCE(sum(r.amount), 0)::numeric
FROM acc_bank_reconciliation r
JOIN acc_bank_transaction t ON t.id=r.bank_transaction_id
JOIN acc_bank_account b ON b.id=t.bank_account_id
WHERE r.journal_id=$1 AND b.account_id=$2 AND t.income IS NOT NULL
`

type FinanceBankingJournalDebitUsedParams struct {
	JournalID uuid.UUID  `db:"journal_id" json:"journal_id"`
	AccountID *uuid.UUID `db:"account_id" json:"account_id"`
}

func (q *Queries) FinanceBankingJournalDebitUsed(ctx context.Context, arg FinanceBankingJournalDebitUsedParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, financeBankingJournalDebitUsed, arg.JournalID, arg.AccountID)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const financeBankingLinkImportItem = `-- name: FinanceBankingLinkImportItem :execrows
UPDATE acc_bank_import_item
SET transaction_id=$2, updated_at=(now() AT TIME ZONE 'utc')
WHERE id=$1
`

type FinanceBankingLinkImportItemParams struct {
	ID            uuid.UUID  `db:"id" json:"id"`
	TransactionID *uuid.UUID `db:"transaction_id" json:"transaction_id"`
}

func (q *Queries) FinanceBankingLinkImportItem(ctx context.Context, arg FinanceBankingLinkImportItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, financeBankingLinkImportItem, arg.ID, arg.TransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const financeBankingListLockedImportItems = `-- name: FinanceBankingListLockedImportItems :many
SELECT id, row_no, occurred_at, income, expense, balance, counterparty_name,
       counterparty_account, summary, note, error, inserted_at, updated_at,
       import_id, company_id, transaction_id
FROM acc_bank_import_item
WHERE import_id=$1
ORDER BY row_no, id
FOR UPDATE
`

func (q *Queries) FinanceBankingListLockedImportItems(ctx context.Context, importID uuid.UUID) ([]AccBankImportItem, error) {
	rows, err := q.db.Query(ctx, financeBankingListLockedImportItems, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccBankImportItem{}
	for rows.Next() {
		var i AccBankImportItem
		if err := rows.Scan(
			&i.ID,
			&i.RowNo,
			&i.OccurredAt,
			&i.Income,
			&i.Expense,
			&i.Balance,
			&i.CounterpartyName,
			&i.CounterpartyAccount,
			&i.Summary,
			&i.Note,
			&i.Error,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ImportID,
			&i.CompanyID,
			&i.TransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeBankingLockAccount = `-- name: FinanceBankingLockAccount :one

SELECT id, alias, bank_name, branch_name, holder_name, account_no, active, note,
       inserted_at, updated_at, company_id, currency_id, account_id
FROM acc_bank_account
WHERE id=$1
FOR UPDATE
`

// Banking is currently consumed through its deep domain service. These named
// queries document and type-check the service's lock/order and projection
// contract for the next dbgen adoption pass.
func (q *Queries) FinanceBankingLockAccount(ctx context.Context, id uuid.UUID) (AccBankAccount, error) {
	row := q.db.QueryRow(ctx, financeBankingLockAccount, id)
	var i AccBankAccount
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.BankName,
		&i.BranchName,
		&i.HolderName,
		&i.AccountNo,
		&i.Active,
		&i.Note,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.CurrencyID,
		&i.AccountID,
	)
	return i, err
}

const financeBankingLockImport = `-- name: FinanceBankingLockImport :one
SELECT id, status, error, imported_at, inserted_at, updated_at, company_id,
       bank_account_id, template_id, file_id, created_by_id, imported_by_id
FROM acc_bank_import
WHERE id=$1
FOR UPDATE
`

func (q *Queries) FinanceBankingLockImport(ctx context.Context, id uuid.UUID) (AccBankImport, error) {
	row := q.db.QueryRow(ctx, financeBankingLockImport, id)
	var i AccBankImport
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.ImportedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.BankAccountID,
		&i.TemplateID,
		&i.FileID,
		&i.CreatedByID,
		&i.ImportedByID,
	)
	return i, err
}

const financeBankingLockImportItem = `-- name: FinanceBankingLockImportItem :one
SELECT id, row_no, occurred_at, income, expense, balance, counterparty_name,
       counterparty_account, summary, note, error, inserted_at, updated_at,
       import_id, company_id, transaction_id
FROM acc_bank_import_item
WHERE id=$1
FOR UPDATE
`

func (q *Queries) FinanceBankingLockImportItem(ctx context.Context, id uuid.UUID) (AccBankImportItem, error) {
	row := q.db.QueryRow(ctx, financeBankingLockImportItem, id)
	var i AccBankImportItem
	err := row.Scan(
		&i.ID,
		&i.RowNo,
		&i.OccurredAt,
		&i.Income,
		&i.Expense,
		&i.Balance,
		&i.CounterpartyName,
		&i.CounterpartyAccount,
		&i.Summary,
		&i.Note,
		&i.Error,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ImportID,
		&i.CompanyID,
		&i.TransactionID,
	)
	return i, err
}

const financeBankingLockJournal = `-- name: FinanceBankingLockJournal :one
SELECT id, status, company_id
FROM acc_gl_journal
WHERE id=$1
FOR UPDATE
`

type FinanceBankingLockJournalRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Status    string    `db:"status" json:"status"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) FinanceBankingLockJournal(ctx context.Context, id uuid.UUID) (FinanceBankingLockJournalRow, error) {
	row := q.db.QueryRow(ctx, financeBankingLockJournal, id)
	var i FinanceBankingLockJournalRow
	err := row.Scan(&i.ID, &i.Status, &i.CompanyID)
	return i, err
}

const financeBankingLockReconciliation = `-- name: FinanceBankingLockReconciliation :one
SELECT id, amount, inserted_at, updated_at, company_id, bank_transaction_id,
       journal_id
FROM acc_bank_reconciliation
WHERE id=$1
FOR UPDATE
`

func (q *Queries) FinanceBankingLockReconciliation(ctx context.Context, id uuid.UUID) (AccBankReconciliation, error) {
	row := q.db.QueryRow(ctx, financeBankingLockReconciliation, id)
	var i AccBankReconciliation
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.BankTransactionID,
		&i.JournalID,
	)
	return i, err
}

const financeBankingLockTransaction = `-- name: FinanceBankingLockTransaction :one
SELECT id, occurred_at, income, expense, balance, counterparty_name,
       counterparty_account, summary, note, reconciled_amount,
       unreconciled_amount, reconcile_status, inserted_at, updated_at,
       company_id, bank_account_id
FROM acc_bank_transaction
WHERE id=$1
FOR UPDATE
`

type FinanceBankingLockTransactionRow struct {
	ID                  uuid.UUID        `db:"id" json:"id"`
	OccurredAt          pgtype.Timestamp `db:"occurred_at" json:"occurred_at"`
	Income              pgtype.Numeric   `db:"income" json:"income"`
	Expense             pgtype.Numeric   `db:"expense" json:"expense"`
	Balance             pgtype.Numeric   `db:"balance" json:"balance"`
	CounterpartyName    pgtype.Text      `db:"counterparty_name" json:"counterparty_name"`
	CounterpartyAccount pgtype.Text      `db:"counterparty_account" json:"counterparty_account"`
	Summary             pgtype.Text      `db:"summary" json:"summary"`
	Note                pgtype.Text      `db:"note" json:"note"`
	ReconciledAmount    decimal.Decimal  `db:"reconciled_amount" json:"reconciled_amount"`
	UnreconciledAmount  decimal.Decimal  `db:"unreconciled_amount" json:"unreconciled_amount"`
	ReconcileStatus     string           `db:"reconcile_status" json:"reconcile_status"`
	InsertedAt          pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt           pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	CompanyID           uuid.UUID        `db:"company_id" json:"company_id"`
	BankAccountID       uuid.UUID        `db:"bank_account_id" json:"bank_account_id"`
}

func (q *Queries) FinanceBankingLockTransaction(ctx context.Context, id uuid.UUID) (FinanceBankingLockTransactionRow, error) {
	row := q.db.QueryRow(ctx, financeBankingLockTransaction, id)
	var i FinanceBankingLockTransactionRow
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.Income,
		&i.Expense,
		&i.Balance,
		&i.CounterpartyName,
		&i.CounterpartyAccount,
		&i.Summary,
		&i.Note,
		&i.ReconciledAmount,
		&i.UnreconciledAmount,
		&i.ReconcileStatus,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.BankAccountID,
	)
	return i, err
}

const financeBankingMarkImportImported = `-- name: FinanceBankingMarkImportImported :execrows
UPDATE acc_bank_import
SET status='imported', imported_at=$2, imported_by_id=$3,
    updated_at=(now() AT TIME ZONE 'utc')
WHERE id=$1
`

type FinanceBankingMarkImportImportedParams struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	ImportedAt   pgtype.Timestamp `db:"imported_at" json:"imported_at"`
	ImportedByID *uuid.UUID       `db:"imported_by_id" json:"imported_by_id"`
}

func (q *Queries) FinanceBankingMarkImportImported(ctx context.Context, arg FinanceBankingMarkImportImportedParams) (int64, error) {
	result, err := q.db.Exec(ctx, financeBankingMarkImportImported, arg.ID, arg.ImportedAt, arg.ImportedByID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const financeBankingReconciledTotal = `-- name: FinanceBankingReconciledTotal :one
SELECT COALESCE(sum(amount), 0)::numeric
FROM acc_bank_reconciliation
WHERE bank_transaction_id=$1
`

func (q *Queries) FinanceBankingReconciledTotal(ctx context.Context, bankTransactionID uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, financeBankingReconciledTotal, bankTransactionID)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const financeBankingRefreshTransactionProjection = `-- name: FinanceBankingRefreshTransactionProjection :execrows
UPDATE acc_bank_transaction
SET reconciled_amount=$2,
    unreconciled_amount=$3,
    reconcile_status=$4,
    updated_at=(now() AT TIME ZONE 'utc')
WHERE id=$1
`

type FinanceBankingRefreshTransactionProjectionParams struct {
	ID                 uuid.UUID       `db:"id" json:"id"`
	ReconciledAmount   decimal.Decimal `db:"reconciled_amount" json:"reconciled_amount"`
	UnreconciledAmount decimal.Decimal `db:"unreconciled_amount" json:"unreconciled_amount"`
	ReconcileStatus    string          `db:"reconcile_status" json:"reconcile_status"`
}

func (q *Queries) FinanceBankingRefreshTransactionProjection(ctx context.Context, arg FinanceBankingRefreshTransactionProjectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, financeBankingRefreshTransactionProjection,
		arg.ID,
		arg.ReconciledAmount,
		arg.UnreconciledAmount,
		arg.ReconcileStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
