// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fulfillment.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getPurOutsourcedIssue = `-- name: GetPurOutsourcedIssue :one
SELECT id, issue_no, issue_date, party_type, party_id, remarks, status, audited_at, inserted_at, updated_at, company_id, from_warehouse_id, outsourced_warehouse_id, created_by_id, audited_by_id FROM pur_outsourced_issue WHERE id = $1
`

func (q *Queries) GetPurOutsourcedIssue(ctx context.Context, id uuid.UUID) (PurOutsourcedIssue, error) {
	row := q.db.QueryRow(ctx, getPurOutsourcedIssue, id)
	var i PurOutsourcedIssue
	err := row.Scan(
		&i.ID,
		&i.IssueNo,
		&i.IssueDate,
		&i.PartyType,
		&i.PartyID,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.FromWarehouseID,
		&i.OutsourcedWarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const getPurOutsourcedIssueItem = `-- name: GetPurOutsourcedIssueItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, issue_id, company_id, order_item_material_id, material_id, unit_id, from_warehouse_id, outsourced_warehouse_id FROM pur_outsourced_issue_item WHERE id = $1
`

func (q *Queries) GetPurOutsourcedIssueItem(ctx context.Context, id uuid.UUID) (PurOutsourcedIssueItem, error) {
	row := q.db.QueryRow(ctx, getPurOutsourcedIssueItem, id)
	var i PurOutsourcedIssueItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.OrderNo,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.IssueID,
		&i.CompanyID,
		&i.OrderItemMaterialID,
		&i.MaterialID,
		&i.UnitID,
		&i.FromWarehouseID,
		&i.OutsourcedWarehouseID,
	)
	return i, err
}

const getPurOutsourcedReceipt = `-- name: GetPurOutsourcedReceipt :one
SELECT id, receipt_no, receipt_date, posting_date, party_type, party_id, remarks, status, audited_at, inserted_at, updated_at, company_id, warehouse_id, outsourced_warehouse_id, debit_account_id, credit_account_id, created_by_id, audited_by_id FROM pur_outsourced_receipt WHERE id = $1
`

func (q *Queries) GetPurOutsourcedReceipt(ctx context.Context, id uuid.UUID) (PurOutsourcedReceipt, error) {
	row := q.db.QueryRow(ctx, getPurOutsourcedReceipt, id)
	var i PurOutsourcedReceipt
	err := row.Scan(
		&i.ID,
		&i.ReceiptNo,
		&i.ReceiptDate,
		&i.PostingDate,
		&i.PartyType,
		&i.PartyID,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.OutsourcedWarehouseID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const getPurOutsourcedReceiptItem = `-- name: GetPurOutsourcedReceiptItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, reconciled_qty, remarks, inserted_at, updated_at, receipt_id, company_id, order_item_id, material_id, unit_id, warehouse_id FROM pur_outsourced_receipt_item WHERE id = $1
`

func (q *Queries) GetPurOutsourcedReceiptItem(ctx context.Context, id uuid.UUID) (PurOutsourcedReceiptItem, error) {
	row := q.db.QueryRow(ctx, getPurOutsourcedReceiptItem, id)
	var i PurOutsourcedReceiptItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.CustomerPartNo,
		&i.UnitName,
		&i.OrderNo,
		&i.OrderQty,
		&i.OrderBaseQty,
		&i.OrderUnitName,
		&i.OrderPrice,
		&i.OrderAmount,
		&i.OrderBasePrice,
		&i.OrderBaseAmount,
		&i.OrderTaxRate,
		&i.OrderCurrencyCode,
		&i.ReconciledQty,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReceiptID,
		&i.CompanyID,
		&i.OrderItemID,
		&i.MaterialID,
		&i.UnitID,
		&i.WarehouseID,
	)
	return i, err
}

const getPurOutsourcedReceiptItemByproduct = `-- name: GetPurOutsourcedReceiptItemByproduct :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, receipt_item_id, company_id, order_item_byproduct_id, material_id, unit_id, warehouse_id FROM pur_outsourced_receipt_item_byproduct WHERE id = $1
`

func (q *Queries) GetPurOutsourcedReceiptItemByproduct(ctx context.Context, id uuid.UUID) (PurOutsourcedReceiptItemByproduct, error) {
	row := q.db.QueryRow(ctx, getPurOutsourcedReceiptItemByproduct, id)
	var i PurOutsourcedReceiptItemByproduct
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.OrderNo,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReceiptItemID,
		&i.CompanyID,
		&i.OrderItemByproductID,
		&i.MaterialID,
		&i.UnitID,
		&i.WarehouseID,
	)
	return i, err
}

const getPurOutsourcedReceiptItemMaterial = `-- name: GetPurOutsourcedReceiptItemMaterial :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, receipt_item_id, company_id, order_item_material_id, material_id, unit_id, outsourced_warehouse_id FROM pur_outsourced_receipt_item_material WHERE id = $1
`

func (q *Queries) GetPurOutsourcedReceiptItemMaterial(ctx context.Context, id uuid.UUID) (PurOutsourcedReceiptItemMaterial, error) {
	row := q.db.QueryRow(ctx, getPurOutsourcedReceiptItemMaterial, id)
	var i PurOutsourcedReceiptItemMaterial
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.OrderNo,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReceiptItemID,
		&i.CompanyID,
		&i.OrderItemMaterialID,
		&i.MaterialID,
		&i.UnitID,
		&i.OutsourcedWarehouseID,
	)
	return i, err
}

const getPurReceipt = `-- name: GetPurReceipt :one
SELECT id, receipt_no, receipt_date, posting_date, party_type, party_id, remarks, status, audited_at, inserted_at, updated_at, company_id, warehouse_id, debit_account_id, credit_account_id, created_by_id, audited_by_id FROM pur_receipt WHERE id = $1
`

func (q *Queries) GetPurReceipt(ctx context.Context, id uuid.UUID) (PurReceipt, error) {
	row := q.db.QueryRow(ctx, getPurReceipt, id)
	var i PurReceipt
	err := row.Scan(
		&i.ID,
		&i.ReceiptNo,
		&i.ReceiptDate,
		&i.PostingDate,
		&i.PartyType,
		&i.PartyID,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const getPurReceiptItem = `-- name: GetPurReceiptItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, remarks, inserted_at, updated_at, receipt_id, company_id, order_item_id, material_id, unit_id, warehouse_id, reconciled_qty FROM pur_receipt_item WHERE id = $1
`

func (q *Queries) GetPurReceiptItem(ctx context.Context, id uuid.UUID) (PurReceiptItem, error) {
	row := q.db.QueryRow(ctx, getPurReceiptItem, id)
	var i PurReceiptItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.CustomerPartNo,
		&i.UnitName,
		&i.OrderNo,
		&i.OrderQty,
		&i.OrderBaseQty,
		&i.OrderUnitName,
		&i.OrderPrice,
		&i.OrderAmount,
		&i.OrderBasePrice,
		&i.OrderBaseAmount,
		&i.OrderTaxRate,
		&i.OrderCurrencyCode,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReceiptID,
		&i.CompanyID,
		&i.OrderItemID,
		&i.MaterialID,
		&i.UnitID,
		&i.WarehouseID,
		&i.ReconciledQty,
	)
	return i, err
}

const getSalDelivery = `-- name: GetSalDelivery :one

SELECT id, delivery_no, delivery_date, posting_date, party_type, party_id, remarks, status, audited_at, inserted_at, updated_at, company_id, warehouse_id, debit_account_id, credit_account_id, created_by_id, audited_by_id FROM sal_delivery WHERE id = $1
`

// PR-2.15 fulfillment aggregates use fixed, generated table access for their
// lock/read seams. Dynamic list filtering remains in the domain query layer,
// where identifiers come only from compile-time side specifications.
func (q *Queries) GetSalDelivery(ctx context.Context, id uuid.UUID) (SalDelivery, error) {
	row := q.db.QueryRow(ctx, getSalDelivery, id)
	var i SalDelivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryNo,
		&i.DeliveryDate,
		&i.PostingDate,
		&i.PartyType,
		&i.PartyID,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const getSalDeliveryItem = `-- name: GetSalDeliveryItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, remarks, inserted_at, updated_at, delivery_id, company_id, order_item_id, material_id, unit_id, warehouse_id, reconciled_qty FROM sal_delivery_item WHERE id = $1
`

func (q *Queries) GetSalDeliveryItem(ctx context.Context, id uuid.UUID) (SalDeliveryItem, error) {
	row := q.db.QueryRow(ctx, getSalDeliveryItem, id)
	var i SalDeliveryItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.CustomerPartNo,
		&i.UnitName,
		&i.OrderNo,
		&i.OrderQty,
		&i.OrderBaseQty,
		&i.OrderUnitName,
		&i.OrderPrice,
		&i.OrderAmount,
		&i.OrderBasePrice,
		&i.OrderBaseAmount,
		&i.OrderTaxRate,
		&i.OrderCurrencyCode,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.DeliveryID,
		&i.CompanyID,
		&i.OrderItemID,
		&i.MaterialID,
		&i.UnitID,
		&i.WarehouseID,
		&i.ReconciledQty,
	)
	return i, err
}

const listPurOutsourcedIssueItemsForHead = `-- name: ListPurOutsourcedIssueItemsForHead :many
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, issue_id, company_id, order_item_material_id, material_id, unit_id, from_warehouse_id, outsourced_warehouse_id FROM pur_outsourced_issue_item
WHERE issue_id = $1
ORDER BY idx ASC, id ASC
`

func (q *Queries) ListPurOutsourcedIssueItemsForHead(ctx context.Context, issueID uuid.UUID) ([]PurOutsourcedIssueItem, error) {
	rows, err := q.db.Query(ctx, listPurOutsourcedIssueItemsForHead, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurOutsourcedIssueItem{}
	for rows.Next() {
		var i PurOutsourcedIssueItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.OrderNo,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.IssueID,
			&i.CompanyID,
			&i.OrderItemMaterialID,
			&i.MaterialID,
			&i.UnitID,
			&i.FromWarehouseID,
			&i.OutsourcedWarehouseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurOutsourcedReceiptItemByproducts = `-- name: ListPurOutsourcedReceiptItemByproducts :many
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, receipt_item_id, company_id, order_item_byproduct_id, material_id, unit_id, warehouse_id FROM pur_outsourced_receipt_item_byproduct
WHERE receipt_item_id = $1
ORDER BY idx ASC, id ASC
`

func (q *Queries) ListPurOutsourcedReceiptItemByproducts(ctx context.Context, receiptItemID uuid.UUID) ([]PurOutsourcedReceiptItemByproduct, error) {
	rows, err := q.db.Query(ctx, listPurOutsourcedReceiptItemByproducts, receiptItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurOutsourcedReceiptItemByproduct{}
	for rows.Next() {
		var i PurOutsourcedReceiptItemByproduct
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.OrderNo,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ReceiptItemID,
			&i.CompanyID,
			&i.OrderItemByproductID,
			&i.MaterialID,
			&i.UnitID,
			&i.WarehouseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurOutsourcedReceiptItemMaterials = `-- name: ListPurOutsourcedReceiptItemMaterials :many
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, receipt_item_id, company_id, order_item_material_id, material_id, unit_id, outsourced_warehouse_id FROM pur_outsourced_receipt_item_material
WHERE receipt_item_id = $1
ORDER BY idx ASC, id ASC
`

func (q *Queries) ListPurOutsourcedReceiptItemMaterials(ctx context.Context, receiptItemID uuid.UUID) ([]PurOutsourcedReceiptItemMaterial, error) {
	rows, err := q.db.Query(ctx, listPurOutsourcedReceiptItemMaterials, receiptItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurOutsourcedReceiptItemMaterial{}
	for rows.Next() {
		var i PurOutsourcedReceiptItemMaterial
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.OrderNo,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ReceiptItemID,
			&i.CompanyID,
			&i.OrderItemMaterialID,
			&i.MaterialID,
			&i.UnitID,
			&i.OutsourcedWarehouseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurOutsourcedReceiptItemsForHead = `-- name: ListPurOutsourcedReceiptItemsForHead :many
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, reconciled_qty, remarks, inserted_at, updated_at, receipt_id, company_id, order_item_id, material_id, unit_id, warehouse_id FROM pur_outsourced_receipt_item
WHERE receipt_id = $1
ORDER BY idx ASC, id ASC
`

func (q *Queries) ListPurOutsourcedReceiptItemsForHead(ctx context.Context, receiptID uuid.UUID) ([]PurOutsourcedReceiptItem, error) {
	rows, err := q.db.Query(ctx, listPurOutsourcedReceiptItemsForHead, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurOutsourcedReceiptItem{}
	for rows.Next() {
		var i PurOutsourcedReceiptItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.CustomerPartNo,
			&i.UnitName,
			&i.OrderNo,
			&i.OrderQty,
			&i.OrderBaseQty,
			&i.OrderUnitName,
			&i.OrderPrice,
			&i.OrderAmount,
			&i.OrderBasePrice,
			&i.OrderBaseAmount,
			&i.OrderTaxRate,
			&i.OrderCurrencyCode,
			&i.ReconciledQty,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ReceiptID,
			&i.CompanyID,
			&i.OrderItemID,
			&i.MaterialID,
			&i.UnitID,
			&i.WarehouseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurReceiptItemsForHead = `-- name: ListPurReceiptItemsForHead :many
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, remarks, inserted_at, updated_at, receipt_id, company_id, order_item_id, material_id, unit_id, warehouse_id, reconciled_qty FROM pur_receipt_item
WHERE receipt_id = $1
ORDER BY idx ASC, id ASC
`

func (q *Queries) ListPurReceiptItemsForHead(ctx context.Context, receiptID uuid.UUID) ([]PurReceiptItem, error) {
	rows, err := q.db.Query(ctx, listPurReceiptItemsForHead, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurReceiptItem{}
	for rows.Next() {
		var i PurReceiptItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.CustomerPartNo,
			&i.UnitName,
			&i.OrderNo,
			&i.OrderQty,
			&i.OrderBaseQty,
			&i.OrderUnitName,
			&i.OrderPrice,
			&i.OrderAmount,
			&i.OrderBasePrice,
			&i.OrderBaseAmount,
			&i.OrderTaxRate,
			&i.OrderCurrencyCode,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ReceiptID,
			&i.CompanyID,
			&i.OrderItemID,
			&i.MaterialID,
			&i.UnitID,
			&i.WarehouseID,
			&i.ReconciledQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalDeliveryItemsForHead = `-- name: ListSalDeliveryItemsForHead :many
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, remarks, inserted_at, updated_at, delivery_id, company_id, order_item_id, material_id, unit_id, warehouse_id, reconciled_qty FROM sal_delivery_item
WHERE delivery_id = $1
ORDER BY idx ASC, id ASC
`

func (q *Queries) ListSalDeliveryItemsForHead(ctx context.Context, deliveryID uuid.UUID) ([]SalDeliveryItem, error) {
	rows, err := q.db.Query(ctx, listSalDeliveryItemsForHead, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalDeliveryItem{}
	for rows.Next() {
		var i SalDeliveryItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.CustomerPartNo,
			&i.UnitName,
			&i.OrderNo,
			&i.OrderQty,
			&i.OrderBaseQty,
			&i.OrderUnitName,
			&i.OrderPrice,
			&i.OrderAmount,
			&i.OrderBasePrice,
			&i.OrderBaseAmount,
			&i.OrderTaxRate,
			&i.OrderCurrencyCode,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.DeliveryID,
			&i.CompanyID,
			&i.OrderItemID,
			&i.MaterialID,
			&i.UnitID,
			&i.WarehouseID,
			&i.ReconciledQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPurOutsourcedIssue = `-- name: LockPurOutsourcedIssue :one
SELECT id, issue_no, issue_date, party_type, party_id, remarks, status, audited_at, inserted_at, updated_at, company_id, from_warehouse_id, outsourced_warehouse_id, created_by_id, audited_by_id FROM pur_outsourced_issue WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPurOutsourcedIssue(ctx context.Context, id uuid.UUID) (PurOutsourcedIssue, error) {
	row := q.db.QueryRow(ctx, lockPurOutsourcedIssue, id)
	var i PurOutsourcedIssue
	err := row.Scan(
		&i.ID,
		&i.IssueNo,
		&i.IssueDate,
		&i.PartyType,
		&i.PartyID,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.FromWarehouseID,
		&i.OutsourcedWarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const lockPurOutsourcedIssueItem = `-- name: LockPurOutsourcedIssueItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, issue_id, company_id, order_item_material_id, material_id, unit_id, from_warehouse_id, outsourced_warehouse_id FROM pur_outsourced_issue_item WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPurOutsourcedIssueItem(ctx context.Context, id uuid.UUID) (PurOutsourcedIssueItem, error) {
	row := q.db.QueryRow(ctx, lockPurOutsourcedIssueItem, id)
	var i PurOutsourcedIssueItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.OrderNo,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.IssueID,
		&i.CompanyID,
		&i.OrderItemMaterialID,
		&i.MaterialID,
		&i.UnitID,
		&i.FromWarehouseID,
		&i.OutsourcedWarehouseID,
	)
	return i, err
}

const lockPurOutsourcedReceipt = `-- name: LockPurOutsourcedReceipt :one
SELECT id, receipt_no, receipt_date, posting_date, party_type, party_id, remarks, status, audited_at, inserted_at, updated_at, company_id, warehouse_id, outsourced_warehouse_id, debit_account_id, credit_account_id, created_by_id, audited_by_id FROM pur_outsourced_receipt WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPurOutsourcedReceipt(ctx context.Context, id uuid.UUID) (PurOutsourcedReceipt, error) {
	row := q.db.QueryRow(ctx, lockPurOutsourcedReceipt, id)
	var i PurOutsourcedReceipt
	err := row.Scan(
		&i.ID,
		&i.ReceiptNo,
		&i.ReceiptDate,
		&i.PostingDate,
		&i.PartyType,
		&i.PartyID,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.OutsourcedWarehouseID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const lockPurOutsourcedReceiptItem = `-- name: LockPurOutsourcedReceiptItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, reconciled_qty, remarks, inserted_at, updated_at, receipt_id, company_id, order_item_id, material_id, unit_id, warehouse_id FROM pur_outsourced_receipt_item WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPurOutsourcedReceiptItem(ctx context.Context, id uuid.UUID) (PurOutsourcedReceiptItem, error) {
	row := q.db.QueryRow(ctx, lockPurOutsourcedReceiptItem, id)
	var i PurOutsourcedReceiptItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.CustomerPartNo,
		&i.UnitName,
		&i.OrderNo,
		&i.OrderQty,
		&i.OrderBaseQty,
		&i.OrderUnitName,
		&i.OrderPrice,
		&i.OrderAmount,
		&i.OrderBasePrice,
		&i.OrderBaseAmount,
		&i.OrderTaxRate,
		&i.OrderCurrencyCode,
		&i.ReconciledQty,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReceiptID,
		&i.CompanyID,
		&i.OrderItemID,
		&i.MaterialID,
		&i.UnitID,
		&i.WarehouseID,
	)
	return i, err
}

const lockPurOutsourcedReceiptItemByproduct = `-- name: LockPurOutsourcedReceiptItemByproduct :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, receipt_item_id, company_id, order_item_byproduct_id, material_id, unit_id, warehouse_id FROM pur_outsourced_receipt_item_byproduct WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPurOutsourcedReceiptItemByproduct(ctx context.Context, id uuid.UUID) (PurOutsourcedReceiptItemByproduct, error) {
	row := q.db.QueryRow(ctx, lockPurOutsourcedReceiptItemByproduct, id)
	var i PurOutsourcedReceiptItemByproduct
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.OrderNo,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReceiptItemID,
		&i.CompanyID,
		&i.OrderItemByproductID,
		&i.MaterialID,
		&i.UnitID,
		&i.WarehouseID,
	)
	return i, err
}

const lockPurOutsourcedReceiptItemMaterial = `-- name: LockPurOutsourcedReceiptItemMaterial :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, order_no, remarks, inserted_at, updated_at, receipt_item_id, company_id, order_item_material_id, material_id, unit_id, outsourced_warehouse_id FROM pur_outsourced_receipt_item_material WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPurOutsourcedReceiptItemMaterial(ctx context.Context, id uuid.UUID) (PurOutsourcedReceiptItemMaterial, error) {
	row := q.db.QueryRow(ctx, lockPurOutsourcedReceiptItemMaterial, id)
	var i PurOutsourcedReceiptItemMaterial
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.OrderNo,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReceiptItemID,
		&i.CompanyID,
		&i.OrderItemMaterialID,
		&i.MaterialID,
		&i.UnitID,
		&i.OutsourcedWarehouseID,
	)
	return i, err
}

const lockPurReceipt = `-- name: LockPurReceipt :one
SELECT id, receipt_no, receipt_date, posting_date, party_type, party_id, remarks, status, audited_at, inserted_at, updated_at, company_id, warehouse_id, debit_account_id, credit_account_id, created_by_id, audited_by_id FROM pur_receipt WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPurReceipt(ctx context.Context, id uuid.UUID) (PurReceipt, error) {
	row := q.db.QueryRow(ctx, lockPurReceipt, id)
	var i PurReceipt
	err := row.Scan(
		&i.ID,
		&i.ReceiptNo,
		&i.ReceiptDate,
		&i.PostingDate,
		&i.PartyType,
		&i.PartyID,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const lockPurReceiptItem = `-- name: LockPurReceiptItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, remarks, inserted_at, updated_at, receipt_id, company_id, order_item_id, material_id, unit_id, warehouse_id, reconciled_qty FROM pur_receipt_item WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPurReceiptItem(ctx context.Context, id uuid.UUID) (PurReceiptItem, error) {
	row := q.db.QueryRow(ctx, lockPurReceiptItem, id)
	var i PurReceiptItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.CustomerPartNo,
		&i.UnitName,
		&i.OrderNo,
		&i.OrderQty,
		&i.OrderBaseQty,
		&i.OrderUnitName,
		&i.OrderPrice,
		&i.OrderAmount,
		&i.OrderBasePrice,
		&i.OrderBaseAmount,
		&i.OrderTaxRate,
		&i.OrderCurrencyCode,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReceiptID,
		&i.CompanyID,
		&i.OrderItemID,
		&i.MaterialID,
		&i.UnitID,
		&i.WarehouseID,
		&i.ReconciledQty,
	)
	return i, err
}

const lockSalDelivery = `-- name: LockSalDelivery :one
SELECT id, delivery_no, delivery_date, posting_date, party_type, party_id, remarks, status, audited_at, inserted_at, updated_at, company_id, warehouse_id, debit_account_id, credit_account_id, created_by_id, audited_by_id FROM sal_delivery WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSalDelivery(ctx context.Context, id uuid.UUID) (SalDelivery, error) {
	row := q.db.QueryRow(ctx, lockSalDelivery, id)
	var i SalDelivery
	err := row.Scan(
		&i.ID,
		&i.DeliveryNo,
		&i.DeliveryDate,
		&i.PostingDate,
		&i.PartyType,
		&i.PartyID,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const lockSalDeliveryItem = `-- name: LockSalDeliveryItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, customer_part_no, unit_name, order_no, order_qty, order_base_qty, order_unit_name, order_price, order_amount, order_base_price, order_base_amount, order_tax_rate, order_currency_code, remarks, inserted_at, updated_at, delivery_id, company_id, order_item_id, material_id, unit_id, warehouse_id, reconciled_qty FROM sal_delivery_item WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSalDeliveryItem(ctx context.Context, id uuid.UUID) (SalDeliveryItem, error) {
	row := q.db.QueryRow(ctx, lockSalDeliveryItem, id)
	var i SalDeliveryItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.CustomerPartNo,
		&i.UnitName,
		&i.OrderNo,
		&i.OrderQty,
		&i.OrderBaseQty,
		&i.OrderUnitName,
		&i.OrderPrice,
		&i.OrderAmount,
		&i.OrderBasePrice,
		&i.OrderBaseAmount,
		&i.OrderTaxRate,
		&i.OrderCurrencyCode,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.DeliveryID,
		&i.CompanyID,
		&i.OrderItemID,
		&i.MaterialID,
		&i.UnitID,
		&i.WarehouseID,
		&i.ReconciledQty,
	)
	return i, err
}
