// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_operations.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createHrAttendanceCorrection = `-- name: CreateHrAttendanceCorrection :one
INSERT INTO hr_attendance_correction (
  date,times,note,employee_id,created_by_id
) VALUES ($1,$2,$3,$4,$5)
RETURNING id, date, times, note, inserted_at, updated_at, employee_id, created_by_id
`

type CreateHrAttendanceCorrectionParams struct {
	Date        pgtype.Date   `db:"date" json:"date"`
	Times       []pgtype.Time `db:"times" json:"times"`
	Note        pgtype.Text   `db:"note" json:"note"`
	EmployeeID  uuid.UUID     `db:"employee_id" json:"employee_id"`
	CreatedByID *uuid.UUID    `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateHrAttendanceCorrection(ctx context.Context, arg CreateHrAttendanceCorrectionParams) (HrAttendanceCorrection, error) {
	row := q.db.QueryRow(ctx, createHrAttendanceCorrection,
		arg.Date,
		arg.Times,
		arg.Note,
		arg.EmployeeID,
		arg.CreatedByID,
	)
	var i HrAttendanceCorrection
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Times,
		&i.Note,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
		&i.CreatedByID,
	)
	return i, err
}

const createHrAttendanceImport = `-- name: CreateHrAttendanceImport :one
INSERT INTO hr_attendance_import (
  status, error, total_rows, bad_rows, dup_rows, matched_rows, unmatched_rows,
  unmatched_detail, file_id, created_by_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, status, error, total_rows, bad_rows, dup_rows, matched_rows, unmatched_rows, unmatched_detail, imported_count, skipped_existing_rows, skipped_unmatched_rows, auto_created_count, imported_at, inserted_at, updated_at, file_id, created_by_id, imported_by_id
`

type CreateHrAttendanceImportParams struct {
	Status          string      `db:"status" json:"status"`
	Error           pgtype.Text `db:"error" json:"error"`
	TotalRows       pgtype.Int8 `db:"total_rows" json:"total_rows"`
	BadRows         pgtype.Int8 `db:"bad_rows" json:"bad_rows"`
	DupRows         pgtype.Int8 `db:"dup_rows" json:"dup_rows"`
	MatchedRows     pgtype.Int8 `db:"matched_rows" json:"matched_rows"`
	UnmatchedRows   pgtype.Int8 `db:"unmatched_rows" json:"unmatched_rows"`
	UnmatchedDetail pgtype.Text `db:"unmatched_detail" json:"unmatched_detail"`
	FileID          uuid.UUID   `db:"file_id" json:"file_id"`
	CreatedByID     *uuid.UUID  `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateHrAttendanceImport(ctx context.Context, arg CreateHrAttendanceImportParams) (HrAttendanceImport, error) {
	row := q.db.QueryRow(ctx, createHrAttendanceImport,
		arg.Status,
		arg.Error,
		arg.TotalRows,
		arg.BadRows,
		arg.DupRows,
		arg.MatchedRows,
		arg.UnmatchedRows,
		arg.UnmatchedDetail,
		arg.FileID,
		arg.CreatedByID,
	)
	var i HrAttendanceImport
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.TotalRows,
		&i.BadRows,
		&i.DupRows,
		&i.MatchedRows,
		&i.UnmatchedRows,
		&i.UnmatchedDetail,
		&i.ImportedCount,
		&i.SkippedExistingRows,
		&i.SkippedUnmatchedRows,
		&i.AutoCreatedCount,
		&i.ImportedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.FileID,
		&i.CreatedByID,
		&i.ImportedByID,
	)
	return i, err
}

const createHrEmployeeLoan = `-- name: CreateHrEmployeeLoan :one
INSERT INTO hr_employee_loan (
  kind,occurred_on,amount,remarks,employee_id,payroll_id,created_by_id
) VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, kind, occurred_on, amount, remarks, inserted_at, updated_at, employee_id, payroll_id, created_by_id
`

type CreateHrEmployeeLoanParams struct {
	Kind        string          `db:"kind" json:"kind"`
	OccurredOn  pgtype.Date     `db:"occurred_on" json:"occurred_on"`
	Amount      decimal.Decimal `db:"amount" json:"amount"`
	Remarks     pgtype.Text     `db:"remarks" json:"remarks"`
	EmployeeID  uuid.UUID       `db:"employee_id" json:"employee_id"`
	PayrollID   *uuid.UUID      `db:"payroll_id" json:"payroll_id"`
	CreatedByID *uuid.UUID      `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateHrEmployeeLoan(ctx context.Context, arg CreateHrEmployeeLoanParams) (HrEmployeeLoan, error) {
	row := q.db.QueryRow(ctx, createHrEmployeeLoan,
		arg.Kind,
		arg.OccurredOn,
		arg.Amount,
		arg.Remarks,
		arg.EmployeeID,
		arg.PayrollID,
		arg.CreatedByID,
	)
	var i HrEmployeeLoan
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OccurredOn,
		&i.Amount,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
		&i.PayrollID,
		&i.CreatedByID,
	)
	return i, err
}

const createHrPayroll = `-- name: CreateHrPayroll :one
INSERT INTO hr_payroll (
  month,workdays,attendance_days,missing_days,overtime_hours,daily_wage,
  base_amount,allowance,bonus,fine,loan_deduction,payable,remarks,employee_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id, month, workdays, attendance_days, missing_days, overtime_hours, daily_wage, base_amount, allowance, bonus, fine, loan_deduction, payable, status, remarks, inserted_at, updated_at, employee_id
`

type CreateHrPayrollParams struct {
	Month          string          `db:"month" json:"month"`
	Workdays       decimal.Decimal `db:"workdays" json:"workdays"`
	AttendanceDays int64           `db:"attendance_days" json:"attendance_days"`
	MissingDays    int64           `db:"missing_days" json:"missing_days"`
	OvertimeHours  decimal.Decimal `db:"overtime_hours" json:"overtime_hours"`
	DailyWage      decimal.Decimal `db:"daily_wage" json:"daily_wage"`
	BaseAmount     decimal.Decimal `db:"base_amount" json:"base_amount"`
	Allowance      decimal.Decimal `db:"allowance" json:"allowance"`
	Bonus          decimal.Decimal `db:"bonus" json:"bonus"`
	Fine           decimal.Decimal `db:"fine" json:"fine"`
	LoanDeduction  decimal.Decimal `db:"loan_deduction" json:"loan_deduction"`
	Payable        decimal.Decimal `db:"payable" json:"payable"`
	Remarks        pgtype.Text     `db:"remarks" json:"remarks"`
	EmployeeID     uuid.UUID       `db:"employee_id" json:"employee_id"`
}

func (q *Queries) CreateHrPayroll(ctx context.Context, arg CreateHrPayrollParams) (HrPayroll, error) {
	row := q.db.QueryRow(ctx, createHrPayroll,
		arg.Month,
		arg.Workdays,
		arg.AttendanceDays,
		arg.MissingDays,
		arg.OvertimeHours,
		arg.DailyWage,
		arg.BaseAmount,
		arg.Allowance,
		arg.Bonus,
		arg.Fine,
		arg.LoanDeduction,
		arg.Payable,
		arg.Remarks,
		arg.EmployeeID,
	)
	var i HrPayroll
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Workdays,
		&i.AttendanceDays,
		&i.MissingDays,
		&i.OvertimeHours,
		&i.DailyWage,
		&i.BaseAmount,
		&i.Allowance,
		&i.Bonus,
		&i.Fine,
		&i.LoanDeduction,
		&i.Payable,
		&i.Status,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
	)
	return i, err
}

const createHrPayrollPayment = `-- name: CreateHrPayrollPayment :one
INSERT INTO hr_payroll_payment (
  month,paid_on,amount,kind,remarks,payroll_id,employee_id,created_by_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, month, paid_on, amount, kind, remarks, inserted_at, updated_at, payroll_id, employee_id, created_by_id
`

type CreateHrPayrollPaymentParams struct {
	Month       pgtype.Text     `db:"month" json:"month"`
	PaidOn      pgtype.Date     `db:"paid_on" json:"paid_on"`
	Amount      decimal.Decimal `db:"amount" json:"amount"`
	Kind        string          `db:"kind" json:"kind"`
	Remarks     pgtype.Text     `db:"remarks" json:"remarks"`
	PayrollID   uuid.UUID       `db:"payroll_id" json:"payroll_id"`
	EmployeeID  *uuid.UUID      `db:"employee_id" json:"employee_id"`
	CreatedByID *uuid.UUID      `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateHrPayrollPayment(ctx context.Context, arg CreateHrPayrollPaymentParams) (HrPayrollPayment, error) {
	row := q.db.QueryRow(ctx, createHrPayrollPayment,
		arg.Month,
		arg.PaidOn,
		arg.Amount,
		arg.Kind,
		arg.Remarks,
		arg.PayrollID,
		arg.EmployeeID,
		arg.CreatedByID,
	)
	var i HrPayrollPayment
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.PaidOn,
		&i.Amount,
		&i.Kind,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.PayrollID,
		&i.EmployeeID,
		&i.CreatedByID,
	)
	return i, err
}

const deleteHrAttendanceCorrection = `-- name: DeleteHrAttendanceCorrection :exec
DELETE FROM hr_attendance_correction WHERE id = $1
`

func (q *Queries) DeleteHrAttendanceCorrection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHrAttendanceCorrection, id)
	return err
}

const deleteHrAttendanceDayByPair = `-- name: DeleteHrAttendanceDayByPair :exec
DELETE FROM hr_attendance_day WHERE employee_id=$1 AND date=$2
`

type DeleteHrAttendanceDayByPairParams struct {
	EmployeeID uuid.UUID   `db:"employee_id" json:"employee_id"`
	Date       pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) DeleteHrAttendanceDayByPair(ctx context.Context, arg DeleteHrAttendanceDayByPairParams) error {
	_, err := q.db.Exec(ctx, deleteHrAttendanceDayByPair, arg.EmployeeID, arg.Date)
	return err
}

const deleteHrAttendanceImport = `-- name: DeleteHrAttendanceImport :exec
DELETE FROM hr_attendance_import WHERE id = $1
`

func (q *Queries) DeleteHrAttendanceImport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHrAttendanceImport, id)
	return err
}

const deleteHrEmployeeLoan = `-- name: DeleteHrEmployeeLoan :exec
DELETE FROM hr_employee_loan WHERE id = $1
`

func (q *Queries) DeleteHrEmployeeLoan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHrEmployeeLoan, id)
	return err
}

const deleteHrPayroll = `-- name: DeleteHrPayroll :exec
DELETE FROM hr_payroll WHERE id = $1
`

func (q *Queries) DeleteHrPayroll(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHrPayroll, id)
	return err
}

const deleteHrPayrollPayment = `-- name: DeleteHrPayrollPayment :exec
DELETE FROM hr_payroll_payment WHERE id = $1
`

func (q *Queries) DeleteHrPayrollPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHrPayrollPayment, id)
	return err
}

const getHrAttendanceCorrection = `-- name: GetHrAttendanceCorrection :one
SELECT id, date, times, note, inserted_at, updated_at, employee_id, created_by_id FROM hr_attendance_correction WHERE id = $1
`

func (q *Queries) GetHrAttendanceCorrection(ctx context.Context, id uuid.UUID) (HrAttendanceCorrection, error) {
	row := q.db.QueryRow(ctx, getHrAttendanceCorrection, id)
	var i HrAttendanceCorrection
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Times,
		&i.Note,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
		&i.CreatedByID,
	)
	return i, err
}

const getHrAttendanceDay = `-- name: GetHrAttendanceDay :one
SELECT id, date, morning_in, morning_out, afternoon_in, afternoon_out, normal_hours, overtime_hours, bonus_workday, status, inserted_at, updated_at, employee_id FROM hr_attendance_day WHERE id = $1
`

func (q *Queries) GetHrAttendanceDay(ctx context.Context, id uuid.UUID) (HrAttendanceDay, error) {
	row := q.db.QueryRow(ctx, getHrAttendanceDay, id)
	var i HrAttendanceDay
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.MorningIn,
		&i.MorningOut,
		&i.AfternoonIn,
		&i.AfternoonOut,
		&i.NormalHours,
		&i.OvertimeHours,
		&i.BonusWorkday,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
	)
	return i, err
}

const getHrAttendanceImport = `-- name: GetHrAttendanceImport :one
SELECT id, status, error, total_rows, bad_rows, dup_rows, matched_rows, unmatched_rows, unmatched_detail, imported_count, skipped_existing_rows, skipped_unmatched_rows, auto_created_count, imported_at, inserted_at, updated_at, file_id, created_by_id, imported_by_id FROM hr_attendance_import WHERE id = $1
`

func (q *Queries) GetHrAttendanceImport(ctx context.Context, id uuid.UUID) (HrAttendanceImport, error) {
	row := q.db.QueryRow(ctx, getHrAttendanceImport, id)
	var i HrAttendanceImport
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.TotalRows,
		&i.BadRows,
		&i.DupRows,
		&i.MatchedRows,
		&i.UnmatchedRows,
		&i.UnmatchedDetail,
		&i.ImportedCount,
		&i.SkippedExistingRows,
		&i.SkippedUnmatchedRows,
		&i.AutoCreatedCount,
		&i.ImportedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.FileID,
		&i.CreatedByID,
		&i.ImportedByID,
	)
	return i, err
}

const getHrAttendancePunch = `-- name: GetHrAttendancePunch :one
SELECT id, attendance_no, punched_at, inserted_at, employee_id, import_id FROM hr_attendance_punch WHERE id = $1
`

func (q *Queries) GetHrAttendancePunch(ctx context.Context, id uuid.UUID) (HrAttendancePunch, error) {
	row := q.db.QueryRow(ctx, getHrAttendancePunch, id)
	var i HrAttendancePunch
	err := row.Scan(
		&i.ID,
		&i.AttendanceNo,
		&i.PunchedAt,
		&i.InsertedAt,
		&i.EmployeeID,
		&i.ImportID,
	)
	return i, err
}

const getHrEmployeeLoan = `-- name: GetHrEmployeeLoan :one
SELECT id, kind, occurred_on, amount, remarks, inserted_at, updated_at, employee_id, payroll_id, created_by_id FROM hr_employee_loan WHERE id = $1
`

func (q *Queries) GetHrEmployeeLoan(ctx context.Context, id uuid.UUID) (HrEmployeeLoan, error) {
	row := q.db.QueryRow(ctx, getHrEmployeeLoan, id)
	var i HrEmployeeLoan
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OccurredOn,
		&i.Amount,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
		&i.PayrollID,
		&i.CreatedByID,
	)
	return i, err
}

const getHrPayroll = `-- name: GetHrPayroll :one
SELECT id, month, workdays, attendance_days, missing_days, overtime_hours, daily_wage, base_amount, allowance, bonus, fine, loan_deduction, payable, status, remarks, inserted_at, updated_at, employee_id FROM hr_payroll WHERE id = $1
`

func (q *Queries) GetHrPayroll(ctx context.Context, id uuid.UUID) (HrPayroll, error) {
	row := q.db.QueryRow(ctx, getHrPayroll, id)
	var i HrPayroll
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Workdays,
		&i.AttendanceDays,
		&i.MissingDays,
		&i.OvertimeHours,
		&i.DailyWage,
		&i.BaseAmount,
		&i.Allowance,
		&i.Bonus,
		&i.Fine,
		&i.LoanDeduction,
		&i.Payable,
		&i.Status,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
	)
	return i, err
}

const getHrPayrollPayment = `-- name: GetHrPayrollPayment :one
SELECT id, month, paid_on, amount, kind, remarks, inserted_at, updated_at, payroll_id, employee_id, created_by_id FROM hr_payroll_payment WHERE id = $1
`

func (q *Queries) GetHrPayrollPayment(ctx context.Context, id uuid.UUID) (HrPayrollPayment, error) {
	row := q.db.QueryRow(ctx, getHrPayrollPayment, id)
	var i HrPayrollPayment
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.PaidOn,
		&i.Amount,
		&i.Kind,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.PayrollID,
		&i.EmployeeID,
		&i.CreatedByID,
	)
	return i, err
}

const importHrAttendanceBatch = `-- name: ImportHrAttendanceBatch :one
UPDATE hr_attendance_import SET
  status = 'imported', imported_count = $2, skipped_existing_rows = $3,
  skipped_unmatched_rows = $4, auto_created_count = $5, imported_at = $6,
  imported_by_id = $7, updated_at = $6
WHERE id = $1
RETURNING id, status, error, total_rows, bad_rows, dup_rows, matched_rows, unmatched_rows, unmatched_detail, imported_count, skipped_existing_rows, skipped_unmatched_rows, auto_created_count, imported_at, inserted_at, updated_at, file_id, created_by_id, imported_by_id
`

type ImportHrAttendanceBatchParams struct {
	ID                   uuid.UUID        `db:"id" json:"id"`
	ImportedCount        pgtype.Int8      `db:"imported_count" json:"imported_count"`
	SkippedExistingRows  pgtype.Int8      `db:"skipped_existing_rows" json:"skipped_existing_rows"`
	SkippedUnmatchedRows pgtype.Int8      `db:"skipped_unmatched_rows" json:"skipped_unmatched_rows"`
	AutoCreatedCount     pgtype.Int8      `db:"auto_created_count" json:"auto_created_count"`
	ImportedAt           pgtype.Timestamp `db:"imported_at" json:"imported_at"`
	ImportedByID         *uuid.UUID       `db:"imported_by_id" json:"imported_by_id"`
}

func (q *Queries) ImportHrAttendanceBatch(ctx context.Context, arg ImportHrAttendanceBatchParams) (HrAttendanceImport, error) {
	row := q.db.QueryRow(ctx, importHrAttendanceBatch,
		arg.ID,
		arg.ImportedCount,
		arg.SkippedExistingRows,
		arg.SkippedUnmatchedRows,
		arg.AutoCreatedCount,
		arg.ImportedAt,
		arg.ImportedByID,
	)
	var i HrAttendanceImport
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.TotalRows,
		&i.BadRows,
		&i.DupRows,
		&i.MatchedRows,
		&i.UnmatchedRows,
		&i.UnmatchedDetail,
		&i.ImportedCount,
		&i.SkippedExistingRows,
		&i.SkippedUnmatchedRows,
		&i.AutoCreatedCount,
		&i.ImportedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.FileID,
		&i.CreatedByID,
		&i.ImportedByID,
	)
	return i, err
}

const lockHrAttendanceCorrection = `-- name: LockHrAttendanceCorrection :one
SELECT id, date, times, note, inserted_at, updated_at, employee_id, created_by_id FROM hr_attendance_correction WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockHrAttendanceCorrection(ctx context.Context, id uuid.UUID) (HrAttendanceCorrection, error) {
	row := q.db.QueryRow(ctx, lockHrAttendanceCorrection, id)
	var i HrAttendanceCorrection
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Times,
		&i.Note,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
		&i.CreatedByID,
	)
	return i, err
}

const lockHrAttendanceImport = `-- name: LockHrAttendanceImport :one
SELECT id, status, error, total_rows, bad_rows, dup_rows, matched_rows, unmatched_rows, unmatched_detail, imported_count, skipped_existing_rows, skipped_unmatched_rows, auto_created_count, imported_at, inserted_at, updated_at, file_id, created_by_id, imported_by_id FROM hr_attendance_import WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockHrAttendanceImport(ctx context.Context, id uuid.UUID) (HrAttendanceImport, error) {
	row := q.db.QueryRow(ctx, lockHrAttendanceImport, id)
	var i HrAttendanceImport
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.TotalRows,
		&i.BadRows,
		&i.DupRows,
		&i.MatchedRows,
		&i.UnmatchedRows,
		&i.UnmatchedDetail,
		&i.ImportedCount,
		&i.SkippedExistingRows,
		&i.SkippedUnmatchedRows,
		&i.AutoCreatedCount,
		&i.ImportedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.FileID,
		&i.CreatedByID,
		&i.ImportedByID,
	)
	return i, err
}

const lockHrEmployeeLoan = `-- name: LockHrEmployeeLoan :one
SELECT id, kind, occurred_on, amount, remarks, inserted_at, updated_at, employee_id, payroll_id, created_by_id FROM hr_employee_loan WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockHrEmployeeLoan(ctx context.Context, id uuid.UUID) (HrEmployeeLoan, error) {
	row := q.db.QueryRow(ctx, lockHrEmployeeLoan, id)
	var i HrEmployeeLoan
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OccurredOn,
		&i.Amount,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
		&i.PayrollID,
		&i.CreatedByID,
	)
	return i, err
}

const lockHrPayroll = `-- name: LockHrPayroll :one
SELECT id, month, workdays, attendance_days, missing_days, overtime_hours, daily_wage, base_amount, allowance, bonus, fine, loan_deduction, payable, status, remarks, inserted_at, updated_at, employee_id FROM hr_payroll WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockHrPayroll(ctx context.Context, id uuid.UUID) (HrPayroll, error) {
	row := q.db.QueryRow(ctx, lockHrPayroll, id)
	var i HrPayroll
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Workdays,
		&i.AttendanceDays,
		&i.MissingDays,
		&i.OvertimeHours,
		&i.DailyWage,
		&i.BaseAmount,
		&i.Allowance,
		&i.Bonus,
		&i.Fine,
		&i.LoanDeduction,
		&i.Payable,
		&i.Status,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
	)
	return i, err
}

const lockHrPayrollPayment = `-- name: LockHrPayrollPayment :one
SELECT id, month, paid_on, amount, kind, remarks, inserted_at, updated_at, payroll_id, employee_id, created_by_id FROM hr_payroll_payment WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockHrPayrollPayment(ctx context.Context, id uuid.UUID) (HrPayrollPayment, error) {
	row := q.db.QueryRow(ctx, lockHrPayrollPayment, id)
	var i HrPayrollPayment
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.PaidOn,
		&i.Amount,
		&i.Kind,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.PayrollID,
		&i.EmployeeID,
		&i.CreatedByID,
	)
	return i, err
}

const upsertHrAttendanceDay = `-- name: UpsertHrAttendanceDay :one
INSERT INTO hr_attendance_day (
  date, morning_in, morning_out, afternoon_in, afternoon_out, normal_hours,
  overtime_hours, bonus_workday, status, employee_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (employee_id,date) DO UPDATE SET
  morning_in=excluded.morning_in, morning_out=excluded.morning_out,
  afternoon_in=excluded.afternoon_in, afternoon_out=excluded.afternoon_out,
  normal_hours=excluded.normal_hours, overtime_hours=excluded.overtime_hours,
  bonus_workday=excluded.bonus_workday, status=excluded.status,
  updated_at=(now() AT TIME ZONE 'utc')
RETURNING id, date, morning_in, morning_out, afternoon_in, afternoon_out, normal_hours, overtime_hours, bonus_workday, status, inserted_at, updated_at, employee_id
`

type UpsertHrAttendanceDayParams struct {
	Date          pgtype.Date     `db:"date" json:"date"`
	MorningIn     pgtype.Time     `db:"morning_in" json:"morning_in"`
	MorningOut    pgtype.Time     `db:"morning_out" json:"morning_out"`
	AfternoonIn   pgtype.Time     `db:"afternoon_in" json:"afternoon_in"`
	AfternoonOut  pgtype.Time     `db:"afternoon_out" json:"afternoon_out"`
	NormalHours   decimal.Decimal `db:"normal_hours" json:"normal_hours"`
	OvertimeHours decimal.Decimal `db:"overtime_hours" json:"overtime_hours"`
	BonusWorkday  decimal.Decimal `db:"bonus_workday" json:"bonus_workday"`
	Status        string          `db:"status" json:"status"`
	EmployeeID    uuid.UUID       `db:"employee_id" json:"employee_id"`
}

func (q *Queries) UpsertHrAttendanceDay(ctx context.Context, arg UpsertHrAttendanceDayParams) (HrAttendanceDay, error) {
	row := q.db.QueryRow(ctx, upsertHrAttendanceDay,
		arg.Date,
		arg.MorningIn,
		arg.MorningOut,
		arg.AfternoonIn,
		arg.AfternoonOut,
		arg.NormalHours,
		arg.OvertimeHours,
		arg.BonusWorkday,
		arg.Status,
		arg.EmployeeID,
	)
	var i HrAttendanceDay
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.MorningIn,
		&i.MorningOut,
		&i.AfternoonIn,
		&i.AfternoonOut,
		&i.NormalHours,
		&i.OvertimeHours,
		&i.BonusWorkday,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmployeeID,
	)
	return i, err
}
