// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_entry.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countStockEntries = `-- name: CountStockEntries :one
SELECT count(*)
FROM inv_stock_entry
WHERE ($1::boolean OR company_id = ANY($2::uuid[]))
`

type CountStockEntriesParams struct {
	ScopeBypass bool        `db:"scope_bypass" json:"scope_bypass"`
	CompanyIds  []uuid.UUID `db:"company_ids" json:"company_ids"`
}

func (q *Queries) CountStockEntries(ctx context.Context, arg CountStockEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStockEntries, arg.ScopeBypass, arg.CompanyIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStockEntry = `-- name: GetStockEntry :one
SELECT id, seq, quantity, posting_date, voucher_type, voucher_id, voucher_no,
       is_cancelled, cancelled_at, remarks, inserted_at,
       company_id, warehouse_id, material_id
FROM inv_stock_entry
WHERE id = $1
`

type GetStockEntryRow struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Seq         int64            `db:"seq" json:"seq"`
	Quantity    decimal.Decimal  `db:"quantity" json:"quantity"`
	PostingDate pgtype.Date      `db:"posting_date" json:"posting_date"`
	VoucherType string           `db:"voucher_type" json:"voucher_type"`
	VoucherID   uuid.UUID        `db:"voucher_id" json:"voucher_id"`
	VoucherNo   string           `db:"voucher_no" json:"voucher_no"`
	IsCancelled bool             `db:"is_cancelled" json:"is_cancelled"`
	CancelledAt pgtype.Timestamp `db:"cancelled_at" json:"cancelled_at"`
	Remarks     pgtype.Text      `db:"remarks" json:"remarks"`
	InsertedAt  pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	CompanyID   uuid.UUID        `db:"company_id" json:"company_id"`
	WarehouseID uuid.UUID        `db:"warehouse_id" json:"warehouse_id"`
	MaterialID  uuid.UUID        `db:"material_id" json:"material_id"`
}

func (q *Queries) GetStockEntry(ctx context.Context, id uuid.UUID) (GetStockEntryRow, error) {
	row := q.db.QueryRow(ctx, getStockEntry, id)
	var i GetStockEntryRow
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Quantity,
		&i.PostingDate,
		&i.VoucherType,
		&i.VoucherID,
		&i.VoucherNo,
		&i.IsCancelled,
		&i.CancelledAt,
		&i.Remarks,
		&i.InsertedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.MaterialID,
	)
	return i, err
}

const listStockEntries = `-- name: ListStockEntries :many
SELECT id, seq, quantity, posting_date, voucher_type, voucher_id, voucher_no,
       is_cancelled, cancelled_at, remarks, inserted_at,
       company_id, warehouse_id, material_id
FROM inv_stock_entry
WHERE ($1::boolean OR company_id = ANY($2::uuid[]))
ORDER BY seq ASC
LIMIT $4 OFFSET $3
`

type ListStockEntriesParams struct {
	ScopeBypass bool        `db:"scope_bypass" json:"scope_bypass"`
	CompanyIds  []uuid.UUID `db:"company_ids" json:"company_ids"`
	RowOffset   int32       `db:"row_offset" json:"row_offset"`
	RowLimit    int32       `db:"row_limit" json:"row_limit"`
}

type ListStockEntriesRow struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Seq         int64            `db:"seq" json:"seq"`
	Quantity    decimal.Decimal  `db:"quantity" json:"quantity"`
	PostingDate pgtype.Date      `db:"posting_date" json:"posting_date"`
	VoucherType string           `db:"voucher_type" json:"voucher_type"`
	VoucherID   uuid.UUID        `db:"voucher_id" json:"voucher_id"`
	VoucherNo   string           `db:"voucher_no" json:"voucher_no"`
	IsCancelled bool             `db:"is_cancelled" json:"is_cancelled"`
	CancelledAt pgtype.Timestamp `db:"cancelled_at" json:"cancelled_at"`
	Remarks     pgtype.Text      `db:"remarks" json:"remarks"`
	InsertedAt  pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	CompanyID   uuid.UUID        `db:"company_id" json:"company_id"`
	WarehouseID uuid.UUID        `db:"warehouse_id" json:"warehouse_id"`
	MaterialID  uuid.UUID        `db:"material_id" json:"material_id"`
}

func (q *Queries) ListStockEntries(ctx context.Context, arg ListStockEntriesParams) ([]ListStockEntriesRow, error) {
	rows, err := q.db.Query(ctx, listStockEntries,
		arg.ScopeBypass,
		arg.CompanyIds,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockEntriesRow{}
	for rows.Next() {
		var i ListStockEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Quantity,
			&i.PostingDate,
			&i.VoucherType,
			&i.VoucherID,
			&i.VoucherNo,
			&i.IsCancelled,
			&i.CancelledAt,
			&i.Remarks,
			&i.InsertedAt,
			&i.CompanyID,
			&i.WarehouseID,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
