// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_ops.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const closeSystemTodos = `-- name: CloseSystemTodos :many
UPDATE sys_todo
SET status = 'closed',
    closed_reason = $1,
    closed_at = $2,
    updated_at = $2
WHERE source_type = $3
  AND source_id = $4
  AND status = 'active'
RETURNING id, type, source_type, source_id, source_no, party_type, party_id,
          amount, status, closed_reason, source_changed_at, closed_at,
          inserted_at, updated_at, company_id, created_by_id
`

type CloseSystemTodosParams struct {
	ClosedReason pgtype.Text      `db:"closed_reason" json:"closed_reason"`
	ClosedAt     pgtype.Timestamp `db:"closed_at" json:"closed_at"`
	SourceType   string           `db:"source_type" json:"source_type"`
	SourceID     uuid.UUID        `db:"source_id" json:"source_id"`
}

func (q *Queries) CloseSystemTodos(ctx context.Context, arg CloseSystemTodosParams) ([]SysTodo, error) {
	rows, err := q.db.Query(ctx, closeSystemTodos,
		arg.ClosedReason,
		arg.ClosedAt,
		arg.SourceType,
		arg.SourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysTodo{}
	for rows.Next() {
		var i SysTodo
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.SourceType,
			&i.SourceID,
			&i.SourceNo,
			&i.PartyType,
			&i.PartyID,
			&i.Amount,
			&i.Status,
			&i.ClosedReason,
			&i.SourceChangedAt,
			&i.ClosedAt,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.CompanyID,
			&i.CreatedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemAuditLog = `-- name: GetSystemAuditLog :one

SELECT id, inserted_at, resource, record_id, record_label, action_type,
       action_name, actor_id, actor_name, company_id, changes
FROM sys_audit_log
WHERE id = $1
`

type GetSystemAuditLogRow struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	InsertedAt  pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	Resource    string           `db:"resource" json:"resource"`
	RecordID    uuid.UUID        `db:"record_id" json:"record_id"`
	RecordLabel pgtype.Text      `db:"record_label" json:"record_label"`
	ActionType  string           `db:"action_type" json:"action_type"`
	ActionName  string           `db:"action_name" json:"action_name"`
	ActorID     *uuid.UUID       `db:"actor_id" json:"actor_id"`
	ActorName   pgtype.Text      `db:"actor_name" json:"actor_name"`
	CompanyID   *uuid.UUID       `db:"company_id" json:"company_id"`
	Changes     []byte           `db:"changes" json:"changes"`
}

// PR-2.18 system operations query catalogue.
// Dynamic list filters/sorts are assembled from ResourceMeta by filterbuild;
// these named statements document and validate the fixed transactional seams.
func (q *Queries) GetSystemAuditLog(ctx context.Context, id uuid.UUID) (GetSystemAuditLogRow, error) {
	row := q.db.QueryRow(ctx, getSystemAuditLog, id)
	var i GetSystemAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.InsertedAt,
		&i.Resource,
		&i.RecordID,
		&i.RecordLabel,
		&i.ActionType,
		&i.ActionName,
		&i.ActorID,
		&i.ActorName,
		&i.CompanyID,
		&i.Changes,
	)
	return i, err
}

const openSystemTodo = `-- name: OpenSystemTodo :one
INSERT INTO sys_todo (
  type, source_type, source_id, source_no, party_type, party_id, amount,
  status, source_changed_at, company_id, created_by_id
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, 'active', $8,
  $9, $10
)
RETURNING id, type, source_type, source_id, source_no, party_type, party_id,
          amount, status, closed_reason, source_changed_at, closed_at,
          inserted_at, updated_at, company_id, created_by_id
`

type OpenSystemTodoParams struct {
	Type            string           `db:"type" json:"type"`
	SourceType      string           `db:"source_type" json:"source_type"`
	SourceID        uuid.UUID        `db:"source_id" json:"source_id"`
	SourceNo        string           `db:"source_no" json:"source_no"`
	PartyType       string           `db:"party_type" json:"party_type"`
	PartyID         uuid.UUID        `db:"party_id" json:"party_id"`
	Amount          decimal.Decimal  `db:"amount" json:"amount"`
	SourceChangedAt pgtype.Timestamp `db:"source_changed_at" json:"source_changed_at"`
	CompanyID       uuid.UUID        `db:"company_id" json:"company_id"`
	CreatedByID     *uuid.UUID       `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) OpenSystemTodo(ctx context.Context, arg OpenSystemTodoParams) (SysTodo, error) {
	row := q.db.QueryRow(ctx, openSystemTodo,
		arg.Type,
		arg.SourceType,
		arg.SourceID,
		arg.SourceNo,
		arg.PartyType,
		arg.PartyID,
		arg.Amount,
		arg.SourceChangedAt,
		arg.CompanyID,
		arg.CreatedByID,
	)
	var i SysTodo
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SourceType,
		&i.SourceID,
		&i.SourceNo,
		&i.PartyType,
		&i.PartyID,
		&i.Amount,
		&i.Status,
		&i.ClosedReason,
		&i.SourceChangedAt,
		&i.ClosedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.CreatedByID,
	)
	return i, err
}

const touchSystemTodo = `-- name: TouchSystemTodo :exec
UPDATE sys_todo
SET updated_at = $1
WHERE id = $2
`

type TouchSystemTodoParams struct {
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ID        uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) TouchSystemTodo(ctx context.Context, arg TouchSystemTodoParams) error {
	_, err := q.db.Exec(ctx, touchSystemTodo, arg.UpdatedAt, arg.ID)
	return err
}

const upsertSystemTodoState = `-- name: UpsertSystemTodoState :one
INSERT INTO sys_todo_state (
  todo_id, user_id, read_at, dismissed_at, reset_basis_at
) VALUES (
  $1, $2, $3,
  $4, $5
)
ON CONFLICT (todo_id, user_id) DO UPDATE
SET read_at = COALESCE(EXCLUDED.read_at, sys_todo_state.read_at),
    dismissed_at = COALESCE(EXCLUDED.dismissed_at, sys_todo_state.dismissed_at),
    reset_basis_at = COALESCE(EXCLUDED.reset_basis_at, sys_todo_state.reset_basis_at),
    updated_at = (now() AT TIME ZONE 'utc')
RETURNING id, read_at, dismissed_at, reset_basis_at, inserted_at, updated_at,
          todo_id, user_id
`

type UpsertSystemTodoStateParams struct {
	TodoID       uuid.UUID        `db:"todo_id" json:"todo_id"`
	UserID       uuid.UUID        `db:"user_id" json:"user_id"`
	ReadAt       pgtype.Timestamp `db:"read_at" json:"read_at"`
	DismissedAt  pgtype.Timestamp `db:"dismissed_at" json:"dismissed_at"`
	ResetBasisAt pgtype.Timestamp `db:"reset_basis_at" json:"reset_basis_at"`
}

func (q *Queries) UpsertSystemTodoState(ctx context.Context, arg UpsertSystemTodoStateParams) (SysTodoState, error) {
	row := q.db.QueryRow(ctx, upsertSystemTodoState,
		arg.TodoID,
		arg.UserID,
		arg.ReadAt,
		arg.DismissedAt,
		arg.ResetBasisAt,
	)
	var i SysTodoState
	err := row.Scan(
		&i.ID,
		&i.ReadAt,
		&i.DismissedAt,
		&i.ResetBasisAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.TodoID,
		&i.UserID,
	)
	return i, err
}
