// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trading_order.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getTradingOrderCompany = `-- name: GetTradingOrderCompany :one

SELECT id, base_currency_id
FROM bas_company
WHERE id = $1
`

type GetTradingOrderCompanyRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	BaseCurrencyID uuid.UUID `db:"base_currency_id" json:"base_currency_id"`
}

// Fixed persistence helpers for the shared trading/order module. Side-specific
// aggregate queries remain in the module because sqlc cannot parameterize table
// identifiers; all identifiers there come from the compile-time side spec.
func (q *Queries) GetTradingOrderCompany(ctx context.Context, id uuid.UUID) (GetTradingOrderCompanyRow, error) {
	row := q.db.QueryRow(ctx, getTradingOrderCompany, id)
	var i GetTradingOrderCompanyRow
	err := row.Scan(&i.ID, &i.BaseCurrencyID)
	return i, err
}

const getTradingOrderMaterial = `-- name: GetTradingOrderMaterial :one
SELECT m.id,
       m.code,
       m.name,
       m.spec,
       m.customer_part_no,
       m.default_unit_id,
       m.is_customer_material,
       m.customer_id,
       u.id AS unit_id,
       u.name AS unit_name,
       mu.factor,
       (m.default_unit_id = u.id OR mu.id IS NOT NULL)::boolean AS unit_allowed
FROM inv_material m
JOIN bas_unit u ON u.id = $1::uuid
LEFT JOIN inv_material_unit mu
  ON mu.material_id = m.id AND mu.unit_id = u.id
WHERE m.id = $2::uuid
`

type GetTradingOrderMaterialParams struct {
	UnitID     uuid.UUID `db:"unit_id" json:"unit_id"`
	MaterialID uuid.UUID `db:"material_id" json:"material_id"`
}

type GetTradingOrderMaterialRow struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	Code               string         `db:"code" json:"code"`
	Name               string         `db:"name" json:"name"`
	Spec               pgtype.Text    `db:"spec" json:"spec"`
	CustomerPartNo     pgtype.Text    `db:"customer_part_no" json:"customer_part_no"`
	DefaultUnitID      uuid.UUID      `db:"default_unit_id" json:"default_unit_id"`
	IsCustomerMaterial bool           `db:"is_customer_material" json:"is_customer_material"`
	CustomerID         *uuid.UUID     `db:"customer_id" json:"customer_id"`
	UnitID             uuid.UUID      `db:"unit_id" json:"unit_id"`
	UnitName           string         `db:"unit_name" json:"unit_name"`
	Factor             pgtype.Numeric `db:"factor" json:"factor"`
	UnitAllowed        bool           `db:"unit_allowed" json:"unit_allowed"`
}

func (q *Queries) GetTradingOrderMaterial(ctx context.Context, arg GetTradingOrderMaterialParams) (GetTradingOrderMaterialRow, error) {
	row := q.db.QueryRow(ctx, getTradingOrderMaterial, arg.UnitID, arg.MaterialID)
	var i GetTradingOrderMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CustomerPartNo,
		&i.DefaultUnitID,
		&i.IsCustomerMaterial,
		&i.CustomerID,
		&i.UnitID,
		&i.UnitName,
		&i.Factor,
		&i.UnitAllowed,
	)
	return i, err
}

const listTradingOrderDemandPool = `-- name: ListTradingOrderDemandPool :many
SELECT i.id,
       i.demand_id,
       d.demand_no,
       i.idx,
       i.need_date,
       i.company_id,
       i.material_id,
       i.unit_id,
       i.material_code,
       i.material_name,
       i.material_spec,
       i.unit_name,
       i.base_qty,
       i.ordered_qty,
       i.base_qty - i.ordered_qty AS remaining_base_qty,
       CASE
         WHEN i.unit_id = m.default_unit_id THEN i.base_qty - i.ordered_qty
         ELSE (i.base_qty - i.ordered_qty) * mu.factor
       END AS suggested_qty
FROM mfg_demand_item i
JOIN mfg_demand d ON d.id = i.demand_id
JOIN inv_material m ON m.id = i.material_id
LEFT JOIN inv_material_unit mu
  ON mu.material_id = i.material_id AND mu.unit_id = i.unit_id
WHERE i.company_id = $1::uuid
  AND d.status = 'confirmed'
  AND i.status <> 'completed'
  AND i.fulfillment_method = $2::text
  AND i.ordered_qty < i.base_qty
ORDER BY i.need_date ASC NULLS LAST, i.inserted_at ASC, i.id ASC
LIMIT $3
`

type ListTradingOrderDemandPoolParams struct {
	CompanyID         uuid.UUID `db:"company_id" json:"company_id"`
	FulfillmentMethod string    `db:"fulfillment_method" json:"fulfillment_method"`
	RowLimit          int32     `db:"row_limit" json:"row_limit"`
}

type ListTradingOrderDemandPoolRow struct {
	ID               uuid.UUID       `db:"id" json:"id"`
	DemandID         uuid.UUID       `db:"demand_id" json:"demand_id"`
	DemandNo         string          `db:"demand_no" json:"demand_no"`
	Idx              int64           `db:"idx" json:"idx"`
	NeedDate         pgtype.Date     `db:"need_date" json:"need_date"`
	CompanyID        uuid.UUID       `db:"company_id" json:"company_id"`
	MaterialID       uuid.UUID       `db:"material_id" json:"material_id"`
	UnitID           uuid.UUID       `db:"unit_id" json:"unit_id"`
	MaterialCode     string          `db:"material_code" json:"material_code"`
	MaterialName     string          `db:"material_name" json:"material_name"`
	MaterialSpec     pgtype.Text     `db:"material_spec" json:"material_spec"`
	UnitName         string          `db:"unit_name" json:"unit_name"`
	BaseQty          decimal.Decimal `db:"base_qty" json:"base_qty"`
	OrderedQty       decimal.Decimal `db:"ordered_qty" json:"ordered_qty"`
	RemainingBaseQty int32           `db:"remaining_base_qty" json:"remaining_base_qty"`
	SuggestedQty     interface{}     `db:"suggested_qty" json:"suggested_qty"`
}

func (q *Queries) ListTradingOrderDemandPool(ctx context.Context, arg ListTradingOrderDemandPoolParams) ([]ListTradingOrderDemandPoolRow, error) {
	rows, err := q.db.Query(ctx, listTradingOrderDemandPool, arg.CompanyID, arg.FulfillmentMethod, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTradingOrderDemandPoolRow{}
	for rows.Next() {
		var i ListTradingOrderDemandPoolRow
		if err := rows.Scan(
			&i.ID,
			&i.DemandID,
			&i.DemandNo,
			&i.Idx,
			&i.NeedDate,
			&i.CompanyID,
			&i.MaterialID,
			&i.UnitID,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.BaseQty,
			&i.OrderedQty,
			&i.RemainingBaseQty,
			&i.SuggestedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previewTradingOrderBOMByproducts = `-- name: PreviewTradingOrderBOMByproducts :many
SELECT x.material_id,
       m.code AS material_code,
       m.name AS material_name,
       x.unit_id,
       u.name AS unit_name,
       x.quantity * $1::numeric AS quantity,
       x.note
FROM mfg_bom_byproduct x
JOIN inv_material m ON m.id = x.material_id
JOIN bas_unit u ON u.id = x.unit_id
WHERE x.bom_id = $2::uuid
ORDER BY x.inserted_at, x.id
`

type PreviewTradingOrderBOMByproductsParams struct {
	OrderQty decimal.Decimal `db:"order_qty" json:"order_qty"`
	BomID    uuid.UUID       `db:"bom_id" json:"bom_id"`
}

type PreviewTradingOrderBOMByproductsRow struct {
	MaterialID   uuid.UUID   `db:"material_id" json:"material_id"`
	MaterialCode string      `db:"material_code" json:"material_code"`
	MaterialName string      `db:"material_name" json:"material_name"`
	UnitID       uuid.UUID   `db:"unit_id" json:"unit_id"`
	UnitName     string      `db:"unit_name" json:"unit_name"`
	Quantity     int32       `db:"quantity" json:"quantity"`
	Note         pgtype.Text `db:"note" json:"note"`
}

func (q *Queries) PreviewTradingOrderBOMByproducts(ctx context.Context, arg PreviewTradingOrderBOMByproductsParams) ([]PreviewTradingOrderBOMByproductsRow, error) {
	rows, err := q.db.Query(ctx, previewTradingOrderBOMByproducts, arg.OrderQty, arg.BomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PreviewTradingOrderBOMByproductsRow{}
	for rows.Next() {
		var i PreviewTradingOrderBOMByproductsRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialCode,
			&i.MaterialName,
			&i.UnitID,
			&i.UnitName,
			&i.Quantity,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previewTradingOrderBOMMaterials = `-- name: PreviewTradingOrderBOMMaterials :many
SELECT x.material_id,
       m.code AS material_code,
       m.name AS material_name,
       x.unit_id,
       u.name AS unit_name,
       x.quantity * (1 + coalesce(x.loss_rate, 0)) * $1::numeric AS quantity,
       x.note
FROM mfg_bom_component x
JOIN inv_material m ON m.id = x.material_id
JOIN bas_unit u ON u.id = x.unit_id
WHERE x.bom_id = $2::uuid
ORDER BY x.inserted_at, x.id
`

type PreviewTradingOrderBOMMaterialsParams struct {
	OrderQty decimal.Decimal `db:"order_qty" json:"order_qty"`
	BomID    uuid.UUID       `db:"bom_id" json:"bom_id"`
}

type PreviewTradingOrderBOMMaterialsRow struct {
	MaterialID   uuid.UUID   `db:"material_id" json:"material_id"`
	MaterialCode string      `db:"material_code" json:"material_code"`
	MaterialName string      `db:"material_name" json:"material_name"`
	UnitID       uuid.UUID   `db:"unit_id" json:"unit_id"`
	UnitName     string      `db:"unit_name" json:"unit_name"`
	Quantity     int32       `db:"quantity" json:"quantity"`
	Note         pgtype.Text `db:"note" json:"note"`
}

func (q *Queries) PreviewTradingOrderBOMMaterials(ctx context.Context, arg PreviewTradingOrderBOMMaterialsParams) ([]PreviewTradingOrderBOMMaterialsRow, error) {
	rows, err := q.db.Query(ctx, previewTradingOrderBOMMaterials, arg.OrderQty, arg.BomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PreviewTradingOrderBOMMaterialsRow{}
	for rows.Next() {
		var i PreviewTradingOrderBOMMaterialsRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialCode,
			&i.MaterialName,
			&i.UnitID,
			&i.UnitName,
			&i.Quantity,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tradingOrderPartyExists = `-- name: TradingOrderPartyExists :one
SELECT CASE $1::text
  WHEN 'supplier' THEN EXISTS(
    SELECT 1 FROM pur_supplier WHERE id = $2::uuid
  )
  WHEN 'customer' THEN EXISTS(
    SELECT 1 FROM sal_customers WHERE id = $2::uuid
  )
  WHEN 'company' THEN EXISTS(
    SELECT 1 FROM bas_company WHERE id = $2::uuid
  )
  ELSE false
END::boolean
`

type TradingOrderPartyExistsParams struct {
	PartyType string    `db:"party_type" json:"party_type"`
	PartyID   uuid.UUID `db:"party_id" json:"party_id"`
}

func (q *Queries) TradingOrderPartyExists(ctx context.Context, arg TradingOrderPartyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tradingOrderPartyExists, arg.PartyType, arg.PartyID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
