import type { ResourceMeta } from '../meta/types.ts'
import { SYS_STORAGE } from './permissions.ts'

export const FILE_RESOURCE_NAME = 'sysFiles'
export const STORAGE_RESOURCE_NAME = 'sysStorages'

export function fileResourceMeta(): ResourceMeta {
  return {
    name: FILE_RESOURCE_NAME,
    permissionPrefix: 'sys.file',
    permissionLabel: '附件',
    table: 'sys_file',
    print: true,
    audit: { enabled: true },
    fields: [
      { name: 'id', apiName: 'id', dbColumn: 'id', type: 'uuid', label: 'id', readonly: true, sortable: true },
      {
        name: 'storage',
        apiName: 'storage',
        dbColumn: 'storage',
        type: 'string',
        label: '存储接入',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'key',
        apiName: 'key',
        dbColumn: 'key',
        type: 'string',
        label: '对象键',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'filename',
        apiName: 'filename',
        dbColumn: 'filename',
        type: 'string',
        label: '文件名',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'content_type',
        apiName: 'contentType',
        dbColumn: 'content_type',
        type: 'string',
        label: 'MIME 类型',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'size',
        apiName: 'size',
        dbColumn: 'size',
        type: 'integer',
        label: '大小',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'sha256',
        apiName: 'sha256',
        dbColumn: 'sha256',
        type: 'string',
        label: 'SHA-256 摘要',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'inserted_at',
        apiName: 'insertedAt',
        dbColumn: 'inserted_at',
        type: 'datetime',
        label: '上传时间',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'uploaded_by_id',
        apiName: 'uploadedById',
        dbColumn: 'uploaded_by_id',
        type: 'uuid',
        label: '上传人',
        readonly: true,
        filterable: true,
        ref: { resource: 'sysUsers', relation: 'uploadedBy', labelField: 'name' },
      },
    ],
    actions: [
      { key: 'read', label: '查看', scope: 'both' },
      { key: 'create', label: '上传', scope: 'both' },
      { key: 'delete', label: '删除', scope: 'row', isDanger: true },
    ],
    form: { exclude: ['id', 'storage', 'key', 'insertedAt'] },
    destroyMutation: 'destroySysFile',
  }
}

export function storageResourceMeta(): ResourceMeta {
  const kinds = [
    { value: 'LOCAL', label: '本地磁盘' },
    { value: 'S3', label: 'S3 兼容' },
    { value: 'OSS', label: '阿里云 OSS' },
  ]
  return {
    name: STORAGE_RESOURCE_NAME,
    permissionPrefix: SYS_STORAGE.prefix,
    permissionLabel: '存储接入',
    table: 'sys_storage',
    print: true,
    audit: { enabled: true, sensitiveFields: ['secret_access_key'] },
    fields: [
      { name: 'id', apiName: 'id', dbColumn: 'id', type: 'uuid', label: 'id', readonly: true, sortable: true },
      {
        name: 'name',
        apiName: 'name',
        dbColumn: 'name',
        type: 'string',
        label: '接入名',
        required: true,
        createOnly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'label',
        apiName: 'label',
        dbColumn: 'label',
        type: 'string',
        label: '显示名',
        required: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'kind',
        apiName: 'kind',
        dbColumn: 'kind',
        type: 'enum',
        label: '存储类型',
        required: true,
        createOnly: true,
        enumOptions: kinds,
        filterable: true,
        sortable: true,
      },
      {
        name: 'root',
        apiName: 'root',
        dbColumn: 'root',
        type: 'string',
        label: '根目录',
        filterable: true,
        sortable: true,
      },
      {
        name: 'endpoint',
        apiName: 'endpoint',
        dbColumn: 'endpoint',
        type: 'string',
        label: '服务地址',
        filterable: true,
        sortable: true,
      },
      {
        name: 'region',
        apiName: 'region',
        dbColumn: 'region',
        type: 'string',
        label: '区域',
        filterable: true,
        sortable: true,
      },
      {
        name: 'bucket',
        apiName: 'bucket',
        dbColumn: 'bucket',
        type: 'string',
        label: 'Bucket',
        filterable: true,
        sortable: true,
      },
      {
        name: 'prefix',
        apiName: 'prefix',
        dbColumn: 'prefix',
        type: 'string',
        label: '对象键前缀',
        filterable: true,
        sortable: true,
      },
      {
        name: 'access_key_id',
        apiName: 'accessKeyId',
        dbColumn: 'access_key_id',
        type: 'string',
        label: 'Access Key ID',
        filterable: true,
        sortable: true,
      },
      {
        name: 'secret_access_key',
        apiName: 'secretAccessKey',
        dbColumn: 'secret_access_key',
        type: 'string',
        label: 'Secret Access Key',
        sensitive: true,
      },
      {
        name: 'builtin',
        apiName: 'builtin',
        dbColumn: 'builtin',
        type: 'boolean',
        label: '内置',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'is_default',
        apiName: 'isDefault',
        dbColumn: 'is_default',
        type: 'boolean',
        label: '全局默认',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'inserted_at',
        apiName: 'insertedAt',
        dbColumn: 'inserted_at',
        type: 'datetime',
        label: '创建时间',
        readonly: true,
        filterable: true,
        sortable: true,
      },
      {
        name: 'updated_at',
        apiName: 'updatedAt',
        dbColumn: 'updated_at',
        type: 'datetime',
        label: '更新时间',
        readonly: true,
        filterable: true,
        sortable: true,
      },
    ],
    actions: [
      { key: 'read', label: '查看', scope: 'both' },
      { key: 'create', label: '新增', scope: 'both' },
      { key: 'update', label: '编辑', scope: 'row' },
      { key: 'delete', label: '删除', scope: 'row', isDanger: true },
      {
        // 语义 key=setDefault；requiredCapability=update（与 SYS_STORAGE.update 对齐）
        key: 'setDefault',
        label: '设为默认',
        scope: 'row',
        commandTarget: 'row',
        permissionAction: 'update',
        // v1 transport 兼容字段；工单 11 随旧 Grid action 删除
        http: { method: 'POST', path: '/api/v1/system/storages/{id}/set-default' },
      },
    ],
    form: {
      exclude: ['id', 'insertedAt', 'updatedAt'],
      fields: {
        name: { edit: 'createOnly' },
        kind: { edit: 'createOnly' },
        builtin: { edit: 'readOnly' },
        isDefault: { edit: 'readOnly' },
      },
    },
    destroyMutation: 'destroySysStorage',
  }
}
