// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const credentialsByUsername = `-- name: CredentialsByUsername :one
SELECT id, username::text AS username, name, hashed_password
FROM sys_user
WHERE username = $1
`

type CredentialsByUsernameRow struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	Username       string      `db:"username" json:"username"`
	Name           pgtype.Text `db:"name" json:"name"`
	HashedPassword string      `db:"hashed_password" json:"hashed_password"`
}

func (q *Queries) CredentialsByUsername(ctx context.Context, username interface{}) (CredentialsByUsernameRow, error) {
	row := q.db.QueryRow(ctx, credentialsByUsername, username)
	var i CredentialsByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.HashedPassword,
	)
	return i, err
}

const userActorBase = `-- name: UserActorBase :one
SELECT id, username::text AS username, name, super_admin, all_companies
FROM sys_user
WHERE id = $1
`

type UserActorBaseRow struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Username     string      `db:"username" json:"username"`
	Name         pgtype.Text `db:"name" json:"name"`
	SuperAdmin   bool        `db:"super_admin" json:"super_admin"`
	AllCompanies bool        `db:"all_companies" json:"all_companies"`
}

func (q *Queries) UserActorBase(ctx context.Context, id uuid.UUID) (UserActorBaseRow, error) {
	row := q.db.QueryRow(ctx, userActorBase, id)
	var i UserActorBaseRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.SuperAdmin,
		&i.AllCompanies,
	)
	return i, err
}

const userCompanyIDs = `-- name: UserCompanyIDs :many
SELECT company_id
FROM sys_user_company
WHERE user_id = $1
ORDER BY company_id
`

func (q *Queries) UserCompanyIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, userCompanyIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var company_id uuid.UUID
		if err := rows.Scan(&company_id); err != nil {
			return nil, err
		}
		items = append(items, company_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userPermissions = `-- name: UserPermissions :many
SELECT DISTINCT rp.permission
FROM sys_user_role ur
JOIN sys_role r ON r.id = ur.role_id AND r.enabled = true
JOIN sys_role_permission rp ON rp.role_id = r.id
WHERE ur.user_id = $1
ORDER BY rp.permission
`

func (q *Queries) UserPermissions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, userPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
