// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const companyParentLink = `-- name: CompanyParentLink :one
SELECT parent_id FROM bas_company WHERE id = $1
`

func (q *Queries) CompanyParentLink(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, companyParentLink, id)
	var parent_id *uuid.UUID
	err := row.Scan(&parent_id)
	return parent_id, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO bas_company (code, name, short_name, parent_id, base_currency_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateCompanyParams struct {
	Code           string     `db:"code" json:"code"`
	Name           string     `db:"name" json:"name"`
	ShortName      string     `db:"short_name" json:"short_name"`
	ParentID       *uuid.UUID `db:"parent_id" json:"parent_id"`
	BaseCurrencyID uuid.UUID  `db:"base_currency_id" json:"base_currency_id"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Code,
		arg.Name,
		arg.ShortName,
		arg.ParentID,
		arg.BaseCurrencyID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const currencyIsActive = `-- name: CurrencyIsActive :one
SELECT EXISTS (SELECT 1 FROM bas_currency WHERE id = $1 AND active = true)
`

func (q *Queries) CurrencyIsActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, currencyIsActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteCompany = `-- name: DeleteCompany :execrows
DELETE FROM bas_company WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompany, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompany = `-- name: GetCompany :one
SELECT c.id, c.code, c.name, c.short_name, c.parent_id, c.base_currency_id,
       c.inserted_at, c.updated_at, p.name AS parent_name, currency.name AS base_currency_name
FROM bas_company AS c
LEFT JOIN bas_company AS p ON p.id = c.parent_id
JOIN bas_currency AS currency ON currency.id = c.base_currency_id
WHERE c.id = $1
`

type GetCompanyRow struct {
	ID               uuid.UUID        `db:"id" json:"id"`
	Code             string           `db:"code" json:"code"`
	Name             string           `db:"name" json:"name"`
	ShortName        string           `db:"short_name" json:"short_name"`
	ParentID         *uuid.UUID       `db:"parent_id" json:"parent_id"`
	BaseCurrencyID   uuid.UUID        `db:"base_currency_id" json:"base_currency_id"`
	InsertedAt       pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ParentName       pgtype.Text      `db:"parent_name" json:"parent_name"`
	BaseCurrencyName string           `db:"base_currency_name" json:"base_currency_name"`
}

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (GetCompanyRow, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i GetCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ShortName,
		&i.ParentID,
		&i.BaseCurrencyID,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ParentName,
		&i.BaseCurrencyName,
	)
	return i, err
}

const lockCompany = `-- name: LockCompany :one
SELECT id, code, name, short_name, parent_id, base_currency_id, inserted_at, updated_at
FROM bas_company WHERE id = $1 FOR UPDATE
`

type LockCompanyRow struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	Code           string           `db:"code" json:"code"`
	Name           string           `db:"name" json:"name"`
	ShortName      string           `db:"short_name" json:"short_name"`
	ParentID       *uuid.UUID       `db:"parent_id" json:"parent_id"`
	BaseCurrencyID uuid.UUID        `db:"base_currency_id" json:"base_currency_id"`
	InsertedAt     pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockCompany(ctx context.Context, id uuid.UUID) (LockCompanyRow, error) {
	row := q.db.QueryRow(ctx, lockCompany, id)
	var i LockCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ShortName,
		&i.ParentID,
		&i.BaseCurrencyID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :exec
UPDATE bas_company
SET name = $2, short_name = $3, parent_id = $4, base_currency_id = $5,
    updated_at = timezone('utc', now())
WHERE id = $1
`

type UpdateCompanyParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	Name           string     `db:"name" json:"name"`
	ShortName      string     `db:"short_name" json:"short_name"`
	ParentID       *uuid.UUID `db:"parent_id" json:"parent_id"`
	BaseCurrencyID uuid.UUID  `db:"base_currency_id" json:"base_currency_id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) error {
	_, err := q.db.Exec(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.ShortName,
		arg.ParentID,
		arg.BaseCurrencyID,
	)
	return err
}
