// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: employee.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO hr_employees (
  code, name, attendance_no, id_number, household_registration, phone,
  current_address, daily_wage, monthly_allowance, insurance_types
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, code, name, attendance_no, id_number, household_registration, phone, current_address, daily_wage, monthly_allowance, inserted_at, updated_at, insurance_types
`

type CreateEmployeeParams struct {
	Code                  string         `db:"code" json:"code"`
	Name                  string         `db:"name" json:"name"`
	AttendanceNo          pgtype.Text    `db:"attendance_no" json:"attendance_no"`
	IDNumber              pgtype.Text    `db:"id_number" json:"id_number"`
	HouseholdRegistration pgtype.Text    `db:"household_registration" json:"household_registration"`
	Phone                 pgtype.Text    `db:"phone" json:"phone"`
	CurrentAddress        pgtype.Text    `db:"current_address" json:"current_address"`
	DailyWage             pgtype.Numeric `db:"daily_wage" json:"daily_wage"`
	MonthlyAllowance      pgtype.Numeric `db:"monthly_allowance" json:"monthly_allowance"`
	InsuranceTypes        []string       `db:"insurance_types" json:"insurance_types"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (HrEmployee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.Code,
		arg.Name,
		arg.AttendanceNo,
		arg.IDNumber,
		arg.HouseholdRegistration,
		arg.Phone,
		arg.CurrentAddress,
		arg.DailyWage,
		arg.MonthlyAllowance,
		arg.InsuranceTypes,
	)
	var i HrEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AttendanceNo,
		&i.IDNumber,
		&i.HouseholdRegistration,
		&i.Phone,
		&i.CurrentAddress,
		&i.DailyWage,
		&i.MonthlyAllowance,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.InsuranceTypes,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :execrows
DELETE FROM hr_employees WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmployee, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, code, name, attendance_no, id_number, household_registration, phone, current_address, daily_wage, monthly_allowance, inserted_at, updated_at, insurance_types FROM hr_employees WHERE id = $1
`

func (q *Queries) GetEmployee(ctx context.Context, id uuid.UUID) (HrEmployee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i HrEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AttendanceNo,
		&i.IDNumber,
		&i.HouseholdRegistration,
		&i.Phone,
		&i.CurrentAddress,
		&i.DailyWage,
		&i.MonthlyAllowance,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.InsuranceTypes,
	)
	return i, err
}

const lockEmployee = `-- name: LockEmployee :one
SELECT id, code, name, attendance_no, id_number, household_registration, phone, current_address, daily_wage, monthly_allowance, inserted_at, updated_at, insurance_types FROM hr_employees WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockEmployee(ctx context.Context, id uuid.UUID) (HrEmployee, error) {
	row := q.db.QueryRow(ctx, lockEmployee, id)
	var i HrEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AttendanceNo,
		&i.IDNumber,
		&i.HouseholdRegistration,
		&i.Phone,
		&i.CurrentAddress,
		&i.DailyWage,
		&i.MonthlyAllowance,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.InsuranceTypes,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE hr_employees
SET code = $2,
    name = $3,
    attendance_no = $4,
    id_number = $5,
    household_registration = $6,
    phone = $7,
    current_address = $8,
    daily_wage = $9,
    monthly_allowance = $10,
    insurance_types = $11,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, code, name, attendance_no, id_number, household_registration, phone, current_address, daily_wage, monthly_allowance, inserted_at, updated_at, insurance_types
`

type UpdateEmployeeParams struct {
	ID                    uuid.UUID      `db:"id" json:"id"`
	Code                  string         `db:"code" json:"code"`
	Name                  string         `db:"name" json:"name"`
	AttendanceNo          pgtype.Text    `db:"attendance_no" json:"attendance_no"`
	IDNumber              pgtype.Text    `db:"id_number" json:"id_number"`
	HouseholdRegistration pgtype.Text    `db:"household_registration" json:"household_registration"`
	Phone                 pgtype.Text    `db:"phone" json:"phone"`
	CurrentAddress        pgtype.Text    `db:"current_address" json:"current_address"`
	DailyWage             pgtype.Numeric `db:"daily_wage" json:"daily_wage"`
	MonthlyAllowance      pgtype.Numeric `db:"monthly_allowance" json:"monthly_allowance"`
	InsuranceTypes        []string       `db:"insurance_types" json:"insurance_types"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (HrEmployee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.AttendanceNo,
		arg.IDNumber,
		arg.HouseholdRegistration,
		arg.Phone,
		arg.CurrentAddress,
		arg.DailyWage,
		arg.MonthlyAllowance,
		arg.InsuranceTypes,
	)
	var i HrEmployee
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AttendanceNo,
		&i.IDNumber,
		&i.HouseholdRegistration,
		&i.Phone,
		&i.CurrentAddress,
		&i.DailyWage,
		&i.MonthlyAllowance,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.InsuranceTypes,
	)
	return i, err
}
