// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_documents.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const financeDocumentsBillVisibleToCompanies = `-- name: FinanceDocumentsBillVisibleToCompanies :one
SELECT EXISTS (
  SELECT 1
  FROM acc_bill_transaction
  WHERE bill_id = $1
    AND company_id = ANY($2::uuid[])
)
`

type FinanceDocumentsBillVisibleToCompaniesParams struct {
	BillID  *uuid.UUID  `db:"bill_id" json:"bill_id"`
	Column2 []uuid.UUID `db:"column_2" json:"column_2"`
}

func (q *Queries) FinanceDocumentsBillVisibleToCompanies(ctx context.Context, arg FinanceDocumentsBillVisibleToCompaniesParams) (bool, error) {
	row := q.db.QueryRow(ctx, financeDocumentsBillVisibleToCompanies, arg.BillID, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const financeDocumentsDeleteBillHoldingsForReplay = `-- name: FinanceDocumentsDeleteBillHoldingsForReplay :exec
DELETE FROM acc_bill_holding
WHERE bill_id = $1
`

func (q *Queries) FinanceDocumentsDeleteBillHoldingsForReplay(ctx context.Context, billID uuid.UUID) error {
	_, err := q.db.Exec(ctx, financeDocumentsDeleteBillHoldingsForReplay, billID)
	return err
}

const financeDocumentsFindBillByNumberForRegister = `-- name: FinanceDocumentsFindBillByNumberForRegister :one
SELECT id, bill_no, bill_kind, issue_date, due_date, face_amount, drawer_name, drawer_account, drawer_bank_name, drawer_bank_no, payee_name, payee_account, payee_bank_name, payee_bank_no, acceptor_name, acceptor_account, acceptor_bank_name, acceptor_bank_no, transferable, acceptance_date, remarks, inserted_at, updated_at
FROM acc_bill
WHERE bill_no = $1
FOR UPDATE
`

func (q *Queries) FinanceDocumentsFindBillByNumberForRegister(ctx context.Context, billNo string) (AccBill, error) {
	row := q.db.QueryRow(ctx, financeDocumentsFindBillByNumberForRegister, billNo)
	var i AccBill
	err := row.Scan(
		&i.ID,
		&i.BillNo,
		&i.BillKind,
		&i.IssueDate,
		&i.DueDate,
		&i.FaceAmount,
		&i.DrawerName,
		&i.DrawerAccount,
		&i.DrawerBankName,
		&i.DrawerBankNo,
		&i.PayeeName,
		&i.PayeeAccount,
		&i.PayeeBankName,
		&i.PayeeBankNo,
		&i.AcceptorName,
		&i.AcceptorAccount,
		&i.AcceptorBankName,
		&i.AcceptorBankNo,
		&i.Transferable,
		&i.AcceptanceDate,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const financeDocumentsInsertBillHoldingForReplay = `-- name: FinanceDocumentsInsertBillHoldingForReplay :one
INSERT INTO acc_bill_holding (
  bill_no,
  sub_start,
  sub_end,
  amount,
  due_date,
  acquired_on,
  company_id,
  bank_account_id,
  bill_id,
  source_transaction_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, bill_no, sub_start, sub_end, amount, due_date, acquired_on, inserted_at, company_id, bank_account_id, bill_id, source_transaction_id
`

type FinanceDocumentsInsertBillHoldingForReplayParams struct {
	BillNo              string          `db:"bill_no" json:"bill_no"`
	SubStart            int64           `db:"sub_start" json:"sub_start"`
	SubEnd              int64           `db:"sub_end" json:"sub_end"`
	Amount              decimal.Decimal `db:"amount" json:"amount"`
	DueDate             pgtype.Date     `db:"due_date" json:"due_date"`
	AcquiredOn          pgtype.Date     `db:"acquired_on" json:"acquired_on"`
	CompanyID           uuid.UUID       `db:"company_id" json:"company_id"`
	BankAccountID       uuid.UUID       `db:"bank_account_id" json:"bank_account_id"`
	BillID              uuid.UUID       `db:"bill_id" json:"bill_id"`
	SourceTransactionID uuid.UUID       `db:"source_transaction_id" json:"source_transaction_id"`
}

func (q *Queries) FinanceDocumentsInsertBillHoldingForReplay(ctx context.Context, arg FinanceDocumentsInsertBillHoldingForReplayParams) (AccBillHolding, error) {
	row := q.db.QueryRow(ctx, financeDocumentsInsertBillHoldingForReplay,
		arg.BillNo,
		arg.SubStart,
		arg.SubEnd,
		arg.Amount,
		arg.DueDate,
		arg.AcquiredOn,
		arg.CompanyID,
		arg.BankAccountID,
		arg.BillID,
		arg.SourceTransactionID,
	)
	var i AccBillHolding
	err := row.Scan(
		&i.ID,
		&i.BillNo,
		&i.SubStart,
		&i.SubEnd,
		&i.Amount,
		&i.DueDate,
		&i.AcquiredOn,
		&i.InsertedAt,
		&i.CompanyID,
		&i.BankAccountID,
		&i.BillID,
		&i.SourceTransactionID,
	)
	return i, err
}

const financeDocumentsInvoiceReferencedByLiveExpenseReport = `-- name: FinanceDocumentsInvoiceReferencedByLiveExpenseReport :one
SELECT EXISTS (
  SELECT 1
  FROM acc_expense_report_item item
  JOIN acc_expense_report report ON report.id = item.report_id
  WHERE item.invoice_id = $1
    AND report.status <> 'voided'
)
`

func (q *Queries) FinanceDocumentsInvoiceReferencedByLiveExpenseReport(ctx context.Context, invoiceID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, financeDocumentsInvoiceReferencedByLiveExpenseReport, invoiceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const financeDocumentsListAuditedBillTransactionsForReplay = `-- name: FinanceDocumentsListAuditedBillTransactionsForReplay :many
SELECT id, doc_no, transaction_type, occurred_on, sub_start, sub_end, amount, party_type, party_id, discount_org, discount_rate, interest, net_amount, posting_date, status, audited_at, remarks, inserted_at, updated_at, company_id, bank_account_id, to_bank_account_id, bill_id, bill_account_id, settle_account_id, interest_account_id, created_by_id, audited_by_id
FROM acc_bill_transaction
WHERE bill_id = $1
  AND status = 'audited'
ORDER BY occurred_on, audited_at, id
`

func (q *Queries) FinanceDocumentsListAuditedBillTransactionsForReplay(ctx context.Context, billID *uuid.UUID) ([]AccBillTransaction, error) {
	rows, err := q.db.Query(ctx, financeDocumentsListAuditedBillTransactionsForReplay, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccBillTransaction{}
	for rows.Next() {
		var i AccBillTransaction
		if err := rows.Scan(
			&i.ID,
			&i.DocNo,
			&i.TransactionType,
			&i.OccurredOn,
			&i.SubStart,
			&i.SubEnd,
			&i.Amount,
			&i.PartyType,
			&i.PartyID,
			&i.DiscountOrg,
			&i.DiscountRate,
			&i.Interest,
			&i.NetAmount,
			&i.PostingDate,
			&i.Status,
			&i.AuditedAt,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.CompanyID,
			&i.BankAccountID,
			&i.ToBankAccountID,
			&i.BillID,
			&i.BillAccountID,
			&i.SettleAccountID,
			&i.InterestAccountID,
			&i.CreatedByID,
			&i.AuditedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeDocumentsLockBill = `-- name: FinanceDocumentsLockBill :one
SELECT id, bill_no, bill_kind, issue_date, due_date, face_amount, drawer_name, drawer_account, drawer_bank_name, drawer_bank_no, payee_name, payee_account, payee_bank_name, payee_bank_no, acceptor_name, acceptor_account, acceptor_bank_name, acceptor_bank_no, transferable, acceptance_date, remarks, inserted_at, updated_at
FROM acc_bill
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FinanceDocumentsLockBill(ctx context.Context, id uuid.UUID) (AccBill, error) {
	row := q.db.QueryRow(ctx, financeDocumentsLockBill, id)
	var i AccBill
	err := row.Scan(
		&i.ID,
		&i.BillNo,
		&i.BillKind,
		&i.IssueDate,
		&i.DueDate,
		&i.FaceAmount,
		&i.DrawerName,
		&i.DrawerAccount,
		&i.DrawerBankName,
		&i.DrawerBankNo,
		&i.PayeeName,
		&i.PayeeAccount,
		&i.PayeeBankName,
		&i.PayeeBankNo,
		&i.AcceptorName,
		&i.AcceptorAccount,
		&i.AcceptorBankName,
		&i.AcceptorBankNo,
		&i.Transferable,
		&i.AcceptanceDate,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const financeDocumentsLockBillTransaction = `-- name: FinanceDocumentsLockBillTransaction :one
SELECT id, doc_no, transaction_type, occurred_on, sub_start, sub_end, amount, party_type, party_id, discount_org, discount_rate, interest, net_amount, posting_date, status, audited_at, remarks, inserted_at, updated_at, company_id, bank_account_id, to_bank_account_id, bill_id, bill_account_id, settle_account_id, interest_account_id, created_by_id, audited_by_id
FROM acc_bill_transaction
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FinanceDocumentsLockBillTransaction(ctx context.Context, id uuid.UUID) (AccBillTransaction, error) {
	row := q.db.QueryRow(ctx, financeDocumentsLockBillTransaction, id)
	var i AccBillTransaction
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.TransactionType,
		&i.OccurredOn,
		&i.SubStart,
		&i.SubEnd,
		&i.Amount,
		&i.PartyType,
		&i.PartyID,
		&i.DiscountOrg,
		&i.DiscountRate,
		&i.Interest,
		&i.NetAmount,
		&i.PostingDate,
		&i.Status,
		&i.AuditedAt,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.BankAccountID,
		&i.ToBankAccountID,
		&i.BillID,
		&i.BillAccountID,
		&i.SettleAccountID,
		&i.InterestAccountID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const financeDocumentsLockExpenseReport = `-- name: FinanceDocumentsLockExpenseReport :one
SELECT id, doc_no, expense_date, posting_date, remarks, status, audited_at, inserted_at, updated_at, company_id, employee_id, payment_account_id, created_by_id, audited_by_id
FROM acc_expense_report
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FinanceDocumentsLockExpenseReport(ctx context.Context, id uuid.UUID) (AccExpenseReport, error) {
	row := q.db.QueryRow(ctx, financeDocumentsLockExpenseReport, id)
	var i AccExpenseReport
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.ExpenseDate,
		&i.PostingDate,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.EmployeeID,
		&i.PaymentAccountID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const financeDocumentsLockExpenseReportItems = `-- name: FinanceDocumentsLockExpenseReportItems :many
SELECT id, idx, kind, summary, amount, remarks, inserted_at, updated_at, report_id, company_id, invoice_id, expense_account_id
FROM acc_expense_report_item
WHERE report_id = $1
ORDER BY idx, id
FOR UPDATE
`

func (q *Queries) FinanceDocumentsLockExpenseReportItems(ctx context.Context, reportID uuid.UUID) ([]AccExpenseReportItem, error) {
	rows, err := q.db.Query(ctx, financeDocumentsLockExpenseReportItems, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccExpenseReportItem{}
	for rows.Next() {
		var i AccExpenseReportItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Kind,
			&i.Summary,
			&i.Amount,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ReportID,
			&i.CompanyID,
			&i.InvoiceID,
			&i.ExpenseAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeDocumentsLockInvoiceForExpense = `-- name: FinanceDocumentsLockInvoiceForExpense :one
SELECT id, doc_no, direction, invoice_date, posting_date, party_type, party_id, invoice_kind, invoice_code, invoice_no, seller_name, seller_tax_no, seller_address_phone, seller_bank_account, buyer_name, buyer_tax_no, buyer_address_phone, buyer_bank_account, items, net_total, tax_total, gross_total, issuer, reviewer, payee, remarks, red_invoice_no, status, audited_at, inserted_at, updated_at, company_id, party_account_id, amount_account_id, tax_account_id, mirror_invoice_id, created_by_id, audited_by_id, sal_reconciliation_id, pur_reconciliation_id
FROM acc_vat_invoice
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FinanceDocumentsLockInvoiceForExpense(ctx context.Context, id uuid.UUID) (AccVatInvoice, error) {
	row := q.db.QueryRow(ctx, financeDocumentsLockInvoiceForExpense, id)
	var i AccVatInvoice
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Direction,
		&i.InvoiceDate,
		&i.PostingDate,
		&i.PartyType,
		&i.PartyID,
		&i.InvoiceKind,
		&i.InvoiceCode,
		&i.InvoiceNo,
		&i.SellerName,
		&i.SellerTaxNo,
		&i.SellerAddressPhone,
		&i.SellerBankAccount,
		&i.BuyerName,
		&i.BuyerTaxNo,
		&i.BuyerAddressPhone,
		&i.BuyerBankAccount,
		&i.Items,
		&i.NetTotal,
		&i.TaxTotal,
		&i.GrossTotal,
		&i.Issuer,
		&i.Reviewer,
		&i.Payee,
		&i.Remarks,
		&i.RedInvoiceNo,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.PartyAccountID,
		&i.AmountAccountID,
		&i.TaxAccountID,
		&i.MirrorInvoiceID,
		&i.CreatedByID,
		&i.AuditedByID,
		&i.SalReconciliationID,
		&i.PurReconciliationID,
	)
	return i, err
}

const financeDocumentsLockVatInvoice = `-- name: FinanceDocumentsLockVatInvoice :one

SELECT id, doc_no, direction, invoice_date, posting_date, party_type, party_id, invoice_kind, invoice_code, invoice_no, seller_name, seller_tax_no, seller_address_phone, seller_bank_account, buyer_name, buyer_tax_no, buyer_address_phone, buyer_bank_account, items, net_total, tax_total, gross_total, issuer, reviewer, payee, remarks, red_invoice_no, status, audited_at, inserted_at, updated_at, company_id, party_account_id, amount_account_id, tax_account_id, mirror_invoice_id, created_by_id, audited_by_id, sal_reconciliation_id, pur_reconciliation_id
FROM acc_vat_invoice
WHERE id = $1
FOR UPDATE
`

// Canonical finance-document SQL surface. The documents domain currently uses
// these shapes through caller-owned pgx transactions; keeping the statements
// here lets the root integration generate typed adapters without weakening the
// aggregate transaction boundary.
func (q *Queries) FinanceDocumentsLockVatInvoice(ctx context.Context, id uuid.UUID) (AccVatInvoice, error) {
	row := q.db.QueryRow(ctx, financeDocumentsLockVatInvoice, id)
	var i AccVatInvoice
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Direction,
		&i.InvoiceDate,
		&i.PostingDate,
		&i.PartyType,
		&i.PartyID,
		&i.InvoiceKind,
		&i.InvoiceCode,
		&i.InvoiceNo,
		&i.SellerName,
		&i.SellerTaxNo,
		&i.SellerAddressPhone,
		&i.SellerBankAccount,
		&i.BuyerName,
		&i.BuyerTaxNo,
		&i.BuyerAddressPhone,
		&i.BuyerBankAccount,
		&i.Items,
		&i.NetTotal,
		&i.TaxTotal,
		&i.GrossTotal,
		&i.Issuer,
		&i.Reviewer,
		&i.Payee,
		&i.Remarks,
		&i.RedInvoiceNo,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.PartyAccountID,
		&i.AmountAccountID,
		&i.TaxAccountID,
		&i.MirrorInvoiceID,
		&i.CreatedByID,
		&i.AuditedByID,
		&i.SalReconciliationID,
		&i.PurReconciliationID,
	)
	return i, err
}
