// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: gl_entry.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const gLARAPBalances = `-- name: GLARAPBalances :many
SELECT party_type, party_id, account_id,
       sum(debit)::numeric AS debit,
       sum(credit)::numeric AS credit
FROM acc_gl_entry
WHERE company_id = $1
  AND posting_date <= $2
  AND is_cancelled = false
  AND account_id = ANY($3::uuid[])
GROUP BY party_type, party_id, account_id
`

type GLARAPBalancesParams struct {
	CompanyID   uuid.UUID   `db:"company_id" json:"company_id"`
	PostingDate pgtype.Date `db:"posting_date" json:"posting_date"`
	AccountIds  []uuid.UUID `db:"account_ids" json:"account_ids"`
}

type GLARAPBalancesRow struct {
	PartyType pgtype.Text     `db:"party_type" json:"party_type"`
	PartyID   *uuid.UUID      `db:"party_id" json:"party_id"`
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
	Debit     decimal.Decimal `db:"debit" json:"debit"`
	Credit    decimal.Decimal `db:"credit" json:"credit"`
}

func (q *Queries) GLARAPBalances(ctx context.Context, arg GLARAPBalancesParams) ([]GLARAPBalancesRow, error) {
	rows, err := q.db.Query(ctx, gLARAPBalances, arg.CompanyID, arg.PostingDate, arg.AccountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GLARAPBalancesRow{}
	for rows.Next() {
		var i GLARAPBalancesRow
		if err := rows.Scan(
			&i.PartyType,
			&i.PartyID,
			&i.AccountID,
			&i.Debit,
			&i.Credit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGLEntry = `-- name: GetGLEntry :one
SELECT id, seq, posting_date, debit, credit, party_type, party_id,
       voucher_type, voucher_id, voucher_no, is_cancelled, remarks,
       inserted_at, company_id, account_id, currency_id, is_reversed,
       is_reversal
FROM acc_gl_entry
WHERE id = $1
`

func (q *Queries) GetGLEntry(ctx context.Context, id uuid.UUID) (AccGlEntry, error) {
	row := q.db.QueryRow(ctx, getGLEntry, id)
	var i AccGlEntry
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.PostingDate,
		&i.Debit,
		&i.Credit,
		&i.PartyType,
		&i.PartyID,
		&i.VoucherType,
		&i.VoucherID,
		&i.VoucherNo,
		&i.IsCancelled,
		&i.Remarks,
		&i.InsertedAt,
		&i.CompanyID,
		&i.AccountID,
		&i.CurrencyID,
		&i.IsReversed,
		&i.IsReversal,
	)
	return i, err
}

const listGLPartyLabels = `-- name: ListGLPartyLabels :many
SELECT 'customer'::text AS party_type, id, name
FROM sal_customers
WHERE id = ANY($1::uuid[])
UNION ALL
SELECT 'supplier'::text AS party_type, id, name
FROM pur_supplier
WHERE id = ANY($2::uuid[])
UNION ALL
SELECT 'company'::text AS party_type, id, name
FROM bas_company
WHERE id = ANY($3::uuid[])
UNION ALL
SELECT 'employee'::text AS party_type, id, name
FROM hr_employees
WHERE id = ANY($4::uuid[])
`

type ListGLPartyLabelsParams struct {
	CustomerIds []uuid.UUID `db:"customer_ids" json:"customer_ids"`
	SupplierIds []uuid.UUID `db:"supplier_ids" json:"supplier_ids"`
	CompanyIds  []uuid.UUID `db:"company_ids" json:"company_ids"`
	EmployeeIds []uuid.UUID `db:"employee_ids" json:"employee_ids"`
}

type ListGLPartyLabelsRow struct {
	PartyType string    `db:"party_type" json:"party_type"`
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
}

func (q *Queries) ListGLPartyLabels(ctx context.Context, arg ListGLPartyLabelsParams) ([]ListGLPartyLabelsRow, error) {
	rows, err := q.db.Query(ctx, listGLPartyLabels,
		arg.CustomerIds,
		arg.SupplierIds,
		arg.CompanyIds,
		arg.EmployeeIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGLPartyLabelsRow{}
	for rows.Next() {
		var i ListGLPartyLabelsRow
		if err := rows.Scan(&i.PartyType, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGLPartyRoleAccounts = `-- name: ListGLPartyRoleAccounts :many
SELECT id, code, name, role
FROM bas_account
WHERE company_id = $1
  AND role = ANY($2::text[])
ORDER BY role ASC, code ASC, id ASC
`

type ListGLPartyRoleAccountsParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Roles     []string  `db:"roles" json:"roles"`
}

type ListGLPartyRoleAccountsRow struct {
	ID   uuid.UUID   `db:"id" json:"id"`
	Code string      `db:"code" json:"code"`
	Name string      `db:"name" json:"name"`
	Role pgtype.Text `db:"role" json:"role"`
}

func (q *Queries) ListGLPartyRoleAccounts(ctx context.Context, arg ListGLPartyRoleAccountsParams) ([]ListGLPartyRoleAccountsRow, error) {
	rows, err := q.db.Query(ctx, listGLPartyRoleAccounts, arg.CompanyID, arg.Roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGLPartyRoleAccountsRow{}
	for rows.Next() {
		var i ListGLPartyRoleAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
