// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: iam.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIAMRole = `-- name: CreateIAMRole :one
INSERT INTO sys_role (code, name, enabled)
VALUES ($1, $2, $3)
RETURNING id, code, name, enabled, builtin, inserted_at, updated_at
`

type CreateIAMRoleParams struct {
	Code    string `db:"code" json:"code"`
	Name    string `db:"name" json:"name"`
	Enabled bool   `db:"enabled" json:"enabled"`
}

type CreateIAMRoleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Code       string           `db:"code" json:"code"`
	Name       string           `db:"name" json:"name"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	Builtin    bool             `db:"builtin" json:"builtin"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateIAMRole(ctx context.Context, arg CreateIAMRoleParams) (CreateIAMRoleRow, error) {
	row := q.db.QueryRow(ctx, createIAMRole, arg.Code, arg.Name, arg.Enabled)
	var i CreateIAMRoleRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Enabled,
		&i.Builtin,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIAMUser = `-- name: CreateIAMUser :one
INSERT INTO sys_user (username, name, hashed_password)
VALUES ($1, $2, $3)
RETURNING id, username::text AS username, name, preferred_language, inserted_at, updated_at
`

type CreateIAMUserParams struct {
	Username       interface{} `db:"username" json:"username"`
	Name           pgtype.Text `db:"name" json:"name"`
	HashedPassword string      `db:"hashed_password" json:"hashed_password"`
}

type CreateIAMUserRow struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	Username          string           `db:"username" json:"username"`
	Name              pgtype.Text      `db:"name" json:"name"`
	PreferredLanguage pgtype.Text      `db:"preferred_language" json:"preferred_language"`
	InsertedAt        pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateIAMUser(ctx context.Context, arg CreateIAMUserParams) (CreateIAMUserRow, error) {
	row := q.db.QueryRow(ctx, createIAMUser, arg.Username, arg.Name, arg.HashedPassword)
	var i CreateIAMUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.PreferredLanguage,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIAMRole = `-- name: DeleteIAMRole :execrows
DELETE FROM sys_role WHERE id = $1
`

func (q *Queries) DeleteIAMRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIAMRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIAMUser = `-- name: DeleteIAMUser :execrows
DELETE FROM sys_user WHERE id = $1
`

func (q *Queries) DeleteIAMUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIAMUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM sys_role_permission
WHERE role_id = $1 AND permission = ANY($2::text[])
`

type DeleteRolePermissionsParams struct {
	RoleID      uuid.UUID `db:"role_id" json:"role_id"`
	Permissions []string  `db:"permissions" json:"permissions"`
}

func (q *Queries) DeleteRolePermissions(ctx context.Context, arg DeleteRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, arg.RoleID, arg.Permissions)
	return err
}

const deleteUserCompanies = `-- name: DeleteUserCompanies :exec
DELETE FROM sys_user_company WHERE user_id = $1
`

func (q *Queries) DeleteUserCompanies(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserCompanies, userID)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM sys_user_role WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getIAMRole = `-- name: GetIAMRole :one
SELECT id, code, name, enabled, builtin, inserted_at, updated_at
FROM sys_role WHERE id = $1
`

type GetIAMRoleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Code       string           `db:"code" json:"code"`
	Name       string           `db:"name" json:"name"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	Builtin    bool             `db:"builtin" json:"builtin"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetIAMRole(ctx context.Context, id uuid.UUID) (GetIAMRoleRow, error) {
	row := q.db.QueryRow(ctx, getIAMRole, id)
	var i GetIAMRoleRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Enabled,
		&i.Builtin,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIAMUser = `-- name: GetIAMUser :one
SELECT id, username::text AS username, name, preferred_language, inserted_at, updated_at
FROM sys_user WHERE id = $1
`

type GetIAMUserRow struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	Username          string           `db:"username" json:"username"`
	Name              pgtype.Text      `db:"name" json:"name"`
	PreferredLanguage pgtype.Text      `db:"preferred_language" json:"preferred_language"`
	InsertedAt        pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetIAMUser(ctx context.Context, id uuid.UUID) (GetIAMUserRow, error) {
	row := q.db.QueryRow(ctx, getIAMUser, id)
	var i GetIAMUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.PreferredLanguage,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT id, permission FROM sys_role_permission WHERE role_id = $1 ORDER BY permission, id
`

type GetRolePermissionsRow struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Permission string    `db:"permission" json:"permission"`
}

func (q *Queries) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRolePermissionsRow{}
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(&i.ID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRolePermissions = `-- name: InsertRolePermissions :exec
INSERT INTO sys_role_permission (role_id, permission)
SELECT $1, unnest($2::text[])
ON CONFLICT (role_id, permission) DO NOTHING
`

type InsertRolePermissionsParams struct {
	RoleID      uuid.UUID `db:"role_id" json:"role_id"`
	Permissions []string  `db:"permissions" json:"permissions"`
}

func (q *Queries) InsertRolePermissions(ctx context.Context, arg InsertRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, insertRolePermissions, arg.RoleID, arg.Permissions)
	return err
}

const insertUserCompanies = `-- name: InsertUserCompanies :exec
INSERT INTO sys_user_company (user_id, company_id)
SELECT $1, unnest($2::uuid[])
`

type InsertUserCompaniesParams struct {
	UserID     uuid.UUID   `db:"user_id" json:"user_id"`
	CompanyIds []uuid.UUID `db:"company_ids" json:"company_ids"`
}

func (q *Queries) InsertUserCompanies(ctx context.Context, arg InsertUserCompaniesParams) error {
	_, err := q.db.Exec(ctx, insertUserCompanies, arg.UserID, arg.CompanyIds)
	return err
}

const insertUserRoles = `-- name: InsertUserRoles :exec
INSERT INTO sys_user_role (user_id, role_id)
SELECT $1, unnest($2::uuid[])
`

type InsertUserRolesParams struct {
	UserID  uuid.UUID   `db:"user_id" json:"user_id"`
	RoleIds []uuid.UUID `db:"role_ids" json:"role_ids"`
}

func (q *Queries) InsertUserRoles(ctx context.Context, arg InsertUserRolesParams) error {
	_, err := q.db.Exec(ctx, insertUserRoles, arg.UserID, arg.RoleIds)
	return err
}

const lockIAMRole = `-- name: LockIAMRole :one
SELECT id, code, name, enabled, builtin, inserted_at, updated_at
FROM sys_role WHERE id = $1 FOR UPDATE
`

type LockIAMRoleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Code       string           `db:"code" json:"code"`
	Name       string           `db:"name" json:"name"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	Builtin    bool             `db:"builtin" json:"builtin"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockIAMRole(ctx context.Context, id uuid.UUID) (LockIAMRoleRow, error) {
	row := q.db.QueryRow(ctx, lockIAMRole, id)
	var i LockIAMRoleRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Enabled,
		&i.Builtin,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockIAMUser = `-- name: LockIAMUser :one
SELECT id, username::text AS username, name, preferred_language, inserted_at, updated_at
FROM sys_user WHERE id = $1 FOR UPDATE
`

type LockIAMUserRow struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	Username          string           `db:"username" json:"username"`
	Name              pgtype.Text      `db:"name" json:"name"`
	PreferredLanguage pgtype.Text      `db:"preferred_language" json:"preferred_language"`
	InsertedAt        pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockIAMUser(ctx context.Context, id uuid.UUID) (LockIAMUserRow, error) {
	row := q.db.QueryRow(ctx, lockIAMUser, id)
	var i LockIAMUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.PreferredLanguage,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIAMRole = `-- name: UpdateIAMRole :one
UPDATE sys_role SET name = $2, enabled = $3, updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, code, name, enabled, builtin, inserted_at, updated_at
`

type UpdateIAMRoleParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	Name    string    `db:"name" json:"name"`
	Enabled bool      `db:"enabled" json:"enabled"`
}

type UpdateIAMRoleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Code       string           `db:"code" json:"code"`
	Name       string           `db:"name" json:"name"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	Builtin    bool             `db:"builtin" json:"builtin"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateIAMRole(ctx context.Context, arg UpdateIAMRoleParams) (UpdateIAMRoleRow, error) {
	row := q.db.QueryRow(ctx, updateIAMRole, arg.ID, arg.Name, arg.Enabled)
	var i UpdateIAMRoleRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Enabled,
		&i.Builtin,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIAMUser = `-- name: UpdateIAMUser :one
UPDATE sys_user SET name = $2, updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, username::text AS username, name, preferred_language, inserted_at, updated_at
`

type UpdateIAMUserParams struct {
	ID   uuid.UUID   `db:"id" json:"id"`
	Name pgtype.Text `db:"name" json:"name"`
}

type UpdateIAMUserRow struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	Username          string           `db:"username" json:"username"`
	Name              pgtype.Text      `db:"name" json:"name"`
	PreferredLanguage pgtype.Text      `db:"preferred_language" json:"preferred_language"`
	InsertedAt        pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateIAMUser(ctx context.Context, arg UpdateIAMUserParams) (UpdateIAMUserRow, error) {
	row := q.db.QueryRow(ctx, updateIAMUser, arg.ID, arg.Name)
	var i UpdateIAMUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.PreferredLanguage,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIAMUserPassword = `-- name: UpdateIAMUserPassword :exec
UPDATE sys_user SET hashed_password = $2, updated_at = timezone('utc', now()) WHERE id = $1
`

type UpdateIAMUserPasswordParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	HashedPassword string    `db:"hashed_password" json:"hashed_password"`
}

func (q *Queries) UpdateIAMUserPassword(ctx context.Context, arg UpdateIAMUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateIAMUserPassword, arg.ID, arg.HashedPassword)
	return err
}

const userAccessCompanies = `-- name: UserAccessCompanies :many
SELECT uc.company_id, company.name
FROM sys_user_company AS uc
JOIN bas_company AS company ON company.id = uc.company_id
WHERE uc.user_id = $1
ORDER BY company.name, uc.company_id
`

type UserAccessCompaniesRow struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Name      string    `db:"name" json:"name"`
}

func (q *Queries) UserAccessCompanies(ctx context.Context, userID uuid.UUID) ([]UserAccessCompaniesRow, error) {
	rows, err := q.db.Query(ctx, userAccessCompanies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAccessCompaniesRow{}
	for rows.Next() {
		var i UserAccessCompaniesRow
		if err := rows.Scan(&i.CompanyID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userAccessRoles = `-- name: UserAccessRoles :many
SELECT ur.role_id, role.name
FROM sys_user_role AS ur
JOIN sys_role AS role ON role.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY role.name, ur.role_id
`

type UserAccessRolesRow struct {
	RoleID uuid.UUID `db:"role_id" json:"role_id"`
	Name   string    `db:"name" json:"name"`
}

func (q *Queries) UserAccessRoles(ctx context.Context, userID uuid.UUID) ([]UserAccessRolesRow, error) {
	rows, err := q.db.Query(ctx, userAccessRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAccessRolesRow{}
	for rows.Next() {
		var i UserAccessRolesRow
		if err := rows.Scan(&i.RoleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
