// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manufacturing_execution.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getManufacturingDemand = `-- name: GetManufacturingDemand :one
SELECT id, demand_no, demand_date, remarks, status, inserted_at, updated_at, company_id, created_by_id
FROM mfg_demand
WHERE id = $1
`

func (q *Queries) GetManufacturingDemand(ctx context.Context, id uuid.UUID) (MfgDemand, error) {
	row := q.db.QueryRow(ctx, getManufacturingDemand, id)
	var i MfgDemand
	err := row.Scan(
		&i.ID,
		&i.DemandNo,
		&i.DemandDate,
		&i.Remarks,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.CreatedByID,
	)
	return i, err
}

const getManufacturingWorkOrder = `-- name: GetManufacturingWorkOrder :one
SELECT id, work_order_no, qty, base_qty, received_base_qty, need_date, material_code, material_name, material_spec, unit_name, status, inserted_at, updated_at, company_id, demand_id, demand_item_id, material_id, unit_id, created_by_id
FROM mfg_work_order
WHERE id = $1
`

func (q *Queries) GetManufacturingWorkOrder(ctx context.Context, id uuid.UUID) (MfgWorkOrder, error) {
	row := q.db.QueryRow(ctx, getManufacturingWorkOrder, id)
	var i MfgWorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNo,
		&i.Qty,
		&i.BaseQty,
		&i.ReceivedBaseQty,
		&i.NeedDate,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.DemandID,
		&i.DemandItemID,
		&i.MaterialID,
		&i.UnitID,
		&i.CreatedByID,
	)
	return i, err
}

const listManufacturingDemandItems = `-- name: ListManufacturingDemandItems :many
SELECT id, idx, qty, base_qty, need_date, fulfillment_method, status, material_code, material_name, material_spec, unit_name, remarks, inserted_at, updated_at, demand_id, company_id, material_id, unit_id, sales_order_item_id, ordered_qty, received_qty
FROM mfg_demand_item
WHERE demand_id = $1
ORDER BY idx, id
`

func (q *Queries) ListManufacturingDemandItems(ctx context.Context, demandID uuid.UUID) ([]MfgDemandItem, error) {
	rows, err := q.db.Query(ctx, listManufacturingDemandItems, demandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfgDemandItem{}
	for rows.Next() {
		var i MfgDemandItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.NeedDate,
			&i.FulfillmentMethod,
			&i.Status,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.DemandID,
			&i.CompanyID,
			&i.MaterialID,
			&i.UnitID,
			&i.SalesOrderItemID,
			&i.OrderedQty,
			&i.ReceivedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManufacturingOutputItemsForUpdate = `-- name: ListManufacturingOutputItemsForUpdate :many
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name, remarks, inserted_at, updated_at, output_id, company_id, work_order_id, material_id, unit_id, warehouse_id
FROM mfg_output_item
WHERE output_id = $1
ORDER BY idx, id
FOR UPDATE
`

func (q *Queries) ListManufacturingOutputItemsForUpdate(ctx context.Context, outputID uuid.UUID) ([]MfgOutputItem, error) {
	rows, err := q.db.Query(ctx, listManufacturingOutputItemsForUpdate, outputID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfgOutputItem{}
	for rows.Next() {
		var i MfgOutputItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.Remarks,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.OutputID,
			&i.CompanyID,
			&i.WorkOrderID,
			&i.MaterialID,
			&i.UnitID,
			&i.WarehouseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockManufacturingDemand = `-- name: LockManufacturingDemand :one
SELECT id, demand_no, demand_date, remarks, status, inserted_at, updated_at, company_id, created_by_id
FROM mfg_demand
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockManufacturingDemand(ctx context.Context, id uuid.UUID) (MfgDemand, error) {
	row := q.db.QueryRow(ctx, lockManufacturingDemand, id)
	var i MfgDemand
	err := row.Scan(
		&i.ID,
		&i.DemandNo,
		&i.DemandDate,
		&i.Remarks,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.CreatedByID,
	)
	return i, err
}

const lockManufacturingDemandItem = `-- name: LockManufacturingDemandItem :one
SELECT id, idx, qty, base_qty, need_date, fulfillment_method, status, material_code, material_name, material_spec, unit_name, remarks, inserted_at, updated_at, demand_id, company_id, material_id, unit_id, sales_order_item_id, ordered_qty, received_qty
FROM mfg_demand_item
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockManufacturingDemandItem(ctx context.Context, id uuid.UUID) (MfgDemandItem, error) {
	row := q.db.QueryRow(ctx, lockManufacturingDemandItem, id)
	var i MfgDemandItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.NeedDate,
		&i.FulfillmentMethod,
		&i.Status,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.DemandID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
		&i.SalesOrderItemID,
		&i.OrderedQty,
		&i.ReceivedQty,
	)
	return i, err
}

const lockManufacturingOutput = `-- name: LockManufacturingOutput :one
SELECT id, output_no, output_date, remarks, status, audited_at, inserted_at, updated_at, company_id, warehouse_id, created_by_id, audited_by_id
FROM mfg_output
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockManufacturingOutput(ctx context.Context, id uuid.UUID) (MfgOutput, error) {
	row := q.db.QueryRow(ctx, lockManufacturingOutput, id)
	var i MfgOutput
	err := row.Scan(
		&i.ID,
		&i.OutputNo,
		&i.OutputDate,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const lockManufacturingWorkOrder = `-- name: LockManufacturingWorkOrder :one
SELECT id, work_order_no, qty, base_qty, received_base_qty, need_date, material_code, material_name, material_spec, unit_name, status, inserted_at, updated_at, company_id, demand_id, demand_item_id, material_id, unit_id, created_by_id
FROM mfg_work_order
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockManufacturingWorkOrder(ctx context.Context, id uuid.UUID) (MfgWorkOrder, error) {
	row := q.db.QueryRow(ctx, lockManufacturingWorkOrder, id)
	var i MfgWorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNo,
		&i.Qty,
		&i.BaseQty,
		&i.ReceivedBaseQty,
		&i.NeedDate,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.DemandID,
		&i.DemandItemID,
		&i.MaterialID,
		&i.UnitID,
		&i.CreatedByID,
	)
	return i, err
}

const manufacturingHasActivePurchaseOrder = `-- name: ManufacturingHasActivePurchaseOrder :one
SELECT EXISTS (
  SELECT 1
  FROM pur_order_item AS oi
  JOIN pur_order AS o ON o.id = oi.order_id
  JOIN mfg_demand_item AS i ON i.id = oi.demand_line_id
  WHERE i.demand_id = $1
    AND o.status IN ('audited', 'closed')
)
`

func (q *Queries) ManufacturingHasActivePurchaseOrder(ctx context.Context, demandID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, manufacturingHasActivePurchaseOrder, demandID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const manufacturingOutputOverreceiveRatio = `-- name: ManufacturingOutputOverreceiveRatio :one
SELECT COALESCE(
  (
    SELECT output_overreceive_ratio
    FROM mfg_setting
    ORDER BY inserted_at, id
    LIMIT 1
  ),
  0
)::numeric AS output_overreceive_ratio
`

func (q *Queries) ManufacturingOutputOverreceiveRatio(ctx context.Context) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, manufacturingOutputOverreceiveRatio)
	var output_overreceive_ratio decimal.Decimal
	err := row.Scan(&output_overreceive_ratio)
	return output_overreceive_ratio, err
}

const manufacturingSalesOccupancy = `-- name: ManufacturingSalesOccupancy :one
SELECT
  i.id AS sales_order_item_id,
  i.base_qty AS ordered_base_qty,
  COALESCE(SUM(di.base_qty) FILTER (WHERE d.status = 'confirmed'), 0)::numeric
    AS occupied_base_qty
FROM sal_order_item AS i
LEFT JOIN mfg_demand_item AS di ON di.sales_order_item_id = i.id
LEFT JOIN mfg_demand AS d ON d.id = di.demand_id
WHERE i.id = $1
GROUP BY i.id, i.base_qty
`

type ManufacturingSalesOccupancyRow struct {
	SalesOrderItemID uuid.UUID       `db:"sales_order_item_id" json:"sales_order_item_id"`
	OrderedBaseQty   decimal.Decimal `db:"ordered_base_qty" json:"ordered_base_qty"`
	OccupiedBaseQty  decimal.Decimal `db:"occupied_base_qty" json:"occupied_base_qty"`
}

func (q *Queries) ManufacturingSalesOccupancy(ctx context.Context, id uuid.UUID) (ManufacturingSalesOccupancyRow, error) {
	row := q.db.QueryRow(ctx, manufacturingSalesOccupancy, id)
	var i ManufacturingSalesOccupancyRow
	err := row.Scan(&i.SalesOrderItemID, &i.OrderedBaseQty, &i.OccupiedBaseQty)
	return i, err
}
