// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: market.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createMarketInstrument = `-- name: CreateMarketInstrument :one
INSERT INTO bas_market_instrument (
  code, name, source_type, default_price_kind, active, fetch_enabled,
  external_last_code, external_product_group, note, currency_id, unit_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, code, name, source_type, default_price_kind, active, fetch_enabled,
          external_last_code, external_product_group, note, currency_id, unit_id,
          inserted_at, updated_at
`

type CreateMarketInstrumentParams struct {
	Code                 string      `db:"code" json:"code"`
	Name                 string      `db:"name" json:"name"`
	SourceType           string      `db:"source_type" json:"source_type"`
	DefaultPriceKind     string      `db:"default_price_kind" json:"default_price_kind"`
	Active               bool        `db:"active" json:"active"`
	FetchEnabled         bool        `db:"fetch_enabled" json:"fetch_enabled"`
	ExternalLastCode     pgtype.Text `db:"external_last_code" json:"external_last_code"`
	ExternalProductGroup pgtype.Text `db:"external_product_group" json:"external_product_group"`
	Note                 pgtype.Text `db:"note" json:"note"`
	CurrencyID           uuid.UUID   `db:"currency_id" json:"currency_id"`
	UnitID               uuid.UUID   `db:"unit_id" json:"unit_id"`
}

type CreateMarketInstrumentRow struct {
	ID                   uuid.UUID        `db:"id" json:"id"`
	Code                 string           `db:"code" json:"code"`
	Name                 string           `db:"name" json:"name"`
	SourceType           string           `db:"source_type" json:"source_type"`
	DefaultPriceKind     string           `db:"default_price_kind" json:"default_price_kind"`
	Active               bool             `db:"active" json:"active"`
	FetchEnabled         bool             `db:"fetch_enabled" json:"fetch_enabled"`
	ExternalLastCode     pgtype.Text      `db:"external_last_code" json:"external_last_code"`
	ExternalProductGroup pgtype.Text      `db:"external_product_group" json:"external_product_group"`
	Note                 pgtype.Text      `db:"note" json:"note"`
	CurrencyID           uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID               uuid.UUID        `db:"unit_id" json:"unit_id"`
	InsertedAt           pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateMarketInstrument(ctx context.Context, arg CreateMarketInstrumentParams) (CreateMarketInstrumentRow, error) {
	row := q.db.QueryRow(ctx, createMarketInstrument,
		arg.Code,
		arg.Name,
		arg.SourceType,
		arg.DefaultPriceKind,
		arg.Active,
		arg.FetchEnabled,
		arg.ExternalLastCode,
		arg.ExternalProductGroup,
		arg.Note,
		arg.CurrencyID,
		arg.UnitID,
	)
	var i CreateMarketInstrumentRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SourceType,
		&i.DefaultPriceKind,
		&i.Active,
		&i.FetchEnabled,
		&i.ExternalLastCode,
		&i.ExternalProductGroup,
		&i.Note,
		&i.CurrencyID,
		&i.UnitID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMarketPricePoint = `-- name: CreateMarketPricePoint :one
INSERT INTO bas_market_price_point (
  observed_at, price, price_kind, source, note, instrument_id, currency_id, unit_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, observed_at, price, price_kind, source, is_voided, note,
          instrument_id, currency_id, unit_id, inserted_at, updated_at
`

type CreateMarketPricePointParams struct {
	ObservedAt   pgtype.Timestamp `db:"observed_at" json:"observed_at"`
	Price        decimal.Decimal  `db:"price" json:"price"`
	PriceKind    string           `db:"price_kind" json:"price_kind"`
	Source       string           `db:"source" json:"source"`
	Note         pgtype.Text      `db:"note" json:"note"`
	InstrumentID uuid.UUID        `db:"instrument_id" json:"instrument_id"`
	CurrencyID   uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID       uuid.UUID        `db:"unit_id" json:"unit_id"`
}

type CreateMarketPricePointRow struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	ObservedAt   pgtype.Timestamp `db:"observed_at" json:"observed_at"`
	Price        decimal.Decimal  `db:"price" json:"price"`
	PriceKind    string           `db:"price_kind" json:"price_kind"`
	Source       string           `db:"source" json:"source"`
	IsVoided     bool             `db:"is_voided" json:"is_voided"`
	Note         pgtype.Text      `db:"note" json:"note"`
	InstrumentID uuid.UUID        `db:"instrument_id" json:"instrument_id"`
	CurrencyID   uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID       uuid.UUID        `db:"unit_id" json:"unit_id"`
	InsertedAt   pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateMarketPricePoint(ctx context.Context, arg CreateMarketPricePointParams) (CreateMarketPricePointRow, error) {
	row := q.db.QueryRow(ctx, createMarketPricePoint,
		arg.ObservedAt,
		arg.Price,
		arg.PriceKind,
		arg.Source,
		arg.Note,
		arg.InstrumentID,
		arg.CurrencyID,
		arg.UnitID,
	)
	var i CreateMarketPricePointRow
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.Price,
		&i.PriceKind,
		&i.Source,
		&i.IsVoided,
		&i.Note,
		&i.InstrumentID,
		&i.CurrencyID,
		&i.UnitID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMarketInstrument = `-- name: DeleteMarketInstrument :execrows
DELETE FROM bas_market_instrument WHERE id=$1
`

func (q *Queries) DeleteMarketInstrument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMarketInstrument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMarketInstrument = `-- name: GetMarketInstrument :one
SELECT id, code, name, source_type, default_price_kind, active, fetch_enabled,
       external_last_code, external_product_group, note, currency_id, unit_id,
       inserted_at, updated_at
FROM bas_market_instrument WHERE id = $1
`

type GetMarketInstrumentRow struct {
	ID                   uuid.UUID        `db:"id" json:"id"`
	Code                 string           `db:"code" json:"code"`
	Name                 string           `db:"name" json:"name"`
	SourceType           string           `db:"source_type" json:"source_type"`
	DefaultPriceKind     string           `db:"default_price_kind" json:"default_price_kind"`
	Active               bool             `db:"active" json:"active"`
	FetchEnabled         bool             `db:"fetch_enabled" json:"fetch_enabled"`
	ExternalLastCode     pgtype.Text      `db:"external_last_code" json:"external_last_code"`
	ExternalProductGroup pgtype.Text      `db:"external_product_group" json:"external_product_group"`
	Note                 pgtype.Text      `db:"note" json:"note"`
	CurrencyID           uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID               uuid.UUID        `db:"unit_id" json:"unit_id"`
	InsertedAt           pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMarketInstrument(ctx context.Context, id uuid.UUID) (GetMarketInstrumentRow, error) {
	row := q.db.QueryRow(ctx, getMarketInstrument, id)
	var i GetMarketInstrumentRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SourceType,
		&i.DefaultPriceKind,
		&i.Active,
		&i.FetchEnabled,
		&i.ExternalLastCode,
		&i.ExternalProductGroup,
		&i.Note,
		&i.CurrencyID,
		&i.UnitID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketPricePoint = `-- name: GetMarketPricePoint :one
SELECT id, observed_at, price, price_kind, source, is_voided, note,
       instrument_id, currency_id, unit_id, inserted_at, updated_at
FROM bas_market_price_point WHERE id=$1
`

type GetMarketPricePointRow struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	ObservedAt   pgtype.Timestamp `db:"observed_at" json:"observed_at"`
	Price        decimal.Decimal  `db:"price" json:"price"`
	PriceKind    string           `db:"price_kind" json:"price_kind"`
	Source       string           `db:"source" json:"source"`
	IsVoided     bool             `db:"is_voided" json:"is_voided"`
	Note         pgtype.Text      `db:"note" json:"note"`
	InstrumentID uuid.UUID        `db:"instrument_id" json:"instrument_id"`
	CurrencyID   uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID       uuid.UUID        `db:"unit_id" json:"unit_id"`
	InsertedAt   pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMarketPricePoint(ctx context.Context, id uuid.UUID) (GetMarketPricePointRow, error) {
	row := q.db.QueryRow(ctx, getMarketPricePoint, id)
	var i GetMarketPricePointRow
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.Price,
		&i.PriceKind,
		&i.Source,
		&i.IsVoided,
		&i.Note,
		&i.InstrumentID,
		&i.CurrencyID,
		&i.UnitID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockMarketInstrument = `-- name: LockMarketInstrument :one
SELECT id, code, name, source_type, default_price_kind, active, fetch_enabled,
       external_last_code, external_product_group, note, currency_id, unit_id,
       inserted_at, updated_at
FROM bas_market_instrument WHERE id = $1 FOR UPDATE
`

type LockMarketInstrumentRow struct {
	ID                   uuid.UUID        `db:"id" json:"id"`
	Code                 string           `db:"code" json:"code"`
	Name                 string           `db:"name" json:"name"`
	SourceType           string           `db:"source_type" json:"source_type"`
	DefaultPriceKind     string           `db:"default_price_kind" json:"default_price_kind"`
	Active               bool             `db:"active" json:"active"`
	FetchEnabled         bool             `db:"fetch_enabled" json:"fetch_enabled"`
	ExternalLastCode     pgtype.Text      `db:"external_last_code" json:"external_last_code"`
	ExternalProductGroup pgtype.Text      `db:"external_product_group" json:"external_product_group"`
	Note                 pgtype.Text      `db:"note" json:"note"`
	CurrencyID           uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID               uuid.UUID        `db:"unit_id" json:"unit_id"`
	InsertedAt           pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockMarketInstrument(ctx context.Context, id uuid.UUID) (LockMarketInstrumentRow, error) {
	row := q.db.QueryRow(ctx, lockMarketInstrument, id)
	var i LockMarketInstrumentRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SourceType,
		&i.DefaultPriceKind,
		&i.Active,
		&i.FetchEnabled,
		&i.ExternalLastCode,
		&i.ExternalProductGroup,
		&i.Note,
		&i.CurrencyID,
		&i.UnitID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockMarketPricePoint = `-- name: LockMarketPricePoint :one
SELECT id, observed_at, price, price_kind, source, is_voided, note,
       instrument_id, currency_id, unit_id, inserted_at, updated_at
FROM bas_market_price_point WHERE id=$1 FOR UPDATE
`

type LockMarketPricePointRow struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	ObservedAt   pgtype.Timestamp `db:"observed_at" json:"observed_at"`
	Price        decimal.Decimal  `db:"price" json:"price"`
	PriceKind    string           `db:"price_kind" json:"price_kind"`
	Source       string           `db:"source" json:"source"`
	IsVoided     bool             `db:"is_voided" json:"is_voided"`
	Note         pgtype.Text      `db:"note" json:"note"`
	InstrumentID uuid.UUID        `db:"instrument_id" json:"instrument_id"`
	CurrencyID   uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID       uuid.UUID        `db:"unit_id" json:"unit_id"`
	InsertedAt   pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockMarketPricePoint(ctx context.Context, id uuid.UUID) (LockMarketPricePointRow, error) {
	row := q.db.QueryRow(ctx, lockMarketPricePoint, id)
	var i LockMarketPricePointRow
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.Price,
		&i.PriceKind,
		&i.Source,
		&i.IsVoided,
		&i.Note,
		&i.InstrumentID,
		&i.CurrencyID,
		&i.UnitID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMarketInstrument = `-- name: UpdateMarketInstrument :one
UPDATE bas_market_instrument
SET name=$2, default_price_kind=$3, active=$4, fetch_enabled=$5,
    external_last_code=$6, external_product_group=$7, note=$8,
    updated_at=timezone('utc',now())
WHERE id=$1
RETURNING id, code, name, source_type, default_price_kind, active, fetch_enabled,
          external_last_code, external_product_group, note, currency_id, unit_id,
          inserted_at, updated_at
`

type UpdateMarketInstrumentParams struct {
	ID                   uuid.UUID   `db:"id" json:"id"`
	Name                 string      `db:"name" json:"name"`
	DefaultPriceKind     string      `db:"default_price_kind" json:"default_price_kind"`
	Active               bool        `db:"active" json:"active"`
	FetchEnabled         bool        `db:"fetch_enabled" json:"fetch_enabled"`
	ExternalLastCode     pgtype.Text `db:"external_last_code" json:"external_last_code"`
	ExternalProductGroup pgtype.Text `db:"external_product_group" json:"external_product_group"`
	Note                 pgtype.Text `db:"note" json:"note"`
}

type UpdateMarketInstrumentRow struct {
	ID                   uuid.UUID        `db:"id" json:"id"`
	Code                 string           `db:"code" json:"code"`
	Name                 string           `db:"name" json:"name"`
	SourceType           string           `db:"source_type" json:"source_type"`
	DefaultPriceKind     string           `db:"default_price_kind" json:"default_price_kind"`
	Active               bool             `db:"active" json:"active"`
	FetchEnabled         bool             `db:"fetch_enabled" json:"fetch_enabled"`
	ExternalLastCode     pgtype.Text      `db:"external_last_code" json:"external_last_code"`
	ExternalProductGroup pgtype.Text      `db:"external_product_group" json:"external_product_group"`
	Note                 pgtype.Text      `db:"note" json:"note"`
	CurrencyID           uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID               uuid.UUID        `db:"unit_id" json:"unit_id"`
	InsertedAt           pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateMarketInstrument(ctx context.Context, arg UpdateMarketInstrumentParams) (UpdateMarketInstrumentRow, error) {
	row := q.db.QueryRow(ctx, updateMarketInstrument,
		arg.ID,
		arg.Name,
		arg.DefaultPriceKind,
		arg.Active,
		arg.FetchEnabled,
		arg.ExternalLastCode,
		arg.ExternalProductGroup,
		arg.Note,
	)
	var i UpdateMarketInstrumentRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SourceType,
		&i.DefaultPriceKind,
		&i.Active,
		&i.FetchEnabled,
		&i.ExternalLastCode,
		&i.ExternalProductGroup,
		&i.Note,
		&i.CurrencyID,
		&i.UnitID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidMarketPricePoint = `-- name: VoidMarketPricePoint :one
UPDATE bas_market_price_point
SET is_voided=true, updated_at=timezone('utc',now())
WHERE id=$1 AND is_voided=false
RETURNING id, observed_at, price, price_kind, source, is_voided, note,
          instrument_id, currency_id, unit_id, inserted_at, updated_at
`

type VoidMarketPricePointRow struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	ObservedAt   pgtype.Timestamp `db:"observed_at" json:"observed_at"`
	Price        decimal.Decimal  `db:"price" json:"price"`
	PriceKind    string           `db:"price_kind" json:"price_kind"`
	Source       string           `db:"source" json:"source"`
	IsVoided     bool             `db:"is_voided" json:"is_voided"`
	Note         pgtype.Text      `db:"note" json:"note"`
	InstrumentID uuid.UUID        `db:"instrument_id" json:"instrument_id"`
	CurrencyID   uuid.UUID        `db:"currency_id" json:"currency_id"`
	UnitID       uuid.UUID        `db:"unit_id" json:"unit_id"`
	InsertedAt   pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) VoidMarketPricePoint(ctx context.Context, id uuid.UUID) (VoidMarketPricePointRow, error) {
	row := q.db.QueryRow(ctx, voidMarketPricePoint, id)
	var i VoidMarketPricePointRow
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.Price,
		&i.PriceKind,
		&i.Source,
		&i.IsVoided,
		&i.Note,
		&i.InstrumentID,
		&i.CurrencyID,
		&i.UnitID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
