// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material_category.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createMaterialCategory = `-- name: CreateMaterialCategory :one
INSERT INTO inv_material_category (code, name, is_leaf, active, parent_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, is_leaf, active, inserted_at, updated_at, parent_id
`

type CreateMaterialCategoryParams struct {
	Code     string     `db:"code" json:"code"`
	Name     string     `db:"name" json:"name"`
	IsLeaf   bool       `db:"is_leaf" json:"is_leaf"`
	Active   bool       `db:"active" json:"active"`
	ParentID *uuid.UUID `db:"parent_id" json:"parent_id"`
}

func (q *Queries) CreateMaterialCategory(ctx context.Context, arg CreateMaterialCategoryParams) (InvMaterialCategory, error) {
	row := q.db.QueryRow(ctx, createMaterialCategory,
		arg.Code,
		arg.Name,
		arg.IsLeaf,
		arg.Active,
		arg.ParentID,
	)
	var i InvMaterialCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsLeaf,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const deleteMaterialCategory = `-- name: DeleteMaterialCategory :exec
DELETE FROM inv_material_category WHERE id = $1
`

func (q *Queries) DeleteMaterialCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaterialCategory, id)
	return err
}

const getMaterialCategory = `-- name: GetMaterialCategory :one
SELECT id, code, name, is_leaf, active, inserted_at, updated_at, parent_id
FROM inv_material_category
WHERE id = $1
`

func (q *Queries) GetMaterialCategory(ctx context.Context, id uuid.UUID) (InvMaterialCategory, error) {
	row := q.db.QueryRow(ctx, getMaterialCategory, id)
	var i InvMaterialCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsLeaf,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const lockMaterialCategory = `-- name: LockMaterialCategory :one
SELECT id, code, name, is_leaf, active, inserted_at, updated_at, parent_id
FROM inv_material_category
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockMaterialCategory(ctx context.Context, id uuid.UUID) (InvMaterialCategory, error) {
	row := q.db.QueryRow(ctx, lockMaterialCategory, id)
	var i InvMaterialCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsLeaf,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const materialCategoryHasChildren = `-- name: MaterialCategoryHasChildren :one
SELECT EXISTS(SELECT 1 FROM inv_material_category WHERE parent_id = $1)
`

func (q *Queries) MaterialCategoryHasChildren(ctx context.Context, parentID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, materialCategoryHasChildren, parentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const materialCategoryHasMaterials = `-- name: MaterialCategoryHasMaterials :one
SELECT EXISTS(SELECT 1 FROM inv_material WHERE category_id = $1)
`

func (q *Queries) MaterialCategoryHasMaterials(ctx context.Context, categoryID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, materialCategoryHasMaterials, categoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMaterialCategory = `-- name: UpdateMaterialCategory :one
UPDATE inv_material_category
SET code = $2,
    name = $3,
    is_leaf = $4,
    active = $5,
    parent_id = $6,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, code, name, is_leaf, active, inserted_at, updated_at, parent_id
`

type UpdateMaterialCategoryParams struct {
	ID       uuid.UUID  `db:"id" json:"id"`
	Code     string     `db:"code" json:"code"`
	Name     string     `db:"name" json:"name"`
	IsLeaf   bool       `db:"is_leaf" json:"is_leaf"`
	Active   bool       `db:"active" json:"active"`
	ParentID *uuid.UUID `db:"parent_id" json:"parent_id"`
}

func (q *Queries) UpdateMaterialCategory(ctx context.Context, arg UpdateMaterialCategoryParams) (InvMaterialCategory, error) {
	row := q.db.QueryRow(ctx, updateMaterialCategory,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.IsLeaf,
		arg.Active,
		arg.ParentID,
	)
	var i InvMaterialCategory
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsLeaf,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}
