// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: material.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO inv_material (
  code, name, spec, customer_part_no, active,
  category_id, default_unit_id, is_customer_material, customer_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, name, spec, customer_part_no, active, inserted_at, updated_at,
          category_id, default_unit_id, is_customer_material, customer_id
`

type CreateMaterialParams struct {
	Code               string      `db:"code" json:"code"`
	Name               string      `db:"name" json:"name"`
	Spec               pgtype.Text `db:"spec" json:"spec"`
	CustomerPartNo     pgtype.Text `db:"customer_part_no" json:"customer_part_no"`
	Active             bool        `db:"active" json:"active"`
	CategoryID         uuid.UUID   `db:"category_id" json:"category_id"`
	DefaultUnitID      uuid.UUID   `db:"default_unit_id" json:"default_unit_id"`
	IsCustomerMaterial bool        `db:"is_customer_material" json:"is_customer_material"`
	CustomerID         *uuid.UUID  `db:"customer_id" json:"customer_id"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (InvMaterial, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.Code,
		arg.Name,
		arg.Spec,
		arg.CustomerPartNo,
		arg.Active,
		arg.CategoryID,
		arg.DefaultUnitID,
		arg.IsCustomerMaterial,
		arg.CustomerID,
	)
	var i InvMaterial
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CustomerPartNo,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.DefaultUnitID,
		&i.IsCustomerMaterial,
		&i.CustomerID,
	)
	return i, err
}

const deleteMaterial = `-- name: DeleteMaterial :exec
DELETE FROM inv_material WHERE id = $1
`

func (q *Queries) DeleteMaterial(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaterial, id)
	return err
}

const getMaterial = `-- name: GetMaterial :one
SELECT id, code, name, spec, customer_part_no, active, inserted_at, updated_at,
       category_id, default_unit_id, is_customer_material, customer_id
FROM inv_material
WHERE id = $1
`

func (q *Queries) GetMaterial(ctx context.Context, id uuid.UUID) (InvMaterial, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i InvMaterial
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CustomerPartNo,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.DefaultUnitID,
		&i.IsCustomerMaterial,
		&i.CustomerID,
	)
	return i, err
}

const lockMaterial = `-- name: LockMaterial :one
SELECT id, code, name, spec, customer_part_no, active, inserted_at, updated_at,
       category_id, default_unit_id, is_customer_material, customer_id
FROM inv_material
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockMaterial(ctx context.Context, id uuid.UUID) (InvMaterial, error) {
	row := q.db.QueryRow(ctx, lockMaterial, id)
	var i InvMaterial
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CustomerPartNo,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.DefaultUnitID,
		&i.IsCustomerMaterial,
		&i.CustomerID,
	)
	return i, err
}

const materialHasSalesReferences = `-- name: MaterialHasSalesReferences :one
SELECT EXISTS(
  SELECT 1 FROM sal_order_item soi
  WHERE soi.material_id = $1::uuid
  UNION ALL
  SELECT 1 FROM sal_quotation_item sqi
  WHERE sqi.material_id = $1::uuid
)
`

func (q *Queries) MaterialHasSalesReferences(ctx context.Context, materialID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, materialHasSalesReferences, materialID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const materialHasStockEntries = `-- name: MaterialHasStockEntries :one
SELECT EXISTS(SELECT 1 FROM inv_stock_entry WHERE material_id = $1)
`

func (q *Queries) MaterialHasStockEntries(ctx context.Context, materialID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, materialHasStockEntries, materialID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const materialHasUnits = `-- name: MaterialHasUnits :one
SELECT EXISTS(SELECT 1 FROM inv_material_unit WHERE material_id = $1)
`

func (q *Queries) MaterialHasUnits(ctx context.Context, materialID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, materialHasUnits, materialID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE inv_material
SET name = $2,
    spec = $3,
    customer_part_no = $4,
    active = $5,
    category_id = $6,
    default_unit_id = $7,
    is_customer_material = $8,
    customer_id = $9,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, code, name, spec, customer_part_no, active, inserted_at, updated_at,
          category_id, default_unit_id, is_customer_material, customer_id
`

type UpdateMaterialParams struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	Name               string      `db:"name" json:"name"`
	Spec               pgtype.Text `db:"spec" json:"spec"`
	CustomerPartNo     pgtype.Text `db:"customer_part_no" json:"customer_part_no"`
	Active             bool        `db:"active" json:"active"`
	CategoryID         uuid.UUID   `db:"category_id" json:"category_id"`
	DefaultUnitID      uuid.UUID   `db:"default_unit_id" json:"default_unit_id"`
	IsCustomerMaterial bool        `db:"is_customer_material" json:"is_customer_material"`
	CustomerID         *uuid.UUID  `db:"customer_id" json:"customer_id"`
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (InvMaterial, error) {
	row := q.db.QueryRow(ctx, updateMaterial,
		arg.ID,
		arg.Name,
		arg.Spec,
		arg.CustomerPartNo,
		arg.Active,
		arg.CategoryID,
		arg.DefaultUnitID,
		arg.IsCustomerMaterial,
		arg.CustomerID,
	)
	var i InvMaterial
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CustomerPartNo,
		&i.Active,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.DefaultUnitID,
		&i.IsCustomerMaterial,
		&i.CustomerID,
	)
	return i, err
}
