// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material_unit.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createMaterialUnit = `-- name: CreateMaterialUnit :one
INSERT INTO inv_material_unit (material_id, unit_id, factor)
VALUES ($1, $2, $3)
RETURNING id, factor, inserted_at, updated_at, material_id, unit_id
`

type CreateMaterialUnitParams struct {
	MaterialID uuid.UUID       `db:"material_id" json:"material_id"`
	UnitID     uuid.UUID       `db:"unit_id" json:"unit_id"`
	Factor     decimal.Decimal `db:"factor" json:"factor"`
}

func (q *Queries) CreateMaterialUnit(ctx context.Context, arg CreateMaterialUnitParams) (InvMaterialUnit, error) {
	row := q.db.QueryRow(ctx, createMaterialUnit, arg.MaterialID, arg.UnitID, arg.Factor)
	var i InvMaterialUnit
	err := row.Scan(
		&i.ID,
		&i.Factor,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const deleteMaterialUnit = `-- name: DeleteMaterialUnit :exec
DELETE FROM inv_material_unit WHERE id = $1
`

func (q *Queries) DeleteMaterialUnit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaterialUnit, id)
	return err
}

const getMaterialUnit = `-- name: GetMaterialUnit :one
SELECT id, factor, inserted_at, updated_at, material_id, unit_id
FROM inv_material_unit
WHERE id = $1
`

func (q *Queries) GetMaterialUnit(ctx context.Context, id uuid.UUID) (InvMaterialUnit, error) {
	row := q.db.QueryRow(ctx, getMaterialUnit, id)
	var i InvMaterialUnit
	err := row.Scan(
		&i.ID,
		&i.Factor,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const lockMaterialUnit = `-- name: LockMaterialUnit :one
SELECT id, factor, inserted_at, updated_at, material_id, unit_id
FROM inv_material_unit
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockMaterialUnit(ctx context.Context, id uuid.UUID) (InvMaterialUnit, error) {
	row := q.db.QueryRow(ctx, lockMaterialUnit, id)
	var i InvMaterialUnit
	err := row.Scan(
		&i.ID,
		&i.Factor,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const materialDefaultUnitID = `-- name: MaterialDefaultUnitID :one
SELECT default_unit_id FROM inv_material WHERE id = $1
`

func (q *Queries) MaterialDefaultUnitID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, materialDefaultUnitID, id)
	var default_unit_id uuid.UUID
	err := row.Scan(&default_unit_id)
	return default_unit_id, err
}

const updateMaterialUnit = `-- name: UpdateMaterialUnit :one
UPDATE inv_material_unit
SET unit_id = $2,
    factor = $3,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, factor, inserted_at, updated_at, material_id, unit_id
`

type UpdateMaterialUnitParams struct {
	ID     uuid.UUID       `db:"id" json:"id"`
	UnitID uuid.UUID       `db:"unit_id" json:"unit_id"`
	Factor decimal.Decimal `db:"factor" json:"factor"`
}

func (q *Queries) UpdateMaterialUnit(ctx context.Context, arg UpdateMaterialUnitParams) (InvMaterialUnit, error) {
	row := q.db.QueryRow(ctx, updateMaterialUnit, arg.ID, arg.UnitID, arg.Factor)
	var i InvMaterialUnit
	err := row.Scan(
		&i.ID,
		&i.Factor,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}
