// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: numbering.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNumberingRule = `-- name: CreateNumberingRule :one
INSERT INTO sys_numbering_rule (resource, name, segments, per_company, enabled)
VALUES (
  $1,
  $2,
  ARRAY(SELECT value FROM jsonb_array_elements($5::jsonb)),
  $3,
  $4
)
RETURNING id, resource, name, to_json(segments) AS segments, per_company, enabled,
          inserted_at, updated_at
`

type CreateNumberingRuleParams struct {
	Resource   string `db:"resource" json:"resource"`
	Name       string `db:"name" json:"name"`
	PerCompany bool   `db:"per_company" json:"per_company"`
	Enabled    bool   `db:"enabled" json:"enabled"`
	Segments   []byte `db:"segments" json:"segments"`
}

type CreateNumberingRuleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Resource   string           `db:"resource" json:"resource"`
	Name       string           `db:"name" json:"name"`
	Segments   []byte           `db:"segments" json:"segments"`
	PerCompany bool             `db:"per_company" json:"per_company"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateNumberingRule(ctx context.Context, arg CreateNumberingRuleParams) (CreateNumberingRuleRow, error) {
	row := q.db.QueryRow(ctx, createNumberingRule,
		arg.Resource,
		arg.Name,
		arg.PerCompany,
		arg.Enabled,
		arg.Segments,
	)
	var i CreateNumberingRuleRow
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Name,
		&i.Segments,
		&i.PerCompany,
		&i.Enabled,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNumberingRule = `-- name: DeleteNumberingRule :execrows
DELETE FROM sys_numbering_rule WHERE id = $1
`

func (q *Queries) DeleteNumberingRule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNumberingRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnabledNumberingRule = `-- name: GetEnabledNumberingRule :one
SELECT id, resource, name, to_json(segments) AS segments, per_company, enabled,
       inserted_at, updated_at
FROM sys_numbering_rule
WHERE resource = $1 AND enabled = true
`

type GetEnabledNumberingRuleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Resource   string           `db:"resource" json:"resource"`
	Name       string           `db:"name" json:"name"`
	Segments   []byte           `db:"segments" json:"segments"`
	PerCompany bool             `db:"per_company" json:"per_company"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetEnabledNumberingRule(ctx context.Context, resource string) (GetEnabledNumberingRuleRow, error) {
	row := q.db.QueryRow(ctx, getEnabledNumberingRule, resource)
	var i GetEnabledNumberingRuleRow
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Name,
		&i.Segments,
		&i.PerCompany,
		&i.Enabled,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNumberingCounter = `-- name: GetNumberingCounter :one
SELECT id, rule_id, scope_key, value, inserted_at, updated_at
FROM sys_numbering_counter
WHERE id = $1
`

type GetNumberingCounterRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	RuleID     uuid.UUID        `db:"rule_id" json:"rule_id"`
	ScopeKey   string           `db:"scope_key" json:"scope_key"`
	Value      int64            `db:"value" json:"value"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetNumberingCounter(ctx context.Context, id uuid.UUID) (GetNumberingCounterRow, error) {
	row := q.db.QueryRow(ctx, getNumberingCounter, id)
	var i GetNumberingCounterRow
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ScopeKey,
		&i.Value,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNumberingRule = `-- name: GetNumberingRule :one
SELECT id, resource, name, to_json(segments) AS segments, per_company, enabled,
       inserted_at, updated_at
FROM sys_numbering_rule
WHERE id = $1
`

type GetNumberingRuleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Resource   string           `db:"resource" json:"resource"`
	Name       string           `db:"name" json:"name"`
	Segments   []byte           `db:"segments" json:"segments"`
	PerCompany bool             `db:"per_company" json:"per_company"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetNumberingRule(ctx context.Context, id uuid.UUID) (GetNumberingRuleRow, error) {
	row := q.db.QueryRow(ctx, getNumberingRule, id)
	var i GetNumberingRuleRow
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Name,
		&i.Segments,
		&i.PerCompany,
		&i.Enabled,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementNumberingCounter = `-- name: IncrementNumberingCounter :one
INSERT INTO sys_numbering_counter (rule_id, scope_key, value)
VALUES ($1, $2, 1)
ON CONFLICT (rule_id, scope_key)
DO UPDATE
SET value = sys_numbering_counter.value + 1,
    updated_at = (now() AT TIME ZONE 'utc')
RETURNING value
`

type IncrementNumberingCounterParams struct {
	RuleID   uuid.UUID `db:"rule_id" json:"rule_id"`
	ScopeKey string    `db:"scope_key" json:"scope_key"`
}

func (q *Queries) IncrementNumberingCounter(ctx context.Context, arg IncrementNumberingCounterParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementNumberingCounter, arg.RuleID, arg.ScopeKey)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const lockNumberingCounter = `-- name: LockNumberingCounter :one
SELECT id, rule_id, scope_key, value, inserted_at, updated_at
FROM sys_numbering_counter
WHERE id = $1
FOR UPDATE
`

type LockNumberingCounterRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	RuleID     uuid.UUID        `db:"rule_id" json:"rule_id"`
	ScopeKey   string           `db:"scope_key" json:"scope_key"`
	Value      int64            `db:"value" json:"value"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockNumberingCounter(ctx context.Context, id uuid.UUID) (LockNumberingCounterRow, error) {
	row := q.db.QueryRow(ctx, lockNumberingCounter, id)
	var i LockNumberingCounterRow
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ScopeKey,
		&i.Value,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockNumberingRule = `-- name: LockNumberingRule :one
SELECT id, resource, name, to_json(segments) AS segments, per_company, enabled,
       inserted_at, updated_at
FROM sys_numbering_rule
WHERE id = $1
FOR UPDATE
`

type LockNumberingRuleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Resource   string           `db:"resource" json:"resource"`
	Name       string           `db:"name" json:"name"`
	Segments   []byte           `db:"segments" json:"segments"`
	PerCompany bool             `db:"per_company" json:"per_company"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) LockNumberingRule(ctx context.Context, id uuid.UUID) (LockNumberingRuleRow, error) {
	row := q.db.QueryRow(ctx, lockNumberingRule, id)
	var i LockNumberingRuleRow
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Name,
		&i.Segments,
		&i.PerCompany,
		&i.Enabled,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNumberingCounter = `-- name: UpdateNumberingCounter :one
UPDATE sys_numbering_counter
SET value = $2, updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, rule_id, scope_key, value, inserted_at, updated_at
`

type UpdateNumberingCounterParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Value int64     `db:"value" json:"value"`
}

type UpdateNumberingCounterRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	RuleID     uuid.UUID        `db:"rule_id" json:"rule_id"`
	ScopeKey   string           `db:"scope_key" json:"scope_key"`
	Value      int64            `db:"value" json:"value"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateNumberingCounter(ctx context.Context, arg UpdateNumberingCounterParams) (UpdateNumberingCounterRow, error) {
	row := q.db.QueryRow(ctx, updateNumberingCounter, arg.ID, arg.Value)
	var i UpdateNumberingCounterRow
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ScopeKey,
		&i.Value,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNumberingRule = `-- name: UpdateNumberingRule :one
UPDATE sys_numbering_rule
SET name = $2,
    segments = ARRAY(SELECT value FROM jsonb_array_elements($5::jsonb)),
    per_company = $3,
    enabled = $4,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, resource, name, to_json(segments) AS segments, per_company, enabled,
          inserted_at, updated_at
`

type UpdateNumberingRuleParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Name       string    `db:"name" json:"name"`
	PerCompany bool      `db:"per_company" json:"per_company"`
	Enabled    bool      `db:"enabled" json:"enabled"`
	Segments   []byte    `db:"segments" json:"segments"`
}

type UpdateNumberingRuleRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Resource   string           `db:"resource" json:"resource"`
	Name       string           `db:"name" json:"name"`
	Segments   []byte           `db:"segments" json:"segments"`
	PerCompany bool             `db:"per_company" json:"per_company"`
	Enabled    bool             `db:"enabled" json:"enabled"`
	InsertedAt pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateNumberingRule(ctx context.Context, arg UpdateNumberingRuleParams) (UpdateNumberingRuleRow, error) {
	row := q.db.QueryRow(ctx, updateNumberingRule,
		arg.ID,
		arg.Name,
		arg.PerCompany,
		arg.Enabled,
		arg.Segments,
	)
	var i UpdateNumberingRuleRow
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Name,
		&i.Segments,
		&i.PerCompany,
		&i.Enabled,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
