// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: printing.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deletePrintTemplateAttachments = `-- name: DeletePrintTemplateAttachments :exec
DELETE FROM sys_attachment
WHERE owner_type = 'sys_print_template'
  AND owner_id = $1::uuid
`

func (q *Queries) DeletePrintTemplateAttachments(ctx context.Context, templateID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePrintTemplateAttachments, templateID)
	return err
}

const replacePrintTemplateAttachment = `-- name: ReplacePrintTemplateAttachment :exec
WITH removed AS (
  DELETE FROM sys_attachment
  WHERE owner_type = 'sys_print_template'
    AND owner_id = $2::uuid
)
INSERT INTO sys_attachment (file_id, owner_type, owner_id, category, company_id)
VALUES (
  $1::uuid,
  'sys_print_template',
  $2::uuid,
  'template',
  NULL
)
`

type ReplacePrintTemplateAttachmentParams struct {
	FileID     uuid.UUID `db:"file_id" json:"file_id"`
	TemplateID uuid.UUID `db:"template_id" json:"template_id"`
}

func (q *Queries) ReplacePrintTemplateAttachment(ctx context.Context, arg ReplacePrintTemplateAttachmentParams) error {
	_, err := q.db.Exec(ctx, replacePrintTemplateAttachment, arg.FileID, arg.TemplateID)
	return err
}
