// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const cancelStockEntriesForVoucher = `-- name: CancelStockEntriesForVoucher :execrows
UPDATE inv_stock_entry
SET is_cancelled = true,
    cancelled_at = $3
WHERE voucher_type = $1
  AND voucher_id = $2
  AND is_cancelled = false
`

type CancelStockEntriesForVoucherParams struct {
	VoucherType string           `db:"voucher_type" json:"voucher_type"`
	VoucherID   uuid.UUID        `db:"voucher_id" json:"voucher_id"`
	CancelledAt pgtype.Timestamp `db:"cancelled_at" json:"cancelled_at"`
}

func (q *Queries) CancelStockEntriesForVoucher(ctx context.Context, arg CancelStockEntriesForVoucherParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelStockEntriesForVoucher, arg.VoucherType, arg.VoucherID, arg.CancelledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const currentStockBalance = `-- name: CurrentStockBalance :one
SELECT COALESCE(sum(quantity), 0)::numeric
FROM inv_stock_entry
WHERE warehouse_id = $1
  AND material_id = $2
  AND is_cancelled = false
`

type CurrentStockBalanceParams struct {
	WarehouseID uuid.UUID `db:"warehouse_id" json:"warehouse_id"`
	MaterialID  uuid.UUID `db:"material_id" json:"material_id"`
}

func (q *Queries) CurrentStockBalance(ctx context.Context, arg CurrentStockBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, currentStockBalance, arg.WarehouseID, arg.MaterialID)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const getStockMaterials = `-- name: GetStockMaterials :many
SELECT id, code, name, spec, default_unit_id
FROM inv_material
WHERE id = ANY($1::uuid[])
`

type GetStockMaterialsRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Code          string      `db:"code" json:"code"`
	Name          string      `db:"name" json:"name"`
	Spec          pgtype.Text `db:"spec" json:"spec"`
	DefaultUnitID uuid.UUID   `db:"default_unit_id" json:"default_unit_id"`
}

func (q *Queries) GetStockMaterials(ctx context.Context, ids []uuid.UUID) ([]GetStockMaterialsRow, error) {
	rows, err := q.db.Query(ctx, getStockMaterials, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStockMaterialsRow{}
	for rows.Next() {
		var i GetStockMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Spec,
			&i.DefaultUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockWarehouses = `-- name: GetStockWarehouses :many
SELECT id, name, company_id, is_leaf, active, allow_negative
FROM inv_warehouse
WHERE id = ANY($1::uuid[])
`

type GetStockWarehousesRow struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Name          string    `db:"name" json:"name"`
	CompanyID     uuid.UUID `db:"company_id" json:"company_id"`
	IsLeaf        bool      `db:"is_leaf" json:"is_leaf"`
	Active        bool      `db:"active" json:"active"`
	AllowNegative bool      `db:"allow_negative" json:"allow_negative"`
}

func (q *Queries) GetStockWarehouses(ctx context.Context, ids []uuid.UUID) ([]GetStockWarehousesRow, error) {
	rows, err := q.db.Query(ctx, getStockWarehouses, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStockWarehousesRow{}
	for rows.Next() {
		var i GetStockWarehousesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CompanyID,
			&i.IsLeaf,
			&i.Active,
			&i.AllowNegative,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStockEntry = `-- name: InsertStockEntry :one
INSERT INTO inv_stock_entry (
  company_id, warehouse_id, material_id, quantity, posting_date,
  voucher_type, voucher_id, voucher_no, remarks
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, seq, quantity, posting_date, voucher_type, voucher_id, voucher_no,
          is_cancelled, cancelled_at, remarks, inserted_at,
          company_id, warehouse_id, material_id
`

type InsertStockEntryParams struct {
	CompanyID   uuid.UUID       `db:"company_id" json:"company_id"`
	WarehouseID uuid.UUID       `db:"warehouse_id" json:"warehouse_id"`
	MaterialID  uuid.UUID       `db:"material_id" json:"material_id"`
	Quantity    decimal.Decimal `db:"quantity" json:"quantity"`
	PostingDate pgtype.Date     `db:"posting_date" json:"posting_date"`
	VoucherType string          `db:"voucher_type" json:"voucher_type"`
	VoucherID   uuid.UUID       `db:"voucher_id" json:"voucher_id"`
	VoucherNo   string          `db:"voucher_no" json:"voucher_no"`
	Remarks     pgtype.Text     `db:"remarks" json:"remarks"`
}

type InsertStockEntryRow struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Seq         int64            `db:"seq" json:"seq"`
	Quantity    decimal.Decimal  `db:"quantity" json:"quantity"`
	PostingDate pgtype.Date      `db:"posting_date" json:"posting_date"`
	VoucherType string           `db:"voucher_type" json:"voucher_type"`
	VoucherID   uuid.UUID        `db:"voucher_id" json:"voucher_id"`
	VoucherNo   string           `db:"voucher_no" json:"voucher_no"`
	IsCancelled bool             `db:"is_cancelled" json:"is_cancelled"`
	CancelledAt pgtype.Timestamp `db:"cancelled_at" json:"cancelled_at"`
	Remarks     pgtype.Text      `db:"remarks" json:"remarks"`
	InsertedAt  pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	CompanyID   uuid.UUID        `db:"company_id" json:"company_id"`
	WarehouseID uuid.UUID        `db:"warehouse_id" json:"warehouse_id"`
	MaterialID  uuid.UUID        `db:"material_id" json:"material_id"`
}

func (q *Queries) InsertStockEntry(ctx context.Context, arg InsertStockEntryParams) (InsertStockEntryRow, error) {
	row := q.db.QueryRow(ctx, insertStockEntry,
		arg.CompanyID,
		arg.WarehouseID,
		arg.MaterialID,
		arg.Quantity,
		arg.PostingDate,
		arg.VoucherType,
		arg.VoucherID,
		arg.VoucherNo,
		arg.Remarks,
	)
	var i InsertStockEntryRow
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Quantity,
		&i.PostingDate,
		&i.VoucherType,
		&i.VoucherID,
		&i.VoucherNo,
		&i.IsCancelled,
		&i.CancelledAt,
		&i.Remarks,
		&i.InsertedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.MaterialID,
	)
	return i, err
}

const listLiveStockEntriesForVoucher = `-- name: ListLiveStockEntriesForVoucher :many
SELECT id, seq, quantity, posting_date, voucher_type, voucher_id, voucher_no,
       is_cancelled, cancelled_at, remarks, inserted_at,
       company_id, warehouse_id, material_id
FROM inv_stock_entry
WHERE voucher_type = $1
  AND voucher_id = $2
  AND is_cancelled = false
ORDER BY seq ASC
`

type ListLiveStockEntriesForVoucherParams struct {
	VoucherType string    `db:"voucher_type" json:"voucher_type"`
	VoucherID   uuid.UUID `db:"voucher_id" json:"voucher_id"`
}

type ListLiveStockEntriesForVoucherRow struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Seq         int64            `db:"seq" json:"seq"`
	Quantity    decimal.Decimal  `db:"quantity" json:"quantity"`
	PostingDate pgtype.Date      `db:"posting_date" json:"posting_date"`
	VoucherType string           `db:"voucher_type" json:"voucher_type"`
	VoucherID   uuid.UUID        `db:"voucher_id" json:"voucher_id"`
	VoucherNo   string           `db:"voucher_no" json:"voucher_no"`
	IsCancelled bool             `db:"is_cancelled" json:"is_cancelled"`
	CancelledAt pgtype.Timestamp `db:"cancelled_at" json:"cancelled_at"`
	Remarks     pgtype.Text      `db:"remarks" json:"remarks"`
	InsertedAt  pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	CompanyID   uuid.UUID        `db:"company_id" json:"company_id"`
	WarehouseID uuid.UUID        `db:"warehouse_id" json:"warehouse_id"`
	MaterialID  uuid.UUID        `db:"material_id" json:"material_id"`
}

func (q *Queries) ListLiveStockEntriesForVoucher(ctx context.Context, arg ListLiveStockEntriesForVoucherParams) ([]ListLiveStockEntriesForVoucherRow, error) {
	rows, err := q.db.Query(ctx, listLiveStockEntriesForVoucher, arg.VoucherType, arg.VoucherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveStockEntriesForVoucherRow{}
	for rows.Next() {
		var i ListLiveStockEntriesForVoucherRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Quantity,
			&i.PostingDate,
			&i.VoucherType,
			&i.VoucherID,
			&i.VoucherNo,
			&i.IsCancelled,
			&i.CancelledAt,
			&i.Remarks,
			&i.InsertedAt,
			&i.CompanyID,
			&i.WarehouseID,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStockBalanceKey = `-- name: LockStockBalanceKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockStockBalanceKey(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockStockBalanceKey, lockKey)
	return err
}

const stockBalance = `-- name: StockBalance :many
SELECT e.warehouse_id,
       w.name AS warehouse_name,
       e.material_id,
       m.code AS material_code,
       m.name AS material_name,
       m.spec AS material_spec,
       u.name AS unit_name,
       sum(e.quantity)::numeric AS quantity
FROM inv_stock_entry AS e
JOIN inv_warehouse AS w ON w.id = e.warehouse_id
JOIN inv_material AS m ON m.id = e.material_id
JOIN bas_unit AS u ON u.id = m.default_unit_id
WHERE e.company_id = $1
  AND e.is_cancelled = false
  AND e.posting_date <= $2
  AND ($3::uuid IS NULL OR e.warehouse_id = $3)
  AND ($4::uuid IS NULL OR e.material_id = $4)
GROUP BY e.warehouse_id, w.name, e.material_id, m.code, m.name, m.spec, u.name
HAVING (NOT $5::boolean OR sum(e.quantity) <> 0)
ORDER BY w.name ASC, m.code ASC, e.warehouse_id ASC, e.material_id ASC
`

type StockBalanceParams struct {
	CompanyID   uuid.UUID   `db:"company_id" json:"company_id"`
	AsOf        pgtype.Date `db:"as_of" json:"as_of"`
	WarehouseID *uuid.UUID  `db:"warehouse_id" json:"warehouse_id"`
	MaterialID  *uuid.UUID  `db:"material_id" json:"material_id"`
	HideZero    bool        `db:"hide_zero" json:"hide_zero"`
}

type StockBalanceRow struct {
	WarehouseID   uuid.UUID       `db:"warehouse_id" json:"warehouse_id"`
	WarehouseName string          `db:"warehouse_name" json:"warehouse_name"`
	MaterialID    uuid.UUID       `db:"material_id" json:"material_id"`
	MaterialCode  string          `db:"material_code" json:"material_code"`
	MaterialName  string          `db:"material_name" json:"material_name"`
	MaterialSpec  pgtype.Text     `db:"material_spec" json:"material_spec"`
	UnitName      string          `db:"unit_name" json:"unit_name"`
	Quantity      decimal.Decimal `db:"quantity" json:"quantity"`
}

func (q *Queries) StockBalance(ctx context.Context, arg StockBalanceParams) ([]StockBalanceRow, error) {
	rows, err := q.db.Query(ctx, stockBalance,
		arg.CompanyID,
		arg.AsOf,
		arg.WarehouseID,
		arg.MaterialID,
		arg.HideZero,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockBalanceRow{}
	for rows.Next() {
		var i StockBalanceRow
		if err := rows.Scan(
			&i.WarehouseID,
			&i.WarehouseName,
			&i.MaterialID,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
