// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_transfer.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createStockTransfer = `-- name: CreateStockTransfer :one
INSERT INTO inv_stock_transfer (
  doc_no, doc_date, summary, remarks, company_id, from_warehouse_id,
  to_warehouse_id, transit_warehouse_id, created_by_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, doc_no, doc_date, summary, remarks, status, shipped_at, received_at,
          inserted_at, updated_at, company_id, from_warehouse_id, to_warehouse_id,
          transit_warehouse_id, created_by_id, shipped_by_id, received_by_id
`

type CreateStockTransferParams struct {
	DocNo              string      `db:"doc_no" json:"doc_no"`
	DocDate            pgtype.Date `db:"doc_date" json:"doc_date"`
	Summary            pgtype.Text `db:"summary" json:"summary"`
	Remarks            pgtype.Text `db:"remarks" json:"remarks"`
	CompanyID          uuid.UUID   `db:"company_id" json:"company_id"`
	FromWarehouseID    uuid.UUID   `db:"from_warehouse_id" json:"from_warehouse_id"`
	ToWarehouseID      uuid.UUID   `db:"to_warehouse_id" json:"to_warehouse_id"`
	TransitWarehouseID uuid.UUID   `db:"transit_warehouse_id" json:"transit_warehouse_id"`
	CreatedByID        *uuid.UUID  `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateStockTransfer(ctx context.Context, arg CreateStockTransferParams) (InvStockTransfer, error) {
	row := q.db.QueryRow(ctx, createStockTransfer,
		arg.DocNo,
		arg.DocDate,
		arg.Summary,
		arg.Remarks,
		arg.CompanyID,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.TransitWarehouseID,
		arg.CreatedByID,
	)
	var i InvStockTransfer
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TransitWarehouseID,
		&i.CreatedByID,
		&i.ShippedByID,
		&i.ReceivedByID,
	)
	return i, err
}

const createStockTransferItem = `-- name: CreateStockTransferItem :one
INSERT INTO inv_stock_transfer_item (
  idx, qty, base_qty, material_code, material_name, material_spec, unit_name,
  remark, stock_transfer_id, company_id, material_id, unit_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, idx, qty, base_qty, received_qty, material_code, material_name,
          material_spec, unit_name, remark, inserted_at, updated_at,
          stock_transfer_id, company_id, material_id, unit_id
`

type CreateStockTransferItemParams struct {
	Idx             int64           `db:"idx" json:"idx"`
	Qty             decimal.Decimal `db:"qty" json:"qty"`
	BaseQty         decimal.Decimal `db:"base_qty" json:"base_qty"`
	MaterialCode    string          `db:"material_code" json:"material_code"`
	MaterialName    string          `db:"material_name" json:"material_name"`
	MaterialSpec    pgtype.Text     `db:"material_spec" json:"material_spec"`
	UnitName        string          `db:"unit_name" json:"unit_name"`
	Remark          pgtype.Text     `db:"remark" json:"remark"`
	StockTransferID uuid.UUID       `db:"stock_transfer_id" json:"stock_transfer_id"`
	CompanyID       uuid.UUID       `db:"company_id" json:"company_id"`
	MaterialID      uuid.UUID       `db:"material_id" json:"material_id"`
	UnitID          uuid.UUID       `db:"unit_id" json:"unit_id"`
}

func (q *Queries) CreateStockTransferItem(ctx context.Context, arg CreateStockTransferItemParams) (InvStockTransferItem, error) {
	row := q.db.QueryRow(ctx, createStockTransferItem,
		arg.Idx,
		arg.Qty,
		arg.BaseQty,
		arg.MaterialCode,
		arg.MaterialName,
		arg.MaterialSpec,
		arg.UnitName,
		arg.Remark,
		arg.StockTransferID,
		arg.CompanyID,
		arg.MaterialID,
		arg.UnitID,
	)
	var i InvStockTransferItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.ReceivedQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockTransferID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const deleteStockTransfer = `-- name: DeleteStockTransfer :execrows
DELETE FROM inv_stock_transfer WHERE id = $1
`

func (q *Queries) DeleteStockTransfer(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStockTransfer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStockTransferItem = `-- name: DeleteStockTransferItem :execrows
DELETE FROM inv_stock_transfer_item WHERE id = $1
`

func (q *Queries) DeleteStockTransferItem(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStockTransferItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStockTransfer = `-- name: GetStockTransfer :one
SELECT id, doc_no, doc_date, summary, remarks, status, shipped_at, received_at,
       inserted_at, updated_at, company_id, from_warehouse_id, to_warehouse_id,
       transit_warehouse_id, created_by_id, shipped_by_id, received_by_id
FROM inv_stock_transfer
WHERE id = $1
`

func (q *Queries) GetStockTransfer(ctx context.Context, id uuid.UUID) (InvStockTransfer, error) {
	row := q.db.QueryRow(ctx, getStockTransfer, id)
	var i InvStockTransfer
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TransitWarehouseID,
		&i.CreatedByID,
		&i.ShippedByID,
		&i.ReceivedByID,
	)
	return i, err
}

const getStockTransferItem = `-- name: GetStockTransferItem :one
SELECT id, idx, qty, base_qty, received_qty, material_code, material_name,
       material_spec, unit_name, remark, inserted_at, updated_at,
       stock_transfer_id, company_id, material_id, unit_id
FROM inv_stock_transfer_item
WHERE id = $1
`

func (q *Queries) GetStockTransferItem(ctx context.Context, id uuid.UUID) (InvStockTransferItem, error) {
	row := q.db.QueryRow(ctx, getStockTransferItem, id)
	var i InvStockTransferItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.ReceivedQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockTransferID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const getStockTransferItemProjection = `-- name: GetStockTransferItemProjection :one
SELECT m.code AS material_code,
       m.name AS material_name,
       m.spec AS material_spec,
       m.default_unit_id,
       u.name AS unit_name,
       mu.factor AS conversion_factor
FROM inv_material AS m
JOIN bas_unit AS u ON u.id = $1
LEFT JOIN inv_material_unit AS mu
  ON mu.material_id = m.id
 AND mu.unit_id = $1
WHERE m.id = $2
`

type GetStockTransferItemProjectionParams struct {
	UnitID     uuid.UUID `db:"unit_id" json:"unit_id"`
	MaterialID uuid.UUID `db:"material_id" json:"material_id"`
}

type GetStockTransferItemProjectionRow struct {
	MaterialCode     string         `db:"material_code" json:"material_code"`
	MaterialName     string         `db:"material_name" json:"material_name"`
	MaterialSpec     pgtype.Text    `db:"material_spec" json:"material_spec"`
	DefaultUnitID    uuid.UUID      `db:"default_unit_id" json:"default_unit_id"`
	UnitName         string         `db:"unit_name" json:"unit_name"`
	ConversionFactor pgtype.Numeric `db:"conversion_factor" json:"conversion_factor"`
}

func (q *Queries) GetStockTransferItemProjection(ctx context.Context, arg GetStockTransferItemProjectionParams) (GetStockTransferItemProjectionRow, error) {
	row := q.db.QueryRow(ctx, getStockTransferItemProjection, arg.UnitID, arg.MaterialID)
	var i GetStockTransferItemProjectionRow
	err := row.Scan(
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.DefaultUnitID,
		&i.UnitName,
		&i.ConversionFactor,
	)
	return i, err
}

const listStockTransferItems = `-- name: ListStockTransferItems :many
SELECT id, idx, qty, base_qty, received_qty, material_code, material_name,
       material_spec, unit_name, remark, inserted_at, updated_at,
       stock_transfer_id, company_id, material_id, unit_id
FROM inv_stock_transfer_item
WHERE stock_transfer_id = $1
ORDER BY idx ASC, id ASC
`

func (q *Queries) ListStockTransferItems(ctx context.Context, stockTransferID uuid.UUID) ([]InvStockTransferItem, error) {
	rows, err := q.db.Query(ctx, listStockTransferItems, stockTransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvStockTransferItem{}
	for rows.Next() {
		var i InvStockTransferItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.ReceivedQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.Remark,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.StockTransferID,
			&i.CompanyID,
			&i.MaterialID,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStockTransfer = `-- name: LockStockTransfer :one
SELECT id, doc_no, doc_date, summary, remarks, status, shipped_at, received_at,
       inserted_at, updated_at, company_id, from_warehouse_id, to_warehouse_id,
       transit_warehouse_id, created_by_id, shipped_by_id, received_by_id
FROM inv_stock_transfer
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockStockTransfer(ctx context.Context, id uuid.UUID) (InvStockTransfer, error) {
	row := q.db.QueryRow(ctx, lockStockTransfer, id)
	var i InvStockTransfer
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TransitWarehouseID,
		&i.CreatedByID,
		&i.ShippedByID,
		&i.ReceivedByID,
	)
	return i, err
}

const lockStockTransferItem = `-- name: LockStockTransferItem :one
SELECT id, idx, qty, base_qty, received_qty, material_code, material_name,
       material_spec, unit_name, remark, inserted_at, updated_at,
       stock_transfer_id, company_id, material_id, unit_id
FROM inv_stock_transfer_item
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockStockTransferItem(ctx context.Context, id uuid.UUID) (InvStockTransferItem, error) {
	row := q.db.QueryRow(ctx, lockStockTransferItem, id)
	var i InvStockTransferItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.ReceivedQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockTransferID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const receiveStockTransfer = `-- name: ReceiveStockTransfer :one
UPDATE inv_stock_transfer
SET status = 'received',
    received_at = $1,
    received_by_id = $2::uuid,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $3
RETURNING id, doc_no, doc_date, summary, remarks, status, shipped_at, received_at,
          inserted_at, updated_at, company_id, from_warehouse_id, to_warehouse_id,
          transit_warehouse_id, created_by_id, shipped_by_id, received_by_id
`

type ReceiveStockTransferParams struct {
	ReceivedAt   pgtype.Timestamp `db:"received_at" json:"received_at"`
	ReceivedByID *uuid.UUID       `db:"received_by_id" json:"received_by_id"`
	ID           uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) ReceiveStockTransfer(ctx context.Context, arg ReceiveStockTransferParams) (InvStockTransfer, error) {
	row := q.db.QueryRow(ctx, receiveStockTransfer, arg.ReceivedAt, arg.ReceivedByID, arg.ID)
	var i InvStockTransfer
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TransitWarehouseID,
		&i.CreatedByID,
		&i.ShippedByID,
		&i.ReceivedByID,
	)
	return i, err
}

const shipStockTransfer = `-- name: ShipStockTransfer :one
UPDATE inv_stock_transfer
SET status = 'shipped',
    shipped_at = $1,
    shipped_by_id = $2::uuid,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $3
RETURNING id, doc_no, doc_date, summary, remarks, status, shipped_at, received_at,
          inserted_at, updated_at, company_id, from_warehouse_id, to_warehouse_id,
          transit_warehouse_id, created_by_id, shipped_by_id, received_by_id
`

type ShipStockTransferParams struct {
	ShippedAt   pgtype.Timestamp `db:"shipped_at" json:"shipped_at"`
	ShippedByID *uuid.UUID       `db:"shipped_by_id" json:"shipped_by_id"`
	ID          uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) ShipStockTransfer(ctx context.Context, arg ShipStockTransferParams) (InvStockTransfer, error) {
	row := q.db.QueryRow(ctx, shipStockTransfer, arg.ShippedAt, arg.ShippedByID, arg.ID)
	var i InvStockTransfer
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TransitWarehouseID,
		&i.CreatedByID,
		&i.ShippedByID,
		&i.ReceivedByID,
	)
	return i, err
}

const updateStockTransfer = `-- name: UpdateStockTransfer :one
UPDATE inv_stock_transfer
SET doc_no = $2,
    doc_date = $3,
    summary = $4,
    remarks = $5,
    from_warehouse_id = $6,
    to_warehouse_id = $7,
    transit_warehouse_id = $8,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, doc_no, doc_date, summary, remarks, status, shipped_at, received_at,
          inserted_at, updated_at, company_id, from_warehouse_id, to_warehouse_id,
          transit_warehouse_id, created_by_id, shipped_by_id, received_by_id
`

type UpdateStockTransferParams struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	DocNo              string      `db:"doc_no" json:"doc_no"`
	DocDate            pgtype.Date `db:"doc_date" json:"doc_date"`
	Summary            pgtype.Text `db:"summary" json:"summary"`
	Remarks            pgtype.Text `db:"remarks" json:"remarks"`
	FromWarehouseID    uuid.UUID   `db:"from_warehouse_id" json:"from_warehouse_id"`
	ToWarehouseID      uuid.UUID   `db:"to_warehouse_id" json:"to_warehouse_id"`
	TransitWarehouseID uuid.UUID   `db:"transit_warehouse_id" json:"transit_warehouse_id"`
}

func (q *Queries) UpdateStockTransfer(ctx context.Context, arg UpdateStockTransferParams) (InvStockTransfer, error) {
	row := q.db.QueryRow(ctx, updateStockTransfer,
		arg.ID,
		arg.DocNo,
		arg.DocDate,
		arg.Summary,
		arg.Remarks,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.TransitWarehouseID,
	)
	var i InvStockTransfer
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TransitWarehouseID,
		&i.CreatedByID,
		&i.ShippedByID,
		&i.ReceivedByID,
	)
	return i, err
}

const updateStockTransferItem = `-- name: UpdateStockTransferItem :one
UPDATE inv_stock_transfer_item
SET idx = $2,
    qty = $3,
    base_qty = $4,
    material_code = $5,
    material_name = $6,
    material_spec = $7,
    unit_name = $8,
    remark = $9,
    material_id = $10,
    unit_id = $11,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, idx, qty, base_qty, received_qty, material_code, material_name,
          material_spec, unit_name, remark, inserted_at, updated_at,
          stock_transfer_id, company_id, material_id, unit_id
`

type UpdateStockTransferItemParams struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	Idx          int64           `db:"idx" json:"idx"`
	Qty          decimal.Decimal `db:"qty" json:"qty"`
	BaseQty      decimal.Decimal `db:"base_qty" json:"base_qty"`
	MaterialCode string          `db:"material_code" json:"material_code"`
	MaterialName string          `db:"material_name" json:"material_name"`
	MaterialSpec pgtype.Text     `db:"material_spec" json:"material_spec"`
	UnitName     string          `db:"unit_name" json:"unit_name"`
	Remark       pgtype.Text     `db:"remark" json:"remark"`
	MaterialID   uuid.UUID       `db:"material_id" json:"material_id"`
	UnitID       uuid.UUID       `db:"unit_id" json:"unit_id"`
}

func (q *Queries) UpdateStockTransferItem(ctx context.Context, arg UpdateStockTransferItemParams) (InvStockTransferItem, error) {
	row := q.db.QueryRow(ctx, updateStockTransferItem,
		arg.ID,
		arg.Idx,
		arg.Qty,
		arg.BaseQty,
		arg.MaterialCode,
		arg.MaterialName,
		arg.MaterialSpec,
		arg.UnitName,
		arg.Remark,
		arg.MaterialID,
		arg.UnitID,
	)
	var i InvStockTransferItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.ReceivedQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockTransferID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const writeStockTransferItemReceivedQty = `-- name: WriteStockTransferItemReceivedQty :one
UPDATE inv_stock_transfer_item
SET received_qty = $2,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, idx, qty, base_qty, received_qty, material_code, material_name,
          material_spec, unit_name, remark, inserted_at, updated_at,
          stock_transfer_id, company_id, material_id, unit_id
`

type WriteStockTransferItemReceivedQtyParams struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	ReceivedQty pgtype.Numeric `db:"received_qty" json:"received_qty"`
}

func (q *Queries) WriteStockTransferItemReceivedQty(ctx context.Context, arg WriteStockTransferItemReceivedQtyParams) (InvStockTransferItem, error) {
	row := q.db.QueryRow(ctx, writeStockTransferItemReceivedQty, arg.ID, arg.ReceivedQty)
	var i InvStockTransferItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.ReceivedQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockTransferID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}
