// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: stock_doc.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const auditStockDoc = `-- name: AuditStockDoc :one
UPDATE inv_stock_doc
SET status = 'audited',
    audited_at = $1,
    audited_by_id = $2::uuid,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $3
RETURNING id, doc_no, direction, doc_date, summary, remarks, status, audited_at,
          inserted_at, updated_at, company_id, warehouse_id, created_by_id, audited_by_id
`

type AuditStockDocParams struct {
	AuditedAt   pgtype.Timestamp `db:"audited_at" json:"audited_at"`
	AuditedByID *uuid.UUID       `db:"audited_by_id" json:"audited_by_id"`
	ID          uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) AuditStockDoc(ctx context.Context, arg AuditStockDocParams) (InvStockDoc, error) {
	row := q.db.QueryRow(ctx, auditStockDoc, arg.AuditedAt, arg.AuditedByID, arg.ID)
	var i InvStockDoc
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Direction,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const countStockDocs = `-- name: CountStockDocs :one
SELECT count(*)
FROM inv_stock_doc
WHERE ($1::boolean OR company_id = ANY($2::uuid[]))
`

type CountStockDocsParams struct {
	ScopeBypass bool        `db:"scope_bypass" json:"scope_bypass"`
	CompanyIds  []uuid.UUID `db:"company_ids" json:"company_ids"`
}

func (q *Queries) CountStockDocs(ctx context.Context, arg CountStockDocsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStockDocs, arg.ScopeBypass, arg.CompanyIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStockDoc = `-- name: CreateStockDoc :one
INSERT INTO inv_stock_doc (
  doc_no, direction, doc_date, summary, remarks, company_id, warehouse_id, created_by_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, doc_no, direction, doc_date, summary, remarks, status, audited_at,
          inserted_at, updated_at, company_id, warehouse_id, created_by_id, audited_by_id
`

type CreateStockDocParams struct {
	DocNo       string      `db:"doc_no" json:"doc_no"`
	Direction   string      `db:"direction" json:"direction"`
	DocDate     pgtype.Date `db:"doc_date" json:"doc_date"`
	Summary     pgtype.Text `db:"summary" json:"summary"`
	Remarks     pgtype.Text `db:"remarks" json:"remarks"`
	CompanyID   uuid.UUID   `db:"company_id" json:"company_id"`
	WarehouseID uuid.UUID   `db:"warehouse_id" json:"warehouse_id"`
	CreatedByID *uuid.UUID  `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateStockDoc(ctx context.Context, arg CreateStockDocParams) (InvStockDoc, error) {
	row := q.db.QueryRow(ctx, createStockDoc,
		arg.DocNo,
		arg.Direction,
		arg.DocDate,
		arg.Summary,
		arg.Remarks,
		arg.CompanyID,
		arg.WarehouseID,
		arg.CreatedByID,
	)
	var i InvStockDoc
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Direction,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const createStockDocItem = `-- name: CreateStockDocItem :one
INSERT INTO inv_stock_doc_item (
  idx, qty, base_qty, material_code, material_name, material_spec, unit_name, remark,
  stock_doc_id, company_id, material_id, unit_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name,
          remark, inserted_at, updated_at, stock_doc_id, company_id, material_id, unit_id
`

type CreateStockDocItemParams struct {
	Idx          int64           `db:"idx" json:"idx"`
	Qty          decimal.Decimal `db:"qty" json:"qty"`
	BaseQty      decimal.Decimal `db:"base_qty" json:"base_qty"`
	MaterialCode string          `db:"material_code" json:"material_code"`
	MaterialName string          `db:"material_name" json:"material_name"`
	MaterialSpec pgtype.Text     `db:"material_spec" json:"material_spec"`
	UnitName     string          `db:"unit_name" json:"unit_name"`
	Remark       pgtype.Text     `db:"remark" json:"remark"`
	StockDocID   uuid.UUID       `db:"stock_doc_id" json:"stock_doc_id"`
	CompanyID    uuid.UUID       `db:"company_id" json:"company_id"`
	MaterialID   uuid.UUID       `db:"material_id" json:"material_id"`
	UnitID       uuid.UUID       `db:"unit_id" json:"unit_id"`
}

func (q *Queries) CreateStockDocItem(ctx context.Context, arg CreateStockDocItemParams) (InvStockDocItem, error) {
	row := q.db.QueryRow(ctx, createStockDocItem,
		arg.Idx,
		arg.Qty,
		arg.BaseQty,
		arg.MaterialCode,
		arg.MaterialName,
		arg.MaterialSpec,
		arg.UnitName,
		arg.Remark,
		arg.StockDocID,
		arg.CompanyID,
		arg.MaterialID,
		arg.UnitID,
	)
	var i InvStockDocItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockDocID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const deleteStockDoc = `-- name: DeleteStockDoc :execrows
DELETE FROM inv_stock_doc WHERE id = $1
`

func (q *Queries) DeleteStockDoc(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStockDoc, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStockDocItem = `-- name: DeleteStockDocItem :execrows
DELETE FROM inv_stock_doc_item WHERE id = $1
`

func (q *Queries) DeleteStockDocItem(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStockDocItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStockDoc = `-- name: GetStockDoc :one
SELECT id, doc_no, direction, doc_date, summary, remarks, status, audited_at,
       inserted_at, updated_at, company_id, warehouse_id, created_by_id, audited_by_id
FROM inv_stock_doc
WHERE id = $1
`

func (q *Queries) GetStockDoc(ctx context.Context, id uuid.UUID) (InvStockDoc, error) {
	row := q.db.QueryRow(ctx, getStockDoc, id)
	var i InvStockDoc
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Direction,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const getStockDocItem = `-- name: GetStockDocItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name,
       remark, inserted_at, updated_at, stock_doc_id, company_id, material_id, unit_id
FROM inv_stock_doc_item
WHERE id = $1
`

func (q *Queries) GetStockDocItem(ctx context.Context, id uuid.UUID) (InvStockDocItem, error) {
	row := q.db.QueryRow(ctx, getStockDocItem, id)
	var i InvStockDocItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockDocID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const getStockItemProjection = `-- name: GetStockItemProjection :one
SELECT m.code AS material_code,
       m.name AS material_name,
       m.spec AS material_spec,
       m.default_unit_id,
       u.name AS unit_name,
       mu.factor AS conversion_factor
FROM inv_material AS m
JOIN bas_unit AS u ON u.id = $1
LEFT JOIN inv_material_unit AS mu
  ON mu.material_id = m.id
 AND mu.unit_id = $1
WHERE m.id = $2
`

type GetStockItemProjectionParams struct {
	UnitID     uuid.UUID `db:"unit_id" json:"unit_id"`
	MaterialID uuid.UUID `db:"material_id" json:"material_id"`
}

type GetStockItemProjectionRow struct {
	MaterialCode     string         `db:"material_code" json:"material_code"`
	MaterialName     string         `db:"material_name" json:"material_name"`
	MaterialSpec     pgtype.Text    `db:"material_spec" json:"material_spec"`
	DefaultUnitID    uuid.UUID      `db:"default_unit_id" json:"default_unit_id"`
	UnitName         string         `db:"unit_name" json:"unit_name"`
	ConversionFactor pgtype.Numeric `db:"conversion_factor" json:"conversion_factor"`
}

func (q *Queries) GetStockItemProjection(ctx context.Context, arg GetStockItemProjectionParams) (GetStockItemProjectionRow, error) {
	row := q.db.QueryRow(ctx, getStockItemProjection, arg.UnitID, arg.MaterialID)
	var i GetStockItemProjectionRow
	err := row.Scan(
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.DefaultUnitID,
		&i.UnitName,
		&i.ConversionFactor,
	)
	return i, err
}

const listStockDocItems = `-- name: ListStockDocItems :many
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name,
       remark, inserted_at, updated_at, stock_doc_id, company_id, material_id, unit_id
FROM inv_stock_doc_item
WHERE stock_doc_id = $1
ORDER BY idx ASC, id ASC
`

func (q *Queries) ListStockDocItems(ctx context.Context, stockDocID uuid.UUID) ([]InvStockDocItem, error) {
	rows, err := q.db.Query(ctx, listStockDocItems, stockDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvStockDocItem{}
	for rows.Next() {
		var i InvStockDocItem
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Qty,
			&i.BaseQty,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialSpec,
			&i.UnitName,
			&i.Remark,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.StockDocID,
			&i.CompanyID,
			&i.MaterialID,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockDocs = `-- name: ListStockDocs :many
SELECT id, doc_no, direction, doc_date, summary, remarks, status, audited_at,
       inserted_at, updated_at, company_id, warehouse_id, created_by_id, audited_by_id
FROM inv_stock_doc
WHERE ($1::boolean OR company_id = ANY($2::uuid[]))
ORDER BY doc_no ASC, id ASC
LIMIT $4 OFFSET $3
`

type ListStockDocsParams struct {
	ScopeBypass bool        `db:"scope_bypass" json:"scope_bypass"`
	CompanyIds  []uuid.UUID `db:"company_ids" json:"company_ids"`
	RowOffset   int32       `db:"row_offset" json:"row_offset"`
	RowLimit    int32       `db:"row_limit" json:"row_limit"`
}

func (q *Queries) ListStockDocs(ctx context.Context, arg ListStockDocsParams) ([]InvStockDoc, error) {
	rows, err := q.db.Query(ctx, listStockDocs,
		arg.ScopeBypass,
		arg.CompanyIds,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvStockDoc{}
	for rows.Next() {
		var i InvStockDoc
		if err := rows.Scan(
			&i.ID,
			&i.DocNo,
			&i.Direction,
			&i.DocDate,
			&i.Summary,
			&i.Remarks,
			&i.Status,
			&i.AuditedAt,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.CompanyID,
			&i.WarehouseID,
			&i.CreatedByID,
			&i.AuditedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStockDoc = `-- name: LockStockDoc :one
SELECT id, doc_no, direction, doc_date, summary, remarks, status, audited_at,
       inserted_at, updated_at, company_id, warehouse_id, created_by_id, audited_by_id
FROM inv_stock_doc
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockStockDoc(ctx context.Context, id uuid.UUID) (InvStockDoc, error) {
	row := q.db.QueryRow(ctx, lockStockDoc, id)
	var i InvStockDoc
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Direction,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const lockStockDocItem = `-- name: LockStockDocItem :one
SELECT id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name,
       remark, inserted_at, updated_at, stock_doc_id, company_id, material_id, unit_id
FROM inv_stock_doc_item
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockStockDocItem(ctx context.Context, id uuid.UUID) (InvStockDocItem, error) {
	row := q.db.QueryRow(ctx, lockStockDocItem, id)
	var i InvStockDocItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockDocID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const stockDocHasItems = `-- name: StockDocHasItems :one
SELECT EXISTS(SELECT 1 FROM inv_stock_doc_item WHERE stock_doc_id = $1)
`

func (q *Queries) StockDocHasItems(ctx context.Context, stockDocID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, stockDocHasItems, stockDocID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStockDoc = `-- name: UpdateStockDoc :one
UPDATE inv_stock_doc
SET doc_no = $2,
    doc_date = $3,
    summary = $4,
    remarks = $5,
    warehouse_id = $6,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, doc_no, direction, doc_date, summary, remarks, status, audited_at,
          inserted_at, updated_at, company_id, warehouse_id, created_by_id, audited_by_id
`

type UpdateStockDocParams struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	DocNo       string      `db:"doc_no" json:"doc_no"`
	DocDate     pgtype.Date `db:"doc_date" json:"doc_date"`
	Summary     pgtype.Text `db:"summary" json:"summary"`
	Remarks     pgtype.Text `db:"remarks" json:"remarks"`
	WarehouseID uuid.UUID   `db:"warehouse_id" json:"warehouse_id"`
}

func (q *Queries) UpdateStockDoc(ctx context.Context, arg UpdateStockDocParams) (InvStockDoc, error) {
	row := q.db.QueryRow(ctx, updateStockDoc,
		arg.ID,
		arg.DocNo,
		arg.DocDate,
		arg.Summary,
		arg.Remarks,
		arg.WarehouseID,
	)
	var i InvStockDoc
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Direction,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}

const updateStockDocItem = `-- name: UpdateStockDocItem :one
UPDATE inv_stock_doc_item
SET idx = $2,
    qty = $3,
    base_qty = $4,
    material_code = $5,
    material_name = $6,
    material_spec = $7,
    unit_name = $8,
    remark = $9,
    material_id = $10,
    unit_id = $11,
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, idx, qty, base_qty, material_code, material_name, material_spec, unit_name,
          remark, inserted_at, updated_at, stock_doc_id, company_id, material_id, unit_id
`

type UpdateStockDocItemParams struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	Idx          int64           `db:"idx" json:"idx"`
	Qty          decimal.Decimal `db:"qty" json:"qty"`
	BaseQty      decimal.Decimal `db:"base_qty" json:"base_qty"`
	MaterialCode string          `db:"material_code" json:"material_code"`
	MaterialName string          `db:"material_name" json:"material_name"`
	MaterialSpec pgtype.Text     `db:"material_spec" json:"material_spec"`
	UnitName     string          `db:"unit_name" json:"unit_name"`
	Remark       pgtype.Text     `db:"remark" json:"remark"`
	MaterialID   uuid.UUID       `db:"material_id" json:"material_id"`
	UnitID       uuid.UUID       `db:"unit_id" json:"unit_id"`
}

func (q *Queries) UpdateStockDocItem(ctx context.Context, arg UpdateStockDocItemParams) (InvStockDocItem, error) {
	row := q.db.QueryRow(ctx, updateStockDocItem,
		arg.ID,
		arg.Idx,
		arg.Qty,
		arg.BaseQty,
		arg.MaterialCode,
		arg.MaterialName,
		arg.MaterialSpec,
		arg.UnitName,
		arg.Remark,
		arg.MaterialID,
		arg.UnitID,
	)
	var i InvStockDocItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.UnitName,
		&i.Remark,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.StockDocID,
		&i.CompanyID,
		&i.MaterialID,
		&i.UnitID,
	)
	return i, err
}

const voidStockDoc = `-- name: VoidStockDoc :one
UPDATE inv_stock_doc
SET status = 'voided',
    updated_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
RETURNING id, doc_no, direction, doc_date, summary, remarks, status, audited_at,
          inserted_at, updated_at, company_id, warehouse_id, created_by_id, audited_by_id
`

func (q *Queries) VoidStockDoc(ctx context.Context, id uuid.UUID) (InvStockDoc, error) {
	row := q.db.QueryRow(ctx, voidStockDoc, id)
	var i InvStockDoc
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Direction,
		&i.DocDate,
		&i.Summary,
		&i.Remarks,
		&i.Status,
		&i.AuditedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.WarehouseID,
		&i.CreatedByID,
		&i.AuditedByID,
	)
	return i, err
}
