// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supply_reconciliation.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getCompanyAccountDefault = `-- name: GetCompanyAccountDefault :one
SELECT id, inserted_at, updated_at, company_id, delivery_debit_account_id, delivery_credit_account_id, receipt_debit_account_id, receipt_credit_account_id
FROM sal_company_account_default
WHERE id = $1
`

func (q *Queries) GetCompanyAccountDefault(ctx context.Context, id uuid.UUID) (SalCompanyAccountDefault, error) {
	row := q.db.QueryRow(ctx, getCompanyAccountDefault, id)
	var i SalCompanyAccountDefault
	err := row.Scan(
		&i.ID,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.DeliveryDebitAccountID,
		&i.DeliveryCreditAccountID,
		&i.ReceiptDebitAccountID,
		&i.ReceiptCreditAccountID,
	)
	return i, err
}

const getCompanyAccountDefaultByCompany = `-- name: GetCompanyAccountDefaultByCompany :one
SELECT id, inserted_at, updated_at, company_id, delivery_debit_account_id, delivery_credit_account_id, receipt_debit_account_id, receipt_credit_account_id
FROM sal_company_account_default
WHERE company_id = $1
`

func (q *Queries) GetCompanyAccountDefaultByCompany(ctx context.Context, companyID uuid.UUID) (SalCompanyAccountDefault, error) {
	row := q.db.QueryRow(ctx, getCompanyAccountDefaultByCompany, companyID)
	var i SalCompanyAccountDefault
	err := row.Scan(
		&i.ID,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.DeliveryDebitAccountID,
		&i.DeliveryCreditAccountID,
		&i.ReceiptDebitAccountID,
		&i.ReceiptCreditAccountID,
	)
	return i, err
}

const getOrderFlowItem = `-- name: GetOrderFlowItem :one
SELECT id, flow_type, voucher_no, voucher_date, status, company_id, order_id, order_item_id, material_code, material_name, material_spec, customer_part_no, unit_name, qty
FROM scm_order_flow_item
WHERE id = $1::text
`

func (q *Queries) GetOrderFlowItem(ctx context.Context, dollar_1 string) (ScmOrderFlowItem, error) {
	row := q.db.QueryRow(ctx, getOrderFlowItem, dollar_1)
	var i ScmOrderFlowItem
	err := row.Scan(
		&i.ID,
		&i.FlowType,
		&i.VoucherNo,
		&i.VoucherDate,
		&i.Status,
		&i.CompanyID,
		&i.OrderID,
		&i.OrderItemID,
		&i.MaterialCode,
		&i.MaterialName,
		&i.MaterialSpec,
		&i.CustomerPartNo,
		&i.UnitName,
		&i.Qty,
	)
	return i, err
}

const getPurchaseReconciliation = `-- name: GetPurchaseReconciliation :one
SELECT id, reconciliation_no, reconciliation_type, party_type, party_id, posting_date, remarks, status, inserted_at, updated_at, company_id, debit_account_id, credit_account_id, created_by_id
FROM pur_reconciliation
WHERE id = $1
`

func (q *Queries) GetPurchaseReconciliation(ctx context.Context, id uuid.UUID) (PurReconciliation, error) {
	row := q.db.QueryRow(ctx, getPurchaseReconciliation, id)
	var i PurReconciliation
	err := row.Scan(
		&i.ID,
		&i.ReconciliationNo,
		&i.ReconciliationType,
		&i.PartyType,
		&i.PartyID,
		&i.PostingDate,
		&i.Remarks,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.CreatedByID,
	)
	return i, err
}

const getPurchaseReconciliationItem = `-- name: GetPurchaseReconciliationItem :one
SELECT id, idx, qty, base_qty, amount, base_amount, remarks, inserted_at, updated_at, reconciliation_id, company_id, receipt_item_id, outsourced_receipt_item_id
FROM pur_reconciliation_item
WHERE id = $1
`

func (q *Queries) GetPurchaseReconciliationItem(ctx context.Context, id uuid.UUID) (PurReconciliationItem, error) {
	row := q.db.QueryRow(ctx, getPurchaseReconciliationItem, id)
	var i PurReconciliationItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.Amount,
		&i.BaseAmount,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReconciliationID,
		&i.CompanyID,
		&i.ReceiptItemID,
		&i.OutsourcedReceiptItemID,
	)
	return i, err
}

const getSalesReconciliation = `-- name: GetSalesReconciliation :one

SELECT id, reconciliation_no, reconciliation_type, party_type, party_id, posting_date, remarks, status, inserted_at, updated_at, company_id, debit_account_id, credit_account_id, created_by_id
FROM sal_reconciliation
WHERE id = $1
`

// PR-2.16 的静态 SQLC seam。动态结构化筛选仍由领域模块在 ResourceMeta
// 白名单下构造；单行读取与受控来源读取保留为可生成、可审计的 SQL。
func (q *Queries) GetSalesReconciliation(ctx context.Context, id uuid.UUID) (SalReconciliation, error) {
	row := q.db.QueryRow(ctx, getSalesReconciliation, id)
	var i SalReconciliation
	err := row.Scan(
		&i.ID,
		&i.ReconciliationNo,
		&i.ReconciliationType,
		&i.PartyType,
		&i.PartyID,
		&i.PostingDate,
		&i.Remarks,
		&i.Status,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.CreatedByID,
	)
	return i, err
}

const getSalesReconciliationItem = `-- name: GetSalesReconciliationItem :one
SELECT id, idx, qty, base_qty, amount, base_amount, remarks, inserted_at, updated_at, reconciliation_id, company_id, delivery_item_id
FROM sal_reconciliation_item
WHERE id = $1
`

func (q *Queries) GetSalesReconciliationItem(ctx context.Context, id uuid.UUID) (SalReconciliationItem, error) {
	row := q.db.QueryRow(ctx, getSalesReconciliationItem, id)
	var i SalReconciliationItem
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Qty,
		&i.BaseQty,
		&i.Amount,
		&i.BaseAmount,
		&i.Remarks,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReconciliationID,
		&i.CompanyID,
		&i.DeliveryItemID,
	)
	return i, err
}
