// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadTodos = `-- name: CountUnreadTodos :one
SELECT count(*)::bigint
FROM sys_todo AS todo
LEFT JOIN sys_todo_state AS state
  ON state.todo_id = todo.id
 AND state.user_id = $1
WHERE todo.status = 'active'
  AND (
    $2::boolean
    OR todo.company_id = ANY($3::uuid[])
  )
  AND state.read_at IS NULL
  AND NOT (
    state.dismissed_at IS NOT NULL
    AND state.reset_basis_at IS NOT NULL
    AND state.reset_basis_at = todo.source_changed_at
  )
`

type CountUnreadTodosParams struct {
	UserID             uuid.UUID   `db:"user_id" json:"user_id"`
	BypassCompanyScope bool        `db:"bypass_company_scope" json:"bypass_company_scope"`
	CompanyIds         []uuid.UUID `db:"company_ids" json:"company_ids"`
}

func (q *Queries) CountUnreadTodos(ctx context.Context, arg CountUnreadTodosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadTodos, arg.UserID, arg.BypassCompanyScope, arg.CompanyIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSetupStatus = `-- name: GetSetupStatus :one
SELECT
  EXISTS (SELECT 1 FROM sys_setting WHERE setup_completed_at IS NOT NULL) AS initialized,
  EXISTS (SELECT 1 FROM sys_user) AS has_users
`

type GetSetupStatusRow struct {
	Initialized bool `db:"initialized" json:"initialized"`
	HasUsers    bool `db:"has_users" json:"has_users"`
}

func (q *Queries) GetSetupStatus(ctx context.Context) (GetSetupStatusRow, error) {
	row := q.db.QueryRow(ctx, getSetupStatus)
	var i GetSetupStatusRow
	err := row.Scan(&i.Initialized, &i.HasUsers)
	return i, err
}
