// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trading_quotation.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTradingQuotationCompany = `-- name: GetTradingQuotationCompany :one
SELECT id, base_currency_id
FROM bas_company
WHERE id = $1
`

type GetTradingQuotationCompanyRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	BaseCurrencyID uuid.UUID `db:"base_currency_id" json:"base_currency_id"`
}

func (q *Queries) GetTradingQuotationCompany(ctx context.Context, id uuid.UUID) (GetTradingQuotationCompanyRow, error) {
	row := q.db.QueryRow(ctx, getTradingQuotationCompany, id)
	var i GetTradingQuotationCompanyRow
	err := row.Scan(&i.ID, &i.BaseCurrencyID)
	return i, err
}

const getTradingQuotationMaterialSnapshot = `-- name: GetTradingQuotationMaterialSnapshot :one
SELECT m.id,
       m.code,
       m.name,
       m.spec,
       m.customer_part_no,
       m.is_customer_material,
       m.customer_id,
       u.id AS unit_id,
       u.name AS unit_name,
       (
         m.default_unit_id = u.id OR EXISTS(
           SELECT 1
           FROM inv_material_unit mu
           WHERE mu.material_id = m.id AND mu.unit_id = u.id
         )
       )::boolean AS unit_allowed
FROM inv_material m
JOIN bas_unit u ON u.id = $1::uuid
WHERE m.id = $2::uuid
`

type GetTradingQuotationMaterialSnapshotParams struct {
	UnitID     uuid.UUID `db:"unit_id" json:"unit_id"`
	MaterialID uuid.UUID `db:"material_id" json:"material_id"`
}

type GetTradingQuotationMaterialSnapshotRow struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	Code               string      `db:"code" json:"code"`
	Name               string      `db:"name" json:"name"`
	Spec               pgtype.Text `db:"spec" json:"spec"`
	CustomerPartNo     pgtype.Text `db:"customer_part_no" json:"customer_part_no"`
	IsCustomerMaterial bool        `db:"is_customer_material" json:"is_customer_material"`
	CustomerID         *uuid.UUID  `db:"customer_id" json:"customer_id"`
	UnitID             uuid.UUID   `db:"unit_id" json:"unit_id"`
	UnitName           string      `db:"unit_name" json:"unit_name"`
	UnitAllowed        bool        `db:"unit_allowed" json:"unit_allowed"`
}

func (q *Queries) GetTradingQuotationMaterialSnapshot(ctx context.Context, arg GetTradingQuotationMaterialSnapshotParams) (GetTradingQuotationMaterialSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getTradingQuotationMaterialSnapshot, arg.UnitID, arg.MaterialID)
	var i GetTradingQuotationMaterialSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CustomerPartNo,
		&i.IsCustomerMaterial,
		&i.CustomerID,
		&i.UnitID,
		&i.UnitName,
		&i.UnitAllowed,
	)
	return i, err
}

const tradingQuotationMaterialExists = `-- name: TradingQuotationMaterialExists :one
SELECT EXISTS(
  SELECT 1 FROM inv_material WHERE id = $1
)::boolean
`

func (q *Queries) TradingQuotationMaterialExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tradingQuotationMaterialExists, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const tradingQuotationPartyExists = `-- name: TradingQuotationPartyExists :one
SELECT CASE $1::text
  WHEN 'supplier' THEN EXISTS(
    SELECT 1 FROM pur_supplier WHERE id = $2::uuid
  )
  WHEN 'customer' THEN EXISTS(
    SELECT 1 FROM sal_customers WHERE id = $2::uuid
  )
  WHEN 'company' THEN EXISTS(
    SELECT 1 FROM bas_company WHERE id = $2::uuid
  )
  ELSE false
END::boolean
`

type TradingQuotationPartyExistsParams struct {
	PartyType string    `db:"party_type" json:"party_type"`
	PartyID   uuid.UUID `db:"party_id" json:"party_id"`
}

func (q *Queries) TradingQuotationPartyExists(ctx context.Context, arg TradingQuotationPartyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tradingQuotationPartyExists, arg.PartyType, arg.PartyID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
