// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouse_seed.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const companyHasWarehouses = `-- name: CompanyHasWarehouses :one
SELECT EXISTS (SELECT 1 FROM inv_warehouse WHERE company_id = $1)
`

func (q *Queries) CompanyHasWarehouses(ctx context.Context, companyID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, companyHasWarehouses, companyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createSeedWarehouse = `-- name: CreateSeedWarehouse :one
INSERT INTO inv_warehouse (name, is_leaf, company_id, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, is_leaf, active, is_outsourced, allow_negative,
          company_id, parent_id, account_id, party_type, party_id, inserted_at, updated_at
`

type CreateSeedWarehouseParams struct {
	Name      string     `db:"name" json:"name"`
	IsLeaf    bool       `db:"is_leaf" json:"is_leaf"`
	CompanyID uuid.UUID  `db:"company_id" json:"company_id"`
	ParentID  *uuid.UUID `db:"parent_id" json:"parent_id"`
}

type CreateSeedWarehouseRow struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	Name          string           `db:"name" json:"name"`
	IsLeaf        bool             `db:"is_leaf" json:"is_leaf"`
	Active        bool             `db:"active" json:"active"`
	IsOutsourced  bool             `db:"is_outsourced" json:"is_outsourced"`
	AllowNegative bool             `db:"allow_negative" json:"allow_negative"`
	CompanyID     uuid.UUID        `db:"company_id" json:"company_id"`
	ParentID      *uuid.UUID       `db:"parent_id" json:"parent_id"`
	AccountID     *uuid.UUID       `db:"account_id" json:"account_id"`
	PartyType     pgtype.Text      `db:"party_type" json:"party_type"`
	PartyID       *uuid.UUID       `db:"party_id" json:"party_id"`
	InsertedAt    pgtype.Timestamp `db:"inserted_at" json:"inserted_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSeedWarehouse(ctx context.Context, arg CreateSeedWarehouseParams) (CreateSeedWarehouseRow, error) {
	row := q.db.QueryRow(ctx, createSeedWarehouse,
		arg.Name,
		arg.IsLeaf,
		arg.CompanyID,
		arg.ParentID,
	)
	var i CreateSeedWarehouseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsLeaf,
		&i.Active,
		&i.IsOutsourced,
		&i.AllowNegative,
		&i.CompanyID,
		&i.ParentID,
		&i.AccountID,
		&i.PartyType,
		&i.PartyID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
